### ISSUE TITLE
🐛  onChange Event Misfiring

### ISSUE THREAD

**Issue by bayleedev** [testing-library/dom-testing-library#1000]
- `@testing-library/dom` version: v8.1.0
- Testing Framework and version:
- jest version: 26.6.3

### Relevant code or config:

This is what [the docs](https://preactjs.com/guide/v10/preact-testing-library) suggest trying

```diff
// test.js:36
-  if (false) {
+ {
    const field = await screen.getByRole('textbox', { name: 'Comment Body' });
    fireEvent.change(field, {
      value: 'user123', // the docs just suggest setting this one
    });
    expect(field.value).toEqual('user123'); // Received: "default_value"
  }
```

### What you did:

I made a few modifications to get it working, but it's reaching in kinda deep:

```javascript
// test.js:44
  // Change, working
  {
    const field = await screen.getByRole('textbox', { name: 'Comment Body' });
    const changeEvent = createEvent.change(field, {
      value: 'user123', // BROKE, possibly decorated in the library
      target: { value: 'user234' }, // ADD
    });
    changeEvent.inputType = 'insertText'; // ADD, required to get it to work
    await act(() => {
      return field.l.inputfalse(changeEvent);
      // return field.dispatchEvent(changeEvent) // DEL, this didn't work
    });
    // Assertion
    const textarea = screen.getByRole('textbox', { name: 'Comment Body' });
    expect(textarea.value).toEqual('on_change_value'); // SUCCESS!

    // Double assertion, to see if `body` was updated.
    const bodyData = screen.getByTestId('body-data');
    expect(bodyData.textContent).toEqual('on_change_value'); // SUCCESS!
  }
```

### What happened:

The elements onChange did not fire

### Reproduction:

Reproduction repository:

https://github.com/bayleedev/preact-change-issue

I [double posted](https://github.com/testing-library/preact-testing-library/issues/43) because I think the code's in this repo. I'm not familiar with the org so apologies for the spam.

**Comment by eps1lon** [comment]
Closing in favor of https://github.com/testing-library/preact-testing-library/issues/43
