### ISSUE TITLE
`:disabled` css selector does not work in fieldset

### ISSUE THREAD

**Issue by mayank99** [testing-library/dom-testing-library#1003]
- `@testing-library/react` version: 12.0.0
- Testing Framework and version: React 17.0.2
- DOM Environment: jsdom 16? unsure

### Relevant code or config:

```jsx
export const Component = () => (
  <fieldset disabled>
    <input />
    <input />
  </fieldset>
);
```

```js
it("should render disabled inputs in fieldset", () => {
  const { container } = render(<Component />);
  expect(container.querySelector("fieldset")).toBeTruthy();

  container.querySelectorAll("fieldset input").forEach((input) => {
    expect(input.matches(":disabled")).toBeTruthy(); // THIS FAILS
  });

  expect(container.querySelectorAll("fieldset input:disabled")).toHaveLength(2); // THIS FAILS TOO
});
```

### What you did:

1. Render input inside fieldset (the input itself does not have disabled attribute set)
2. Set fieldset to be disabled

### What happened:

1. Input renders as disabled in the browser
2. Input does not match `:disabled` CSS selector

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-forked-ohbcu?file=/src/__tests__/hello.js

### Problem description:

`:disabled` works perfectly fine in the browser, so I would expect it to work here too.

Weirdly, `toBeDisabled` from `@testing-library/jest-dom` works fine but it's not built in to jest, so I had to install it just for this one test.

### Suggested solution:

Considering that `toBeDisabled` works, maybe the `:disabled` selector should use similar logic?

**Comment by MatanBobi** [comment]
Hi @mayank99! Thanks for taking the time to open this one.
AFAIK, unfortunately the `matches` function for an element isn't implemented in our codebase but in [`jsdom`](https://github.com/jsdom/jsdom) or your testing environment.
I'd recommend opening an issue there.
If you think this is our issue, please feel free to comment here and I'll re-open it :)
Thanks again!

**Comment by mayank99** [comment]
> AFAIK, unfortunately the `matches` function for an element isn't implemented in our codebase but in [`jsdom`](https://github.com/jsdom/jsdom) or your testing environment.

What about `querySelector`/`querySelectorAll`? Is that also a problem with jsdom?

**Comment by MatanBobi** [comment]
> > AFAIK, unfortunately the `matches` function for an element isn't implemented in our codebase but in [`jsdom`](https://github.com/jsdom/jsdom) or your testing environment.
> 
> What about `querySelector`/`querySelectorAll`? Is that also a problem with jsdom?

Yep, both of them are native api's that are implemented in JSDOM for testing purposes :)
