### ISSUE TITLE
waitFor initial delay

### ISSUE THREAD

**Issue by michalenr** [testing-library/dom-testing-library#1004]
Add an option to `waitFor` to check for initial delay before firing the callback.

**Why?**

Here's my case:

I mock a server response with MSW. If response contains certain field, i need to show a button, if it doesn't - no button.

```js
await waitFor(
      () => {
        expect(btn).not.toBeInTheDocument();
      }
    );
```

I need to check for a scenario in which there is not field in the response and see if the button didn't appear.
However, `waitFor` gives a false-positive result even if the field is present.

**Comment by eps1lon** [comment]
Thanks for the feedback.

This can be implemented by waiting for a timer:

```ts
function sleep(sleepMS) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve();
    }, sleepMS)
  })
}


await sleep(initialDelay)
await waitFor(
      () => {
        expect(btn).not.toBeInTheDocument();
      }
    );
```

Since this is fairly trivial, and has a first-class API with [`timers/promises` in Node 16](https://nodejs.org/api/timers.html#timers_timers_promises_api), I don't see a strong argument to include this in the library.
