### ISSUE TITLE
ByRole can not find accessible input which browser shows

### ISSUE THREAD

**Issue by xxleyi** [testing-library/dom-testing-library#1005]
- `@testing-library/dom` version: @testing-library/cypress#@testing-library/dom@8.1.0
- Testing Framework and version: cypress 8.1.0
  
- DOM Environment: cypress, real browser, chrome 92

### Relevant code or config:

```js
screen.getByRole('textbox', {name: 'xxx'})
```

```js
# input structrue
    <input
      placeholder="test"
      style="width: 400px;"
      type="text"
    />
```

### What you did:

![image](https://user-images.githubusercontent.com/12626454/128954449-bc423267-5d81-4d31-b658-b2f32989eb00.png)

Browser can show accessible input, so I try find it with getByRole.

### What happened: 
can not find it with getByRole.

### Reproduction: 

https://codesandbox.io/s/react-testing-library-demo-forked-d1zme?file=/src/__tests__/input.js

### Problem description: 

Browser can show the accessible input with role and name, but getByRole can not find it.

### Suggested solution: 

maybe getByRole should consider support this case, where placeholder of input can act name of input.

**Comment by alexkrolick** [comment]
Is that a new feature of Chrome? I thought the `placeholder` was excluded from accessible name computation. I don't see mention of `placeholder` in the spec: https://www.w3.org/TR/accname-1.1/#mapping_additional_nd_te

**Comment by xxleyi** [comment]
> Is that a new feature of Chrome? I thought the `placeholder` was excluded from accessible name computation. I don't see mention of `placeholder` in the spec: https://www.w3.org/TR/accname-1.1/#mapping_additional_nd_te

I just found this question has already existed:  #926

**Comment by eps1lon** [comment]
Closing in favor of https://github.com/testing-library/dom-testing-library/issues/926
