### ISSUE TITLE
`ByRole` query gets empty accessible name for `li` elements

### ISSUE THREAD

**Issue by Belco90** [testing-library/dom-testing-library#1006]
- `@testing-library/dom` version: 8.1.0
- Testing Framework and version: jest v26.6.0
  
- DOM Environment: jsdom v26.6.2
  
- Node version: 14.15.4

### Relevant code or config:

```js
import { getByRole } from '@testing-library/dom';

function getExampleDOM() {
  const root = document.createElement('div');

  root.innerHTML = `
    <ul>
      <li>Item A</li>
      <li>Item B</li>
    </ul>
  `;

  return root;
}

test('should render list items', () => {
  const container = getExampleDOM();
  getByRole(container, 'list');

  // the following query fails since it can't find a listitem element with provided accessible name
  getByRole(container, 'listitem', { name: /item a/i });
});
```

### What you did:

I'm trying to query a specific `li` element using `ByRole` query + accessible name.

### What happened:

DOM Testing Library returns 0 elements matching the query since it can't find any accessible name for the `li` elements:
![Unable to find an accessible element with the role "listitem" and name `/item a/i`](https://user-images.githubusercontent.com/2677072/128983708-ea92729a-d68a-4b54-8cc2-8f331bc5a251.png)

### Reproduction:

I forked `dom-testing-library-template` and reproduced the issue. You can find it here: https://github.com/Belco90/dom-testing-library-template/blob/main/src/__tests__/index.test.js

### Problem description:
Correct me if I'm wrong, but `li` child should be its accessible name if it is a static text:
<img width="677" alt="accessible names for li elements in the browser" src="https://user-images.githubusercontent.com/2677072/128984137-856a06d0-8a36-455d-ba8a-332241422a98.png">

### Suggested solution:

Not really sure where the problem is located, to be honest.

**Comment by eps1lon** [comment]
Thanks for the report.

Does this problem reproduce when you run it locally (not on codesandbox.io) when the elements are connected to the document (not just to an unconnected `document.createElement('div')`)?

**Comment by Belco90** [comment]
> Does this problem reproduce when you run it locally (not on codesandbox.io) when the elements are connected to the document (not just to an unconnected `document.createElement('div')`)?

Yes. I originally spotted this using `react-testing-library`, which appends elements to the document. I can update the repo to reproduce this one too.

**Comment by eps1lon** [comment]
Now I remember: `listitem` isn't named by content but author (i.e. aria-label etc). You probably don't want to query by name but text.

Firefox devtools are not using "name" as specified by ARIA but rather a different interpretation (probably leaning towards what a screen reader would announce).

**Comment by eps1lon** [comment]
Also see https://github.com/w3c/aria/issues/1117 where it's explained in more detail why naming of listitem requires a lot of nuance (e.g. listitems containing lots of text).

**Comment by Belco90** [comment]
That's the info I was trying to look for but couldn't find anything, thanks!

I'll stick to `ByText` then.

**Comment by silvenon** [comment]
Just wanted to say thanks for this great explanation @eps1lon! 🥇
