### ISSUE TITLE
*ByRole form seems not to find <form /> elements

### ISSUE THREAD

**Issue by Sly321** [testing-library/dom-testing-library#1021]
Versions:

- `@testing-library/react`: ^11.2.5,
- `@testing-library/dom`: 7.29.4
- `@testing-library/jest-dom`: ^5.11.9,
  
Testcase:

```js
it(`testcase`, async () => {
    render(
        <div>
            <h1>helloworld</h1>
            <form>
                <h2>content</h2>
                <label htmlFor="tinput">hello</label>
                <input type="text" id="tinput" />
            </form>
        </div>
    )

    expect(screen.getByRole("form")).toBeInTheDocument()
})
```

### result:

```
    Unable to find role="form"

    <body
      class=""
    >
      <div>
          <h1>
            helloworld
          </h1>
          <form>
            <h2>
              content
            </h2>
            <label
              for="tinput"
            >
              hello
            </label>
            <input
              id="tinput"
              type="text"
            />
          </form>
        </div>
    </body>
```

### Expected result:

Find the form as a representation of a form role element.

### Problem description:

The form should be recognized as a aria form role, or am I wrong? https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Form_Role

Thanks for your effort!

**Comment by eps1lon** [comment]
Thanks for the feedback.

We closely follow ARIA specifications. [`html-aam`](https://www.w3.org/TR/html-aam-1.0/) specifies that [`<form />` only has the `form` role if it has an accessible name](https://www.w3.org/TR/html-aam-1.0/#html-element-role-mappings).

Hope this clears things up. If you think `<form />` should always have the `form` role, please open an issue on the [`html-aam` repository](https://github.com/w3c/html-aam). But please consider prior discussions such as https://github.com/w3c/html-aria/issues/94

**Comment by Sly321** [comment]
Thanks for clearing that out!
