### ISSUE TITLE
Compile error from query-helpers.d.ts

### ISSUE THREAD

**Issue by pypmannetjies** [testing-library/dom-testing-library#1025]
It looks like the latest version of the DOM testing library types has a compile error:

```
node_modules/@testing-library/dom/types/query-helpers.d.ts(6,60): error TS1005: ',' expected.
```

I believe it was introduced in [this PR](https://github.com/testing-library/dom-testing-library/pull/1016)

- `@testing-library/dom` version: 8.3.0
- Testing Framework and version: Mocha 9.1.1
- DOM Environment: N/A

### Relevant code or config:

```js
var your => (code) => here;
```

### What you did:

Compiled a file which is using the dom-testing type

```
import * as domTesting from '@testing-library/dom';
```

### What happened:

Compile error: 

```
node_modules/@testing-library/dom/types/query-helpers.d.ts(6,60): error TS1005: ',' expected.
```

### Suggested solution:

It looks like the error is on this line

```
export type GetErrorFunction<Arguments extends any[] = [alt: string]> = (
```

It's complaining about the `:` after the `alt`

Not sure what the intended type is.

**Comment by timdeschryver** [comment]
What TypeScript version are you using @pypmannetjies ?
I'm not 100% sure, but I think you need to be on v4.1 or higher.

**Comment by ozluy** [comment]
@pypmannetjies are you on Windows? If yes I had the same problem after Windows updates...

**Comment by pypmannetjies** [comment]
> @pypmannetjies are you on Windows? If yes I had the same problem after Windows updates...

No, this is on Mac

**Comment by sujitykulkarni** [comment]
Same here. It occurred to me when I installed it along with `[@testing-library/user-event](https://github.com/testing-library/user-event#installation)`
My config:
typescript 3.8.3
@testing-library/user-event 13.2.1
