### ISSUE TITLE
screen.getByRole("button") fails without role="button" on element.

### ISSUE THREAD

**Issue by bradwoods** [testing-library/dom-testing-library#1032]
I have a simple test that is attempting to query a button using `screen.getByRole("button")`. The test fails unless role="button" is added to the element (which shouldn't be required). This is a bare-bones example so I'm assuming I'm doing something basic wrong. 

- `@testing-library/jset-dom` version: 5.14.1
- `@testing-library/react` version: 12.1.0

https://codesandbox.io/s/testing-library-ckvtt?file=/src/index.test.tsx

![image](https://user-images.githubusercontent.com/28694502/133366474-261ca833-68f6-4395-be41-b07f307249e2.png)

**Comment by eps1lon** [comment]
Thanks for the feedback.

Unfortunately, this is an issue with CodeSandbox not Testing Library. See https://github.com/codesandbox/codesandbox-client/issues/5887 for more information.

**Comment by bradwoods** [comment]
> Thanks for the feedback.
> 
> Unfortunately, this is an issue with CodeSandbox not Testing Library. See [codesandbox/codesandbox-client#5887](https://github.com/codesandbox/codesandbox-client/issues/5887) for more information.

Thanks for the heads up.
