### ISSUE TITLE
Make `screen` query methods generic

### ISSUE THREAD

**Issue by nstepien** [testing-library/dom-testing-library#1033]
- `@testing-library/dom` version: 8.5.0
- Testing Framework and version: jest@27.2.0
  
- DOM Environment: jsdom
  

### Relevant code or config:

```ts
import { screen } from '@testing-library/dom';

screen.getByText<HTMLElement>('test');
```

### What you did:

Defined a type argument for `getByText`

### What happened:

```
> tsc

test.ts:3:18 - error TS2558: Expected 0 type arguments, but got 1.

3 screen.getByText<HTMLElement>('test');
                   ~~~~~~~~~~~
```

### Reproduction:

```ts
import { screen } from '@testing-library/dom';

screen.getByText<HTMLElement>('test');
```

### Problem description:

While the methods are generic, the way they're redefined on the `screen` object for example makes them lose their genericness.
Original request: https://github.com/testing-library/dom-testing-library/issues/615
PR which made the methods generic: https://github.com/testing-library/dom-testing-library/pull/1023

**Comment by timdeschryver** [comment]
I tried to solve this, but AFAIK there isn't a way to "automatically" add the generic to the queries of the screen object.
The only way I was able to add a generic, was to manually add the queries on `screen`.

I'll leave this open for someone that is able to add the generic "automatically".
If no-one is able to do this, I can open a PR with my current implementation.

**Comment by eps1lon** [comment]
> If no-one is able to do this, I can open a PR with my current implementation.

Let's start with this. We can always improve later though from my understanding, we can't carry generics over automatically. So the manual approach is probably going to stick for a while.
