### ISSUE TITLE
event.currentTarget is null

### ISSUE THREAD

**Issue by droganov** [testing-library/dom-testing-library#1039]
For `@testing-library/dom`

I'm working on a validation function that is getting form instance from the event.

Since the form-level event can be initiated by the input element, I have to rely on `currentTarget` and can not use `event.target`.

The mock:
```js
function mockFrom(handleValidate) {
  let form = document.createElement('form')
  form.innerHTML = `
    <input name="name" />
    <button type="submit">OK</button>
  `
  form.addEventListener('submit', handleValidate)
  return {
    submit() {
      fireEvent.submit(form, { currentTarget: form })
    }
  }
}
```

The problem:
```js
new FormData(event.currentTarget) // => TypeError: FormData constructor: Argument 1 is not an object.
```

**Comment by eps1lon** [comment]
Thanks for the feedback.

> fireEvent.submit(form, { currentTarget: form })

This is unnecessary. `fireEvent.submit(form)` does the same thing.

That being said, I can't reproduce the issue: https://codesandbox.io/s/testinglibrary-submit-event-currenttarget-rm3nn

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by droganov** [comment]
@eps1lon thank you for the quick reply, it's true your example works...

My bad, I missed that the case was using an async handler, sorry for that

This snippet is reproducing the case for me:
```js
import { fireEvent } from "@testing-library/dom";

let form = document.createElement("form");
form.innerHTML = `
    <input name="name" />
    <button type="submit">OK</button>
  `;
form.addEventListener("submit", (event) => {
  Promise.resolve().then(
    () => console.log(event.currentTarget)
  )
});

fireEvent.submit(form);
```

I [created](https://jsbin.com/camafohiha/edit?js,console,output) a browser case, and I can see that the browser event does not degrade over a time

**Comment by eps1lon** [comment]
This is either expected behavior, or a browser quirk. Though not actionable for us since the same behavior occurs without using `@testing-library/dom`. 

`event.currentTarget` changes while the event propagates through the DOM tree. By the time `Promise.resolve().then()` is reached (i.e. microtask queue is emptied), the event propagation has seemingly already concluded when a synthetic submit event is fired.

**Comment by MatanBobi** [comment]
Following what @eps1lon wrote, I believe the reason this isn't working for you is that [`currentTarget`](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget) is a read-only property so it can't be changed programmatically.
You can though, do something like this:
```
const myEvent = createEvent.submit(form);
Object.defineProperty(myEvent, "currentTarget", { value: form });
fireEvent(form, myEvent);
```

This is the "workaround" to mimic such use-cases in tests.
