### ISSUE TITLE
Thre should be a query that works for <button> or <input type=button value="">

### ISSUE THREAD

**Issue by BenoitAverty** [testing-library/dom-testing-library#1043]
### Describe the feature you'd like:

There should be a query that works for both these elements : 

- `<button>Click Me</button>`
- `<input type="button" value="Click Me" />`

Currently, `getByDisplayValue("Click Me")` will find the input but not the button, and `getByText("Click Me")` is the opposite. There is no way to write a test that will stay green if i refactor one into the other (Assuming that for whatever reason I can't use getByRole or other queries)

### Suggested implementation:

getByText finding the input is counter-intuitive I think, so in my opinion the best way would be to change the `getByDisplayValue` query so that it works with button elements.

### Describe alternatives you've considered:

There are many workarounds and alternatives, but they rely on using less specific queries, or queries that make the tests less close to what a user would do, which is the apposite of what I'm trying to do if I'm using testing-library.

**Comment by afontcu** [comment]
Hi!

> but they rely on using less specific queries

Isn't quite the opposite? `getByRole` would work in both cases and it is the default, suggested query method.

Also, as far as I can remember, `getByDisplayValue` only works with input, textarea, or select elements (because are the only elements that can actually "display" a value – a button does no).

**Comment by BenoitAverty** [comment]
getByRole needs the "role" attribute to be present. Unfortunately it's not always the case.

You are correct on the behaviour of `getByDisplayValue`, my request comes from the fact that `<input type="button" value="toto">` or `<input type="submit" value="toto">` look exactly the same to an end user as `<button>toto</button>`. This is why I would like to have a query that matches both versions.

**Comment by timdeschryver** [comment]
> and getByText("Click Me") is the opposite

Can you share an example where `getByText` doesn't find the element?
AFAK it does find it, see [a playground](https://testing-playground.com/gist/854b09ce9893c1d15eb0500dd99c52f5/bbbc76d850d3b398ff8b4f1edf55a8ba81493be7).

> my request comes from the fact that <input type="button" value="toto"> or <input type="submit" value="toto"> look exactly the same to an end user as <button>toto</button>. This is why I would like to have a query that matches both versions.

`getByDisplayValue` finds both buttons - [playground](https://testing-playground.com/gist/51dc7b881211203362b536f24aad94c7/f99bdec6baaae2c7a9377f1163b8d2839b41866b)

**Comment by afontcu** [comment]
> getByRole needs the "role" attribute to be present. Unfortunately it's not always the case.

getByRole actually queries by [implicit roles](https://www.w3.org/TR/html-aria/#docconformance) (for instance, a Button element has an implicit `button` role) - [playground](https://testing-playground.com/gist/5a13d2a2c96beb68862d2c6516a018db/2816b6ff93090fff8b04073f3ef0594effa25d97).

**Comment by BenoitAverty** [comment]
Thanks ! I realise what I want is already the way it works :D

I misread the documentation there : https://testing-library.com/docs/queries/bytext, missed the line 

> It also works with inputs whose type attribute is either submit or button

I also was not aware of the way getByRole works.

Should have tried before filing the issue :)
