### ISSUE TITLE
feat: *NthBy*

### ISSUE THREAD

**Issue by ghengeveld** [testing-library/dom-testing-library#1056]
### Describe the feature you'd like:

I would like to add a new set of APIs to get/find/query for the nth result. So that would give us `getNthByText`, `findNthByRole` etc. For example:

```js
await screen.findNthByRole(0, 'button')
```

This would be similar to doing `findAllBy(...)[n]`, but without the awkward `(await findAllByRole('button'))[0]` syntax (extra parenthesis needed for the `await`).

The API is similar to `toHaveBeenNthCalledWith` in Jest.

Additionally, I am working on the Interactions addon for Storybook which provides a GUI for Testing Library:

<img width="822" alt="Screenshot 2021-10-14 at 15 56 58" src="https://user-images.githubusercontent.com/321738/137332101-22105a9e-7c49-48b4-b4c9-25389f48d267.png">

However, when you do things like `getAllByRole('button')[0]`, it's no longer able to track the nested call reference, and it falls back to showing the underlying value (the 0th item in the array):

<img width="819" alt="Screenshot 2021-10-14 at 15 58 41" src="https://user-images.githubusercontent.com/321738/137332464-465e3a2a-0dc9-4493-9c1b-a046e60eec0e.png">

This can only be avoided by having a dedicated API call, for which the result can then be directly fed into the userEvent method.

I'm totally willing to implement this, no problem.

**Comment by alexkrolick** [comment]
The general recommendation if you want a specific item from a list query, is to replace it with a single item query that includes the attributes you need to identify the item that you want. Otherwise the test is susceptible to looking at the wrong item if some one adds another matching element before the one you want.
