### ISSUE TITLE
jQuery on Click event with jQuery Object using dom-test-library 

### ISSUE THREAD

**Issue by amanjaintkg9509** [testing-library/dom-testing-library#1079]
- `@testing-library/dom` version:
- Testing Framework and version:
  
- DOM Environment:
  

Relevant code or config

```js

```

What you did:

What happened:

Reproduction repository:
https://github.com/testing-library/dom-testing-library-template

Problem description:

Suggested solution:

**Comment by timdeschryver** [comment]
I'm closing this issue, feel free to reopen if you add more details to the issue report.
