### ISSUE TITLE
<input type="date" /> is missing a role

### ISSUE THREAD

**Issue by juanca** [testing-library/dom-testing-library#1103]
- `@testing-library/react` version: ^12 (latest)
- Testing Framework and version: jest@^27 (latest)
- DOM Environment: jest-dom@^5 (latest)
- Reproducible on codesandbox and local machine with node@^14

### Relevant code or config:

See repro codesandbox. 

### What you did:

Query for an input of type `date` with a given label.

### What happened:

The input is disregarded as having _any_ accessible role. 

### Reproduction:

https://codesandbox.io/s/date-textbox-bug-e5j56?file=/src/index.test.js

### Problem description:

An `input` normally has a `textbox` role. I believe a `type="date"` input has a `date` role -- but I don't really know where to verify this information -- but even its `textbox` role is missing here.

**Comment by eps1lon** [comment]
Thanks for opening this ticket.

I can understand the confusion but as it stands right now, `<input type="date" />` has no role. We follow `html-aria` which defines the mappings.

As you can see in https://www.w3.org/TR/2021/REC-html-aria-20211209/#docconformance there's no mapped role for `<input type="date" />`
