### ISSUE TITLE
`fireEvent.keyPress` doesn't work as expected (doesn't change the value of input)

### ISSUE THREAD

**Issue by dehghani-mehdi** [testing-library/dom-testing-library#1104]
- `@testing-library/dom` version: 8.11.1
- Testing Framework and version: Jest v27.3.1
- DOM Environment: Firefox latest

### Relevant code or config:

```js
const handleKeyPress = e => {
    if(e.key is not numeric) e.preventDefault();
}

<input
    onKeyPress={handleKeyPress}
/>
```

### What you did:

```
const input = screen.getByLabelText('textbox');
fireEvent.keyPress(input, { key: '5', keyCode: 53, charCode: 53, code: 'Numpad5' });
fireEvent.keyPress(input, { key: 'x', keyCode: 120, charCode: 120, code: 'KeyX' });

expect(screen.getByDisplayValue('5')).toBeInTheDocument();
```

### What happened:

Test failed and the value of input is _empty_ and doesn't changed at all.

### Problem description:

`fireEvent.keyPress` doesn't change the value of the input (doesn't trigger change event)

### Suggested solution:

:)

**Comment by timdeschryver** [comment]
This is expected because keypress doesn't set the value of an input.
It's also unclear what you want to test here, if you need help feel free to join our [Discord server](https://discord.com/invite/testing-library) and ask for help there.

**Comment by dehghani-mehdi** [comment]
@timdeschryver do not comment on my reported issues again, thank you!
