### ISSUE TITLE
how to use screen.logTestingPlaygroundURL()

### ISSUE THREAD

**Issue by lucasp-cit** [testing-library/dom-testing-library#1110]
Hey guys,

in our project here, we are trying to use screen.logTestingPlaygroundURL()

but we are having the following error message:

 TypeError: screen.logTestingPlaygroundURL is not a function

my suspicious is that we are not using the correct version or some other dependency is not updated.

could you, please, help me figure out what are we missing?

package.json:
    "@testing-library/dom": "^8.11.3",
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.7",

my test:

  test("if grid will be loaded", async () => {
    const screen = renderComponent()

    await AgGridTest.waitForGridToBeInTheDOM()
    await AgGridTest.waitForDataToHaveLoaded()
    
    screen.debug()
    screen.logTestingPlaygroundURL()

  })

screen.debug() works fine...

only screen.logTestingPlaygroundURL() is not being found...

any idea?

**Comment by timdeschryver** [comment]
Please create a reproduction, without it we can't offer much help.
What got my attention is that `screen` isn't the Testing Library screen instance, but your own implementation - so probably the problem lies within  `renderComponent`.

If that's not the case, feel free to reopen the issue.
