### ISSUE TITLE
Incorrect role when searching for checkbox

### ISSUE THREAD

**Issue by OueslatiGhaith** [testing-library/dom-testing-library#1122]
- `@testing-library/dom` version: ^5.16.3
- Testing Framework and version: vitest ^0.8.2
  
- DOM Environment: happydom and jsdom 
  

### Relevant code or config:

```js
import { render, screen } from "@testing-library/react";
import Checkbox from ".";

describe("checkbox", () => {
  it("should render", () => {
    render(<Checkbox />);
    const checkbox = screen.getByRole("checkbox");
    expect(checkbox).toBeInTheDocument();
  });
});

```
```ts
type Props = {
  label?: string | React.ReactNode;
  value?: "true" | "false";
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
};

const Checkbox: React.FC<Props> = (props) => {
  return (
    <div className="flex flex-row items-center gap-2">
      <input
        id={props.label?.toString()}
        type="checkbox"
        value={props.value}
        onChange={props.onChange}
        className="cursor-pointer rounded-sm border border-greyMedium bg-white ring-0 ring-transparent checked:bg-darkMedium hover:bg-greyLight checked:hover:bg-darkMedium focus:ring-0 checked:focus:bg-darkMedium"
      />
      {props.label && (
        <label htmlFor={props.label.toString()}>{props.label}</label>
      )}
    </div>
  );
};

export default Checkbox;

```

### What you did:
Trying to test if a checkbox renders properly by using get by role

### What happened:
didn't get the element, and got instead role "searchbox"

```
TestingLibraryElementError: Unable to find an accessible element with the role "checkbox"

Here are the accessible roles:

  searchbox:

  Name "":
  <input
    class="cursor-pointer rounded-sm border border-greyMedium bg-white ring-0 ring-transparent checked:bg-darkMedium hover:bg-greyLight checked:hover:bg-darkMedium focus:ring-0 checked:focus:bg-darkMedium"
    defaultvalue=""
    type="checkbox"
    value=""
  />

  --------------------------------------------------

Ignored nodes: comments, <script />, <style />
<body>
  <div>
    <div
      class="flex flex-row items-center gap-2"
    >
      <input
        class="cursor-pointer rounded-sm border border-greyMedium bg-white ring-0 ring-transparent checked:bg-darkMedium hover:bg-greyLight checked:hover:bg-darkMedium focus:ring-0 checked:focus:bg-darkMedium"
        defaultvalue=""
        type="checkbox"
        value=""
      />
    </div>
  </div>
</body>
 ❯ Object.getElementError node_modules/@testing-library/dom/dist/config.js:38:19
 ❯ node_modules/@testing-library/dom/dist/query-helpers.js:90:38
 ❯ node_modules/@testing-library/dom/dist/query-helpers.js:62:17
 ❯ node_modules/@testing-library/dom/dist/query-helpers.js:111:19
 ❯ app/components/ui/checkbox/checkbox.spec.tsx:7:28
      5|   it("should render", () => {
      6|     render(<Checkbox />);
      7|     const checkbox = screen.getByRole("checkbox");
       |                            ^
      8|     expect(checkbox).toBeInTheDocument();
      9|   });
```
### Problem description:

given that the input has a role of "checkbox", I would expect the accessible roles to contain "checkbox", but it does not, and also contains "searchbox" for some reason

**Comment by timdeschryver** [comment]
Could you reproduce this in a codesanbox please?
I tried to, but the [test is green](https://codesandbox.io/s/unruffled-smoke-gn7053?file=/src/index.test.js).

**Comment by OueslatiGhaith** [comment]
I haven't been able to isolate the problem, might be something with my specific configuration.
But here's the link to my repo
[repo](https://github.com/OueslatiGhaith/pfa-remix)
the specific test that's causing the issue can be found under /app/components/ui/checkbox/checkbox.spec.tsx

**Comment by wieringen** [comment]
I have the same problem, also using happy-dom and vitest. 

TestingLibraryElementError: Unable to find an accessible element with the role "checkbox"

**Comment by fauxparse** [comment]
@OueslatiGhaith I'm seeing this too under `happy-dom`. When I change my environment to use `jsdom`, the test passes.

**Comment by eps1lon** [comment]
I would file this against `happy-dom`. It's unlikely that this issue is on our side considering it has been working in JSDOM and browsers for a while now.

**Comment by mmalomo** [comment]
I've solved this like this:

`screen.getByRole('checkbox', { hidden: true });`

In my case, I was using the input element with `hidden: true`

```
  <input
      type="checkbox"
      hidden={true}
      ref={ref}
      checked={isChecked}
      onChange={(e) => onChange(e, props.item)}
      {...htmlInputProps}
  />
```

**Comment by CyrilQuandalle** [comment]
Thanks @mmalomo for your workaround, I had the same issue using `jsdom` but without setting `hidden={true}` . That's a bit weird to need that though.

**Comment by capricorn86** [comment]
This has been fixed in Happy DOM now:
https://github.com/capricorn86/happy-dom/releases/tag/v9.10.3
