### ISSUE TITLE
[feature] add an option to return value from `logTestingPlaygroundURL` instead of printing to console

### ISSUE THREAD

**Issue by kaminskypavel** [testing-library/dom-testing-library#1125]
### Describe the feature you'd like:
`logTestingPlaygroundURL` is such a powerful feature 💪!
The only issue with it is always printed to the console if you're using test runners such as (wallaby.js) this is extremely inconvenient.

it'd be great to have a similar `getTestingPlaygroundURL` method or add Options parameters to the original method.

### Suggested implementation:

would you be open for a PR?

### Teachability, Documentation, Adoption, Migration Strategy:
[Test](https://github.com/testing-library/dom-testing-library/blob/f27d14c18c02c412635d33fdaa1cfdaa44c14a5a/src/__tests__/screen.js#L43)

once this is implemented we will be able to work faster with the value both in VSCode and other IDE's

**Comment by MatanBobi** [comment]
Hi @kaminskypavel, thanks for the detailed request.
Any chance you can elaborate a little bit more about the need? I understand what you're looking for but just trying to understand if this is something that's worth adding to the core library and whether it can be done on the user-space.

**Comment by MatanBobi** [comment]
Hi @kaminskypavel, sorry it took me some time to respond.
I understand what you're saying, I think we can support this one, even if the use cases are minimal.
This one is up for grabs, I'll give it a try if I'll have an hour soon..
