### ISSUE TITLE
Query all Input Fields

### ISSUE THREAD

**Issue by DarkTrick** [testing-library/dom-testing-library#1162]
Not sure, if this is actually possible...

### Motivation
I'd like to be able to figure out, if someone changed the UI (added input element to form) without changing the test. 

### Describe the feature you'd like:

Function call to query all input fields (like `queryAllInputFields`)

### Describe alternatives you've considered:

AFAIK there is none.

### Teachability, Documentation, Adoption, Migration Strategy:

```
  const inputs = screen.queryAllInputs();
  expect(inputs.length).toBe(5);
  expect(inputs[0].value).toBe("...");
```

**Comment by timdeschryver** [comment]
You can query the DOM if you want.
Depending on your use case, you can use `getAll` queries or just `document.querySelectorAll`

```
const inputs =  screen.getAllByRole('textbox');
const inputs = document.querySelectorAll('input');
// or another variant
```

**Comment by DarkTrick** [comment]
Then this is perhaps a documentation issue(?)
Eg. [The cheat sheet](https://testing-library.com/docs/react-testing-library/cheatsheet/) says `ByRole find by aria role`. Would be very nice if the documentation would be more clear about this :)

**Comment by MatanBobi** [comment]
@DarkTrick `ByRole` uses implicit or explicit roles, in this case an input element without a type defaults to `role="textbox"`.
More about this can be found in the [ARIA spec](https://www.w3.org/TR/html-aria/).
