### ISSUE TITLE
`getByRole('meter')` doesn't find `meter` element

### ISSUE THREAD

**Issue by idanen** [testing-library/dom-testing-library#1171]
- `@testing-library/dom` version: ^8.17.0
- Testing Framework and version: jest ^28.1.0
- DOM Environment: In codesandbox

### Relevant code or config:

```js
test('getting by implicit "meter" role', () => {
  const aValue = 21;
  render(<Meter value={aValue} />);
  expect(screen.getByRole("meter")).toHaveValue(aValue);
});

function Meter({
  value = 0,
  min = 0,
  max = 0,
  low = 3,
  high = 90,
  label = "meter"
}) {
  return (
    <meter
      aria-label={label}
      value={value}
      min={min}
      max={max}
      low={low}
      high={high}
    />
  );
}
```

### What you did:

Tried to fetch by (implicit) meter role

### What happened:

Failed to get element

### Reproduction:

https://codesandbox.io/s/react-testing-library-getbyrole-meter-forked-ziqc09

### Problem description:

Should be able to fetch a `meter` element by implicit role

**Comment by MatanBobi** [comment]
Hi @idanen!
Thanks for opening this one :)
Looking at the spec, `meter` doesn't have an implicit role:
![image](https://user-images.githubusercontent.com/12711091/191218529-be470ae5-5e3b-4942-a5c4-74c783002190.png)
https://www.w3.org/TR/html-aria/

Where did you see that it does? Remember that `aria-query` follows the spec as is and browsers might not.

**Comment by MatanBobi** [comment]
Yeah, sorry about that :)

**Comment by Blacktiger** [comment]
Maybe we should re-open this issue? Looks like the spec now specifies that meter is an implicit role.

<img width="809" alt="Screenshot 2023-11-07 at 5 20 44 PM" src="https://github.com/testing-library/dom-testing-library/assets/86939/375869d9-4afa-46e9-a115-d63d40129a18">

https://www.w3.org/TR/html-aria/
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter

**Comment by MatanBobi** [comment]
Thanks @Blacktiger!
I've tested this in our `alpha` version of `@testing-library/dom` and it works. We're testing it in multiple places to check for regressions so it's not yet released.

**Comment by Blacktiger** [comment]
For now we just used a data-testid, but I'll definitely want to get our version upgraded when you guys do the final release. We really like how testing-library works and have been very happy with it, so thanks for all the work you guys have done on it.
