### ISSUE TITLE
Overriding testIdAttribute don't work in 8.19.0

### ISSUE THREAD

**Issue by jarlef** [testing-library/dom-testing-library#1177]
- `@testing-library/dom` version: 8.19.0
- Testing Framework and version: vitest 0.24.0
  
- DOM Environment: happy-dom
  

### Relevant code or config:

```js
import { configure } from '@testing-library/dom';

configure({
  testIdAttribute: 'data-eid',
});

```

### What you did:

- Upgraded from version 8.18.1 to 8.19.0
- Ran tests 

### What happened:

The testing framework uses the default `data-testid` attribute instead of the override

```
TestingLibraryElementError: Unable to find an element by: [data-testid="my-test-id"]
```

### Reproduction:

https://codesandbox.io/s/jovial-lucy-6j2l5h?file=/src/App.test.tsx

**Comment by timdeschryver** [comment]
Could you please include a reproduction?
It's hard to help without it.

**Comment by jarlef** [comment]
I have attached a link to a repro sandbox
