### ISSUE TITLE
Custom testIdAttribute has no effect after upgrading to 8.19.1

### ISSUE THREAD

**Issue by jarlef** [testing-library/dom-testing-library#1199]
After bumping `@testing-library/dom` from `8.19.0`  to `8.19.1` all the spec tests fails on the following line when using custom test attribute (data-eid)
 
```typescript 
await waitFor(() => screen.getByTestId('my-id'));`
```

setupTests.ts
```typescript
configure({
  testIdAttribute: 'data-eid',
});
```

If i revert to use the default `data-testid` then getByTestId is able to fetch the element from the DOM

- `@testing-library/dom` version: 8.19.1
- Testing Framework and version: vitest@0.26.2
  
- DOM Environment: happy-dom@8.1.1
  

### Relevant code or config:

```typescript
configure({
  testIdAttribute: 'data-eid',
});
```

```typescript 
await waitFor(() => screen.getByTestId('my-id'));`
```

setupTests.ts

### What you did:

Upgrade to latest version

**Comment by eps1lon** [comment]
You probably have multiple versions of `@testing-library/dom` or `@testing-library/react` installed. Make sure that only a single version of these libraries is installed. If you're unsure on how to do that, you can ask in the [Testing Library Discord server](https://testing-library.com/discord).
