### ISSUE TITLE
When using "useFakeTimers", "findBy*" queries aren't resolved

### ISSUE THREAD

**Issue by JZalfen** [testing-library/dom-testing-library#1218]
- `@testing-library/dom` version: 9.0.0
- Testing Framework and version: `vitest` version: 0.28.5 with `@testing-library/react` version: 14.0.0
  
- DOM Environment: `jsdom` version: 21.1.0
  

### Relevant code or config:

```tsx
it('with fake timers, not working :(', async () => {
  vi.useFakeTimers();

  render(<TestComponent />);

  screen.getByText('Apple');
  vi.runOnlyPendingTimers();

  // this promise never resolves with fake timers
  await screen.findByText('Pear');

  // restore to real timers
  vi.useRealTimers();
});
```

### What you did:

Using "useFakeTimers" with "findBy*" queries.

### What happened:

Timeout on first usage of "screen.findByText".

### Reproduction:

Stackblitz: https://stackblitz.com/edit/vitejs-vite-fwc91c?file=src/TestComponent.spec.tsx
To run test: execute "vitest" in terminal

### Problem description:

The test runs into a timeout.

### Suggested solution:

none

**Comment by BC-M** [comment]
With `@testing-library/react` version 13.4.0 (using `@testing-library/dom` version 8.20.0) it works.

Stackblitz: https://stackblitz.com/edit/vitejs-vite-mfzplb?file=src/TestComponent.spec.tsx

So it looks like a regression of `@testing-library/dom` version 9.

**Comment by BC-M** [comment]
For me `vi.useFakeTimers({ shouldAdvanceTime: true });` fixed it for `@testing-library/dom` v9:

https://stackblitz.com/edit/vitejs-vite-jjkbqn?file=src/TestComponent.spec.tsx
