### ISSUE TITLE
TextEncoder is not defined

### ISSUE THREAD

**Issue by nikgun1984** [testing-library/dom-testing-library#1245]
After upgrading to jest29.5 from jest27, i am getting the following error: "ReferenceError: TextEncoder is not defined". I imported TextEncoder from utils but it still shows the same error. `> 10 | import { JSDOM } from 'jsdom'`

**Comment by MatanBobi** [comment]
This looks like an issue in jest and not something we have a way to fix. There are [some workarounds](https://github.com/inrupt/solid-client-authn-js/issues/1676#issuecomment-1617024437) already available so I'm closing this one.
Thanks.

**Comment by luchillo17** [comment]
This is not an issue in jest, it's in jsdom, been like that for years and we can only work around it until it's fixed.
https://github.com/jsdom/jsdom/issues/2524
