### ISSUE TITLE
`getByRole("option", { name: "..." })` does not match element contents

### ISSUE THREAD

**Issue by TrevorRice** [testing-library/dom-testing-library#1274]
- `@testing-library/dom` version: `8.13.0`
- `@testing-library/jest-dom` version: `5.16.4`
- `@testing-library/react` version: `13.2.0`

### Relevant code or config:

I have an `Option` component that simply wraps its `children` in a `<div role="option">`:
```js
const Option = (props) => {
  return <div id="..." role="option" aria-selected="...">{props.children}</div>
}

// DOM
<div id="..." role="option" aria-selected="...">Dog</div>
```

### What you did:

I've been trying to query for a specific option via `getByRole` in my unit tests:
```js
getByRole("option", { name: "Dog" })
```

### What happened:

I receive the following error:
```
TestingLibraryElementError: Unable to find an element with the role "option" and name "Dog"

Here are the available roles:
...
 --------------------------------------------------
      option:

      Name "":
      <div
        aria-selected="false"
        id=":r3l:"
        role="option"
      />

```

Despite the element's accessible name being "Dog" as demonstrated by inspecting the accessibility tree:

![Accessibility panel of Chrome's development tools noting "dog" as the accessible name of the element](https://github.com/testing-library/dom-testing-library/assets/3644075/84e7ba2d-eeef-4631-a2be-479843dcb17a)
 
![Accessibility panel of Firefox's development tools noting "dog" as the accessible name of the element](https://github.com/testing-library/dom-testing-library/assets/3644075/6fad6d36-7285-4809-acdd-fdb3926513b5)

### Problem description:

`getByRole` does not seem to respect an element's accessible name when not explicitly defined via a method like `aria-label` or `aria-labelledby`.

### Suggested solution:

I would expect the `name` option to respect an element's accessible name regardless of how it was constructed.

Please let me know if I'm totally overlooking something!

**Comment by TrevorRice** [comment]
Apologies, this turned out to an issue with how we were using a Floating UI hook.

**Comment by okonet** [comment]
@TrevorRice I think I'm facing a similar issue. Can you point me to the problem you had please?
