### ISSUE TITLE
`getByRole("group")` can't match `address` tag  

### ISSUE THREAD

**Issue by Tarektouati** [testing-library/dom-testing-library#1277]
- `@testing-library/dom` version: 9.3.3
- Testing Framework and version: @testing-library/react@14.0.0
  
- DOM Environment: vitest: 0.34.6 with jsdom 22.1.0
  

### What you did:

I have React component that contains `address` tag :
 
```jsx
// component.jsx
const Component = () => {
   return (
    <address>
          <span>street Name</span>
          <span>postal code and city</span>
          <span>country</span>
     </address>
    )
}
```

All i wanted is to test that component in spec file : 

```jsx
// component.test.jsx
within(screen.getByRole("group")).getByText("street Name");
```
### What happened:
I was unable to match that `address` with role `group`

### Problem description:

Following [W3C](https://www.w3.org/TR/html-aria/#el-address ) `address` tag has role `group`, still I was unable to match it.

**Comment by timdeschryver** [comment]
To find the elements we make use of [aria-query](https://github.com/A11yance/aria-query).
The current version that we use (5.1.3) doesn't include the `address` field.

Upgrading aria-query to v5.3.0 solves this problem.
This is included in our [v10.0.0-alpha](https://www.npmjs.com/package/@testing-library/dom/v/10.0.0-alpha.2) release.
