### ISSUE TITLE
getByRole('caption') does not find caption element

### ISSUE THREAD

**Issue by Amy-B-Tradition** [testing-library/dom-testing-library#1289]
![image](https://github.com/testing-library/dom-testing-library/assets/141176039/5bd134c3-71c0-4646-b476-9d12d6dd4750)

16.20.2

### Relevant code or config:

```js
const BuyOrSellDepth = ({rows, type, securityId, currency, aggressCallback}: Props) => {
  const columns = depthColumnsByOrderType(type)
  const rootid = `${type}-market-${securityId}`
  const callback = aggressCallback || noop
  return (<table data-testid={rootid}>
    <caption >Current {orderTypeToDisplayName(type)}</caption>
    <tbody>{
      rows.map((row) => (<tr key={row.transactionId}
                             data-testid={`${rootid}-row-${row.transactionId}`}
        >
          {columns.map(col => {
            const key = `${rootid}-row-${row.transactionId}-${col}`
            let content: ReactNode = ''
            switch (col) {
              case 'aggress':
                if (row.canAggress) {
                  content = (
                    <span onClick={() => callback(row)}>
                      {orderTypeToAggressLabel(type)}
                    </span>
                  )
                }
                break
              case 'price':
                content = formatCurrency(row.price, currency)
                break
              case 'size':
                content = `${row.size}`
                break
              case 'spread':
                content = formatSpread(row.spread)
                break
            }
            
            return (<td
              key={key}
              data-testid={key}
              data-column={col}
            >
              {content}
            </td>)
          })}
        </tr>
      ))
    }</tbody>
  </table>)
}
```

### What you did:

test:
```
it('should have a caption', () => {
      const { getByRole } = render(<BuyOrSellDepth rows={[]} securityId={12345} type={type} />)
      expect(getByRole('caption')).toHaveTextContent(`Current ${displayName}s`)
    })
```

### What happened:
![image](https://github.com/testing-library/dom-testing-library/assets/141176039/448ac8bd-037a-4b6f-a5b1-3a0eb6626a23)

### Reproduction:

I think maybe this is it, but codesandbox gets harder and harder to use all the time and I was not able to find how to run the tests anymore
https://codesandbox.io/p/sandbox/react-testing-library-demo-forked-d8ztms?file=%2Fsrc%2F__tests__%2Fhello.js%3A10%2C1

### Problem description:

According to [the docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption#technical_summary), caption should have an implicit caption aria role. You are not allowed to add an aria role to it, and even if you do, RTL errors out and doesn't find it

### Suggested solution:

This should work

**Comment by MatanBobi** [comment]
Hi @Amy-B-Tradition, thanks for opening this one :)
Any chance you can test this against our alpha release? (can be installed using npm install @testing-library/dom@alpha). We've updated the underlying package (aria-query) there. We're still running some tests and I didn't get a chance to push it forwards to a release but having someone else testing that release will really help us.
Thanks!

**Comment by AmyBlankenship** [comment]
[This didn't work for me](https://github.com/AmyBlankenship/caption-repro), but I think it's probably because dom testing library is wrapped by react-testing-library and installing the alpha doesn't make it available. LMK if there's something you'd like me to try

**Comment by MatanBobi** [comment]
Yeah, you'll need to use something like npm's `overrides` or yarn's `resolutions` field to override a dependencies version :) Sorry, I forgot to mention that.

**Comment by AmyBlankenship** [comment]
[Seems to work](https://github.com/AmyBlankenship/caption-repro)

**Comment by MatanBobi** [comment]
Thanks for testing this @AmyBlankenship!
I'll do my best to find time to release this version soon though my plate is quite full at the moment.

**Comment by AmyBlankenship** [comment]
I appreciate your hard work!

**Comment by jlp-craigmorten** [comment]
[v10.0.0](https://github.com/testing-library/dom-testing-library/releases/tag/v10.0.0) is now live with this update, and looks like react-testing-library v15.0.0 will drop soon, see https://github.com/testing-library/react-testing-library/pull/1295 (and then overrides won't be needed).

**Comment by MatanBobi** [comment]
I'm resolving this one as DTL and RTL are already released :)
Thanks.
