### ISSUE TITLE
Test fails if not wrapped into waitFor

### ISSUE THREAD

**Issue by vincentaudebert** [testing-library/dom-testing-library#1301]
- `@testing-library/dom` version: 10.0.0
- Testing Framework and version: vitest - 1.5.0
- DOM Environment: jsdom
- Node v20

### Relevant code or config:

```js
const smsCheckbox = screen.getByRole('checkbox', {
      name: 'sms',
})
expect(smsCheckbox).toBeEnabled()
expect(smsCheckbox).not.toBeChecked()
expect(
      screen.getByText('some.text'),
).toBeInTheDocument()
await userEvent.click(smsCheckbox)
expect(smsCheckbox).toBeChecked()
```

### What you did:

Before bumping to testing-library/dom 10.0.0 this test was passing correctly.
Bumping to v10 is the only change.

### What happened:

Error: expect(element).toBeChecked()

Received element is not checked:
  <input
  aria-checked="false"
  class="cache-p9zju0 e1wstm611"
  id=":r4:"
  name="sms"
  type="checkbox"
  value=""
/>
 ❯ myfile.test.tsx:72:25
     70|     ).toBeInTheDocument()
     71|     await userEvent.click(smsCheckbox)
     72|     expect(smsCheckbox).toBeChecked()
       |                         ^
     73|
     74|     const smsInput = screen.getByLabelText('some.text')

### Problem description:

If I wrap this line into a `await waitFor()` it passes again. Then my tests fail into another file with the same idea, waitFor fixes it...

### Suggested solution:

No idea where it comes from, if any of you has an idea or same issue? Do I really need to apply `waitFor` everywhere? What could have changed with the v10 to cause this ?

Thanks in advance.

**Comment by MatanBobi** [comment]
Hi @vincentaudebert, thanks for opening this one.
This is not an expected behavior, I have a few guesses but without a proper reproduction, we won't be able to figure it out.
Any chance you can create a reproduction using https://testing-library/new-dtl?
This will help us understand and investigate this.

Here's an example that shows it's currently working:
https://stackblitz.com/edit/dtl-template-afwdcz?file=src%2Fmain.test.ts

**Comment by vincentaudebert** [comment]
Hi @MatanBobi

Thanks for your reply...
Sadly I can't manage to have a repro case working...

The best I managed to get is here: https://stackblitz.com/edit/dtl-template-5xjogm

We use our design system Ultraviolet and it seems it fails to work in stackblitz...

Could you communicate your guesses so I can check on my side inside our project and I'll post the solution here if I find something... ?

Thanks in advance.
