### ISSUE TITLE
can't run CodeSandbox tests (issue converting to devbox)

### ISSUE THREAD

**Issue by githorse** [testing-library/dom-testing-library#1303]
I tried to fork the suggested [CodeSandbox starter template](https://codesandbox.io/s/5z6x4r7n0p), but seems like I can't open a terminal any longer in CodeSandbox without first converting to a devbox. On forking and converting to a devbox, though, I get errors:

```
[plugin:vite:import-analysis] Failed to resolve import "react/jsx-dev-runtime" from "src/index.jsx". Does the file exist?
```

Maybe the starter sandbox needs updating for compatibility with devboxes (whatever that means)? Or, if I'm doing something wrong here, please let me know how I should be using it.

**Comment by githorse** [comment]
@MatanBobi this is the one copied from the issue template when I hit the `New Issue` -> `Bug Report` button(s).

**Comment by MatanBobi** [comment]
Thanks, I missed it when we've migrated to stackblitz. I've created a PR to fix that now :)
