### ISSUE TITLE
`alt` attribute can't be empty

### ISSUE THREAD

**Issue by Tasiobg** [testing-library/dom-testing-library#1313]
Since this update https://github.com/testing-library/dom-testing-library/pull/1241 the `alt` attribute for the `img` role can't be empty.
My understanding is that the `alt` attribute should be present but in some cases like decorative images it should be empty, [some info here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/1be7b709eececd83f1d5f67a60b2c97cfe9a561d/docs/rules/alt-text.md)

Is this an issue or an intended change?

Works
```TS
it(`testcase`, async () => {
    render(
      <div>
        <img src="url" alt="alt text" />
      </div>,
    );

    expect(screen.getByRole('img')).toBeInTheDocument();
  });
```

Fail
```TS
it(`testcase`, async () => {
    render(
      <div>
        <img src="url" alt="" />
      </div>,
    );

    expect(screen.getByRole('img')).toBeInTheDocument();
  });
```

**Comment by MatanBobi** [comment]
Hi @Tasiobg :)
An image with an empty `alt` attribute has a role of `none` or `presentation` (based on the [ARIA spec](https://www.w3.org/TR/html-aria/)):
<img width="842" alt="image" src="https://github.com/testing-library/dom-testing-library/assets/12711091/d494cd72-c48b-4e29-b8a8-6f9c8a8a1853">

So this works as expected.
Thanks for the report.
