### ISSUE TITLE
Node.js 14: Unsuported operator in 9.x

### ISSUE THREAD

**Issue by marcoslor** [testing-library/dom-testing-library#1326]
- `@testing-library/dom` version: 9.3
- node version: 14.x

I believe there is a single operator in the sourcecode that made 9.x drop support for node 14.x early. It is a [&&=](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND_assignment) operator, which was added in Node 15.

It was commited in the 9.2 release: https://github.com/testing-library/dom-testing-library/commit/eadf7485430968df8d1e1293535d78cdbeea20a5

Since I could not find any warnings of dropped Node 14 support in 9.2 (seem to have happened [here](https://github.com/testing-library/dom-testing-library/pull/1262) before 10.x), I think this may have been a mistake, and may be worth a patch.

In which version was support for 14.x oficially dropped?

Thanks!

**Comment by eps1lon** [comment]
We don't backport changes unless security related.
