### ISSUE TITLE
error @testing-library/dom@10.4.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "14.17.2"

### ISSUE THREAD

**Issue by Shubham8507** [testing-library/dom-testing-library#1335]
error @testing-library/dom@10.4.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "14.17.2"

**Comment by Shubham8507** [comment]
but it's related to the dom or my node version 14.17.2 if i upgrade the node version typescript is not working

**Comment by MatanBobi** [comment]
As the error message says, DTL doesn't support `node` version lower than 18 as they aren't actively maintained anymore.
Please upgrade to node 18 or higher to use this version.

**Comment by Shubham8507** [comment]
But many dependencies giving error
