### ISSUE TITLE
Remove undocumented queries

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/dom-testing-library#223]
Like:

- BySelectText
- ByValue

Those two are now handled via `ByDisplayValue` :+1:

This will be a breaking change. And I'm working on it today hopefully.

**Comment by huchenme** [comment]
May I know where can I find documentation for all methods listed here? https://github.com/kentcdodds/dom-testing-library/blob/master/src/queries.js

**Comment by kentcdodds** [comment]
Here you go: https://testing-library.com/docs/api-queries
