### ISSUE TITLE
npm install throwing error

### ISSUE THREAD

**Issue by ssmukesh** [testing-library/dom-testing-library#248]
- `dom-testing-library` version: 3.19.3
- `react` version: 
- `node` version: 11.14.0
- `npm` (or `yarn`) version: 6.7.0

### Relevant code or config:

```js
var your => (code) => here;
```

### What you did:

npm i dom-testing-library

### What happened:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sheerun%2fmutationobserver-shim - User not found
npm ERR! 404
npm ERR! 404  '@sheerun/mutationobserver-shim@^0.3.2' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404 It was specified as a dependency of 'dom-testing-library'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

### Reproduction:

npm i dom-testing-library

### Problem description: 

dependency of 'dom-testing-library' not available

**Comment by alexkrolick** [comment]
https://registry.npmjs.org/@sheerun/mutationobserver-shim exists - are you using a proxy or something?

**Comment by kentcdodds** [comment]
Cannot reproduce.

Good luck @ssmukesh!

**Comment by DaveStein** [comment]
FWIW, I am seeing the same issue when I do `npm install react-testing-library --save-dev`

**Comment by DaveStein** [comment]
https://registry.npmjs.org/@sheerun/mutationobserver-shim does show version `0.3.2` and that's what my lib is failing with

**Comment by DaveStein** [comment]
Doing `npm login` solved this for me. @ssmukesh try that.

**Comment by ssmukesh** [comment]
It was a cache issue. npm clear cache helped me to solve this issue... Sorry for my delayed response.
