### ISSUE TITLE
Could fireEvent return the event created somehow?

### ISSUE THREAD

**Issue by dbismut** [testing-library/dom-testing-library#257]
### Access the event created by fireEvent

I would like to get access the event created by `fireEvent`. I rely on `event.timeStamp` to do calculations in my component and testing without access to the created event is complex.

### Suggested implementation:

```js
const { canceled, event } = fireEvent[key](node, { ...eventProps })
```

`canceled` would be the result of `element.dispatchEvent` (ie the current return value of `fireEvent`) and `event` would be the event created. 

### Describe alternatives you've considered:

- Base my calculations on `Date.now()` in my component
- Use `timeStamp = Date.now() + 1` right before `fireEvent` (for some reason they equal the `timeStamp` created by `fireEvent`
- [current solution]: create the event manually and fire it with `fireEvent(element, event)`

**Comment by kentcdodds** [comment]
What if instead of that we exposed an easy way to create the event you pass?

```javascript
import {createEvent} from 'dom-testing-library'

const myEvent = createEvent.click()
fireEvent(node, myEvent)
```

**Comment by dbismut** [comment]
Indeed! Way more elegant!

**Comment by kentcdodds** [comment]
Would you be willing to [make a pull request](http://makeapullrequest.com) to do that?

**Comment by dbismut** [comment]
Sure, if I have time, tomorrow!

**Comment by kentcdodds** [comment]
This is done :)
