### ISSUE TITLE
    Unable to find the "window" object for the given node. fireEvent currently supports firing events on DOM nodes, document, and window. Please file an issue with the code

### ISSUE THREAD

**Issue by nazanine** [testing-library/dom-testing-library#270]
- `dom-testing-library` version:
- `node` version:
- `npm` (or `yarn`) version:

Relevant code or config

```javascript
```

What you did:

What happened:

Reproduction repository: https://github.com/alexkrolick/dom-testing-library-template

Problem description:

Suggested solution:

**Comment by clodal** [comment]
Faced a similar issue. Ensure that you are querying the element correctly. For example if you are using `getAllByText`, it returns an array instead of the element object itself. In which case, do:

```
// Case 1: Fail
const button = getAllByText(container, 'Send')
fireEvent.click(button) // Unable to find the "window" object for the given node. fireEvent currently supports firing events on DOM nodes, document, and window....

// Case 2a: Success
const button = getAllByText(container, 'Send')
fireEvent.click(button[0]) // OK

// Case 2b: Success
// or simply just change the query instead
const button = getByText(container, 'Send')
fireEvent.click(button) // OK
```

**Comment by GTOsss** [comment]
In my case: 
```    
const buttonSubmit = screen.findByText('submit');
fireEvent.click(buttonSubmit); // fail

const buttonSubmit = screen.getByText('submit');
fireEvent.click(buttonSubmit); // OK
```

**Comment by kentcdodds** [comment]
@GTOsss, `findByText` returns a promise which should be `await`-ed.

**Comment by SSIrigi** [comment]
it.only('should move the expressions from expression texts to procedure steps', () => {
      console.log("dnd the expressions");

      // const dataTransfer = new DataTransfer();
      const dnd = screen.queryAllByText('exp')
    
      fireEvent.click(dnd)
      fireEvent.mouseMove(dnd, { deltaX: 100, deltaY: 100, ...Option });
      fireEvent.mouseUp(dnd);
      expect(screen.getByTestId('exp')).should('have.length', 9);
    });

**Comment by SSIrigi** [comment]
I am getting below error and could you please help me.

Unable to find the "window" object for the given node. fireEvent currently supports firing events on DOM nodes, document, and window. Please file an issue with the code that's causing you to see this error: https://github.com/testing-library/dom-testing-library/issues/new

**Comment by MatanBobi** [comment]
@SSIrigi, `dnd` is an array since you're using `queryAllByText` and `fireEvent` methods receive a DOM node.
If there's only one element that matches `queryAllByText('exp')`, then use `getByText`, if there are multiple elements, you'll need to run over the array and dispatch the events one by one.
