### ISSUE TITLE
Finding an SVG using aria-labelledby has no results

### ISSUE THREAD

**Issue by paularmstrong** [testing-library/dom-testing-library#271]
- `dom-testing-library` version: latest
- `react` version: latest
- `node` version: n/a
- `npm` (or `yarn`) version: n/a

### Relevant code or config:

```js
const MyComponent = () => (
  <div>
    <svg aria-labelledby="tacos" />
    <div id="tacos">this is tacos</div>
  </div>
);
```

### What you did:

```js
  const { getByLabelText } = render(<MyComponent />);
  expect(getByLabelText("tacos")).not.toBeUndefined();
```

### What happened:

No result for element labelled by "tacos"

### Reproduction:

See codesandbox: https://codesandbox.io/s/reacttestinglibrary-demo-ollox?fontsize=14

Test output:
```
Unable to find a label with the text of: tacos

<body>
  <div>
    <div>
      <svg
        aria-labelledby="tacos"
      />
      <div
        id="tacos"
      >
        tacos
      </div>
    </div>
  </div>
</body>

Error: Unable to find a label with the text of: tacos

<body>
  <div>
    <div>
      <svg
        aria-labelledby="tacos"
      />
      <div
        id="tacos"
      >
        tacos
      </div>
    </div>
  </div>
</body>
```

### Problem description:

There's no way to find an SVG element that is using aria-labelledby, though the [labelText](https://testing-library.com/docs/dom-testing-library/api-queries#bylabeltext) documentation indicates that this should work.

**Comment by kentcdodds** [comment]
I'm guessing this is because the label is in a `div`. I'm not sure whether that's allowed in the spec. Is there a reason you're not using a `label` instead of a `div`?

**Comment by paularmstrong** [comment]
Per the examples in the docs, an H3 element should also be sufficient, right? That does not work.

**Comment by paularmstrong** [comment]
In my project using react-native-web. Pretty much everything is a `div`.

**Comment by kentcdodds** [comment]
Gotcha. Could you please verify whether the spec allows for this (and therefore assistive technologies work with this). If so, then we can consider this a bug and fix it.

**Comment by paularmstrong** [comment]
Can you link to the spec? Seems to be a lot of versions and lengthy reading needed to be done to figure that out.

**Comment by kentcdodds** [comment]
Sorry, I don't know where to find the most up-to-date version. That's what I was asking you to do 😅 I don't have time to look into it at the moment.

**Comment by bcarroll22** [comment]
Based on [the examples here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute) it looks like that’s a valid use of labeled by. 

So, my guess is if you can run document.querySelectorAll in your browser and it selects that element correctly, then this is probably a jsdom issue.

**Comment by kentcdodds** [comment]
We're currently only selecting labels, so we'll have to expand it to everything.

**Comment by bcarroll22** [comment]
I’m busy this weekend so can’t help, but if someone wants to contribute this one I think [this line](https://github.com/testing-library/dom-testing-library/blob/master/src/queries/label-text.js#L66) is the culprit?

**Comment by paularmstrong** [comment]
Thanks for the direction @bcarroll22! I opened #274
