### ISSUE TITLE
GitHub Project URL links to deprecated npm module

### ISSUE THREAD

**Issue by dtinth** [testing-library/dom-testing-library#278]
Right now GitHub project URL points to http://npm.im/dom-testing-library which brings up a deprecated message.

![image](https://user-images.githubusercontent.com/193136/58860927-76290080-86d7-11e9-8efb-cfeef183c034.png)

Suggested solutions:

- Point to the docs

  https://testing-library.com/docs/dom-testing-library/intro

- Point to the new npm module

  http://npm.im/@testing-library/dom

**Comment by kentcdodds** [comment]
Fixed. Thanks!
