### ISSUE TITLE
onKeyDown fireEvent does not work for native buttons

### ISSUE THREAD

**Issue by kendallgassner** [testing-library/dom-testing-library#279]
- `dom-testing-library` version: 8.0.1
- `node` version: 10.15.1
- `npm` (or `yarn`) version: 6.4.1

What you did:
I am creating a component that contains a native button:  `<buttons onClick={() => {}}>`. 

I would like to create this test 

```  
test('test button', () => {
    const click = jest.fn();
    const { container } = render(
      <Component onClick={click}/>
    );
    fireEvent.keyDown(container.firstChild as HTMLButtonElement, { key: 'Enter', code: 13 });
    expect(click).toHaveBeenCalled();
  });
```
 
What happened:

 "Expected mock function to have been called, but it was not called."

Reproduction repository:
https://github.com/alexkrolick/dom-testing-library-template

Problem description:
Without explicitly adding an onKeyDown event in the native button props. Native Buttons automatically set the onKeyDown enter event to be the passed in onClick function. FireEvent will not allow me to test this. 

Suggested solution:

**Comment by kentcdodds** [comment]
Hi @kendallgassner,

I think you mean to use `fireEvent.click` as that's the event you're listening for.

If you'd rather, you might be interested in trying [user-event](https://github.com/testing-library/user-event) which is a tad more user-like.

I hope that helps. Good luck!

**Comment by kentcdodds** [comment]
Also, welcome to GitHub! :D

**Comment by kendallgassner** [comment]
Thank you @kentcdodds. I actually test with fireEvent.click but I also wanted to also add the KeyDown check to test for accessibility. --In case the code ever is changed to not use a native button anymore.

**Comment by kentcdodds** [comment]
Ah, interesting. In my experience that level of defensive testing doesn't often pay off very well (by that I mean that it's not worth the effort, and your time would be better spent making your app awesome).
