### ISSUE TITLE
Form By Submit text

### ISSUE THREAD

**Issue by julionav** [testing-library/dom-testing-library#284]
### Describe the feature you'd like:
It would be great if there could be a way to get a form by its submit button (it could be also by field).
Since there is no way to test a normal HTML form submission, testing its action URL is helpful in some cases.
The alternative to this is to use a `testid` but IMO getting the form by submit button goes more along with testing what the user can see.

**Comment by kentcdodds** [comment]
Hi @julienw,

Thanks for the suggestion, but this doesn't really work well for the library because there's no way for the end-user to know which button is the form's submit button. So I don't think we want to give you that power in the library.

Thanks anyway.

**Comment by rbrisita** [comment]
Even though the user doesn't know what will happen when clicked, the code does. I understand the separation of implementation versus use but in this sense the code can express that a button will submit by having either `type="submit"` in a form or have content text of "Submit".
