### ISSUE TITLE
testing-library/marko

### ISSUE THREAD

**Issue by DylanPiercey** [testing-library/dom-testing-library#290]
### Describe the feature you'd like:

I'd like to build and contribute a testing library wrapper for [MarkoJS](https://markojs.com).

I'm not sure if this a project that you would be interested in adding to the suite of testing libraries in an official way.

If so I have a couple questions:

1. For us it is currently going to make the most sense for this module to exist in our [Marko GitHub organization](https://github.com/marko-js). Is this something that would be an issue? We are happy to contribute documentation to the existing testing-library documentation repo.

2. Are there standards / file structure requirements that are needed to be met? For example I’d like to have this wrapper written in typescript, and potentially with some slightly modified jest-config. eg: Is using kcd-scripts required?

### Teachability, Documentation, Adoption, Migration Strategy:

This wrapper would work similarly to all other available wrappers, with the exception that there would be a distinction between server side rendered tests and client side rendered tests.

**Comment by kentcdodds** [comment]
Hi @DylanPiercey!

1. Not an issue at all. If you're doing the work, you make the decisions 💯
2. No standards necessary. It's 100% your project. We're happy to list it in the docs as others on the site, but we'll expect you to maintain that part of the documentation.

The one requirement that we have is that the API the library exposes encourages good testing practices. Following the guiding principle of "The more your tests resemble the way your software is used, the more confidence they can give you." So long as it upholds that methodology then it's a welcome addition :)
