### ISSUE TITLE
keydown should not take a target

### ISSUE THREAD

**Issue by eps1lon** [testing-library/dom-testing-library#292]
### Describe the feature you'd like:

Safer (less implementation details) way of dispatching keydown events.

### Suggested implementation:

> The event target of a key event is the currently focused element which is processing the keyboard activity. [...] If no suitable element is in focus, the event target will be the HTML body element if available, otherwise the root element.

-- https://www.w3.org/TR/uievents/#events-keyboard-event-order

I interpret this as `fireEvent.keydown(document.activeElement || document.body || document.documentElement)` is what would actually happen in a browser.

### Describe alternatives you've considered:

Manually find `fireEvent.keydown(someElement)` and replace with `fireEvent.keydown(document.activeElement || document.body || document.documentElement)`

### Teachability, Documentation, Adoption, Migration Strategy:

Add `fireEvent.userKeydown` and warn in the documentation about where keydown is actually dispatched. Replace `keydown` in a breaking change with `userKeydown` and either don't allow defining the target manually or add `unsafe_keydown` which takes a target argument.

**Comment by kentcdodds** [comment]
Thanks for the issue. I think this would make more sense as an addition to the user-event package. The fireEvent utility is intended to be a primitive for firing events on DOM nodes.

Anyone else have thoughts here? @Gpx?
