### ISSUE TITLE
getByRole and implicit roles

### ISSUE THREAD

**Issue by eps1lon** [testing-library/dom-testing-library#302]
### Describe the feature you'd like:

`getByRole(<button />, 'button')` should return the button

### Suggested implementation:

Go through W3C HTML 5 specification recommendation and look for default aria roles. For these default aria roles expand the selector e.g. `getByRole('button') => '[role="button"], button:not[role]'` 

### Describe alternatives you've considered:

Use custom queries 

### Teachability, Documentation, Adoption, Migration Strategy:

Make it clear that `getByRole(role)` is not merely an alias for `querySelector([role="${role}"])` but considers implicit roles.

It's potentially breaking if people expect in their tests that `getByRole('button')` doesn't match `button` elements.

Possible misconceptions:
- `<button />` and `<div role="button" />` are equivalent (though I would like to give this freedom to testers and make sure their other tests properly implement native button behavior)
- use `getByRole('textbox')` instead of `getByLabel`

**Comment by kentcdodds** [comment]
Interesting. I wonder why that's not already supported by `aria-query`. I wonder whether this should be fixed in `aria-query`. Could someone do some investigation as to why it's not?

**Comment by eps1lon** [comment]
Didn't look how it's implemented and just assumed it uses attribute selectors. Will take a look at aria-query.

**Comment by eps1lon** [comment]
This totally works `expect(render(<button>hello</button>).getByRole('button')).toBeInTheDocument()`.  I only read [the docs about getByRole](https://testing-library.com/docs/dom-testing-library/api-queries#byrole) without testing 🙅‍♂ 

I don't think we need to add tests for it (since that's the job of aria-query) but I do think we should include in the docs that `getByRole` includes implicit roles.

**Comment by kentcdodds** [comment]
Yes, I believe that the docs are in the process of getting updated.
