### ISSUE TITLE
ClipboardEvent is not defined

### ISSUE THREAD

**Issue by lulidd01** [testing-library/dom-testing-library#310]
when i use ClipboardEvent, it not defined.
```
const pasteFn = new ClipboardEvent('paste', {
      dataType: 'text/plain',
      data: 'paste text'
    })
```
but i can use other events, like: MouseEvent, KeybordEvent

**Comment by afontcu** [comment]
Hi @lulidd01! `ClipboardEvent` appears to be defined [here](https://github.com/testing-library/dom-testing-library/blob/master/src/events.js#L4). Can you please provide a reproduction link? I'm not quite sure what's your use case given the snippet you pasted above.

Thanks!

**Comment by Davetherave2010** [comment]
To build on @afontcu's answer you could use `createEvent.paste`

```js
test('Pasting also fires onPaste event which returns clipboard data', () => {
  const pasted = jest.fn(() => null);
  const changed = jest.fn(() => null);

  render(
    <PasteComponent paste={pasted} changeEvent={changed} data-testid='paste-input' />);

  const PhoneNumberElement = screen.queryByTestId('paste-input');

  const paste = createEvent.paste(PhoneNumberElement, {
    clipboardData: {
      getData: () => '123456',
    },
  });

  fireEvent(PhoneNumberElement, paste);

  expect(pasted).toHaveBeenCalled();
  expect(pasted).toHaveBeenCalledWith('123456');
});
```

This might help - https://medium.davidendersby.me/2-ways-to-trigger-the-onpaste-event-with-testing-library-1502c5fdb9e

**Comment by osheral** [comment]
fireEvent.paste(screen.getByTestId('add-images-modal-body'), {
      clipboardData: {
        items: [
          {
            kind: 'file',
            getAsFile: () => new File(['(⌐□_□)'], imageName, { type: 'image/png' }),
          },
        ],
      },
    });
