### ISSUE TITLE
logRoles doesn't log

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/dom-testing-library#311]
This is my fault for not reviewing properly, but the new `logRoles` function simply generates a formatted string and returns it. It does not call `console.log` as the name implies.

## Suggested solution

Rename the current `logRoles` function to `prettyRoles` (analogous to `prettyDOM`) and make a new function called `logRoles` which actually uses console.log to log out the result of `prettyRoles`.

Thoughts?

cc @michaellasky

**Comment by afontcu** [comment]
Wow, this is so funny. I was just trying to get my head around `logRoles` - right now! I couldn't get any output, so I assumed I was doing something wrong 😅 

Question: Should the _new_ `logRoles` live in DTL, though? AFAIK, there's no `logDOM` function here, but in RTL/VTL (where `debug()` is just logging `prettyDOM`).

What are your thoughts?

**Comment by kentcdodds** [comment]
Yes, I had a similar thought. I'd actually be more ok with adding a `logDOM` than removing the `logRoles`.

And I can see value in wrappers adding a `debugRoles` method to their return value as well.

**Comment by michaellasky** [comment]
I actually was going to ask if we wanted to actually call console.log in the function or just return the string, but didn't when nobody had a problem with the string, haha.  

Probably should have been clearer with my intentions there, but thought you might want to keep it general so you could log the output to places other than the console.  

Anyway, I'm fine with submitting a PR to fix this in the next 24 hours, at least as a stopgap until other changes are proposed/made?

**Comment by kentcdodds** [comment]
Yes, that sounds good. For now let's just make `logRoles` actually log the roles string rather than return it.

We can discuss the addition of `logDOM` and `prettyRoles` later. I'd love to hear what others have to say about that.

**Comment by michaellasky** [comment]
Added a quick PR that makes logRoles actually log :).  

Note: In this PR it still returns the string, as before.  I can change this so it only logs, but i figured we want to keep the api that same for the moment?  

It's unlikely anyone is using logRoles extensively, but if it stops returning the string it could break suddenly for someone.

**Comment by michaellasky** [comment]
I also have some code started for the other changed discussed.  

Assuming it ends up something like (abbreviated):
   
       logroles = container => console.log(prettyRoles(container)); 

Any idea how to test logRoles if it's just calling console.log?  Can we mock the console easily?  I don't think i've ever tested for a call to console.log before.

**Comment by kentcdodds** [comment]
Looks like the PR hasn't been opened yet. Did you intend to do so?

I think it's safe to consider this a bug and do a silent breakage to fix it.

**Comment by michaellasky** [comment]
PR is open, I'm just slow, ahah.   I'll also update it in a sec without the string returning

**Comment by afontcu** [comment]
AFAICT this issue can be closed thanks to #312. Am I right?

**Comment by kentcdodds** [comment]
yup 👍
