### ISSUE TITLE
Get/Log Roles helpers doesn't return anchors when querying link roles

### ISSUE THREAD

**Issue by afontcu** [testing-library/dom-testing-library#313]
- `dom-testing-library` version: `5.5.1`
- `node` version: `10.16.0`
- `npm` (or `yarn`) version: `6.9.0`

### What you did:

Tried to get an anchor element (`<a href="http://whatever.com">`).

Since it wasn't working (even though [the implicit ARIA role exists](https://www.w3.org/TR/html-aria/#document-conformance-requirements-for-use-of-aria-attributes-in-html) in anchor elements as long as they have a `href` attribute) I turned to DTL and added `<a href="http://link.com" data-testid="a-link">link</a>` to [role-helpers test](https://github.com/testing-library/dom-testing-library/blob/master/src/__tests__/role-helpers.js#L8).

### What happened:

Test continued to pass.

### What did you expect:

Test to fail, since `logRoles` would've logged a `link` implicit ARIA role with the anchor element within

### Reproduction:

1. Add `<a href="http://link.com" data-testid="a-link">link</a>` to [role-helpers test](https://github.com/testing-library/dom-testing-library/blob/master/src/__tests__/role-helpers.js#L8).
2. Run tests.

### Suggested solution:

I've been able to track it down to `makeElementSelector()`, where we extract `value` and use it to create the node selector expression:

```js
.map(({name: attributeName, value}) => `[${attributeName}=${value}]`)
```

([source](https://github.com/testing-library/dom-testing-library/blob/master/src/role-helpers.js#L19))

the resulting output for an anchor element is `a[href=undefined]`. Thus, if I change my link to `<a href="undefined">`, the elements is found and test starts to fail - as expected :)

However, not sure what the fix is. Why is the "=value" part needed? Should we just check for `value` to be truthy, and otherwise skip it? It'd generate a `a[href]` selector, which would come in handy to find links. Another option is to get the "http://whatever.com" part somehow, and add it to the element selector query.

What are your thoughts? I'm happy to tackle this if we reach an agreement 👍 I'm gonna open a draft PR with the updated test cases, so we can work from there.

Thanks!

**Comment by kentcdodds** [comment]
Hmm... Yeah, that's interesting. I wonder whether there's a better way to get those elements 🤔

**Comment by afontcu** [comment]
If we want to pull out `anchor` elements with a `link` role, the proper query is actually `a[href]` AFAICT. Thus, the proposed solution of skipping the `value` part if it's falsy makes sense.

However, I guess other role queries are failing right now, too. I'm gonna look into it and report back if I run into any other failing query.

by the way, couldn't create the PR since tests were failing. Should I just remove it from the branch for the time being, and add it back again afterwards?

Thanks! 🙌

**Comment by kentcdodds** [comment]
> couldn't create the draft PR because tests were failing

I just noticed that. Kinda weird thing going on. But I'll have it fixed in a second. Thanks!

**Comment by kentcdodds** [comment]
Ok, the repo is now in a good state 👍
