### ISSUE TITLE
Error parsing file (helpers.js) in Cypress.

### ISSUE THREAD

**Issue by DylanVann** [testing-library/dom-testing-library#315]
![image](https://user-images.githubusercontent.com/1537615/61133036-a019d380-a48a-11e9-84da-58097ff2e861.png)

### Reproduction:

- Clone https://github.com/cypress-io/cypress-example-kitchensink
- `yarn add @testing-library/cypress`
- `yarn cypress open`
- Try to run a test, it will give that error.

### Problem description:

It seems Cypress doesn't like the syntax output by babel for that `helpers.js` file.

### Suggested solution:

Code is on the left, compiled on the right. I don't totally understand what's causing this issue, but if we name the function `setImmediateFn` instead the error does not occur.

![image](https://user-images.githubusercontent.com/1537615/61133681-ea4f8480-a48b-11e9-90d9-68f495b0f730.png)

**Comment by kentcdodds** [comment]
Let us know if your or doesn't fix this when it's released. Thanks!
