### ISSUE TITLE
getClosestBy*

### ISSUE THREAD

**Issue by mlrawlings** [testing-library/dom-testing-library#327]
### Describe the feature you'd like:

I'd like to introduce `getClosestBy*` as a way to find an element that is the known element or some ancestor of it that matches one of they [`testing-library` queries](https://testing-library.com/docs/dom-testing-library/api-queries#queries).

For example, given the following markup, I'd like to be able to get the button by its text.

```html
<button>
  <span>A</span>
</button>
<button>
  <span>B</span>
</button>
```

```js
getClosestByRole(getByText("B"), "button")
```
### Suggested implementation:

Recursively walk up from the node and find the first node that matches.

### Describe alternatives you've considered:

Use native `closest`:

```js
getByText("B").closest("button");
```

Walk the tree myself:

```js
getByText("B").parentNode
```

Get by a known index:

```js
getAllByRole('button')[1]
```

Abuse a TextMatcher:

```js
getByRole((role, element) => role === 'button' && element.textContent === "B")
```

### Teachability, Documentation, Adoption, Migration Strategy:

`getClosestBy*` would be to`getBy*` as [`closest`](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest) is to [`querySelector`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector).

**Comment by alexkrolick** [comment]
There's been some discussion of this idea and its trade-offs in a few threads already:  https://github.com/testing-library/dom-testing-library/issues/204#issuecomment-474590983

**Comment by adamduncan** [comment]
Understand that specifying tags/attributes in queries is [testing implementation details](https://kentcdodds.com/blog/testing-implementation-details), but there are some cases where this might be the most sane way inferring behaviour? As you say, testing attributes on parent nodes.

E.g. Ensuring a button with nested span is `disabled`:

```
<button disabled><span>Do thing</span></button>

// findByText(/Do thing/).should('have.attr', 'disabled') fails
```

@kentcdodds had mentioned a hypothetical solution in #204, suggesting a `closestInteractiveElement` option, but didn't sound too keen on it. Would there be something along these lines that would be workable?

**Comment by eps1lon** [comment]
> E.g. Ensuring a button with nested span is disabled:

This particular instance will be covered by https://github.com/testing-library/dom-testing-library/pull/408. When this lands you'll be able to query the button with `getByRole('button', { name: 'Do thing' })`

**Comment by kentcdodds** [comment]
Yup, closing this in favor of #408. Thanks!
