### ISSUE TITLE
Don't log "here are the available roles" if there are no roles available.

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/dom-testing-library#328]
Pretty much just need to do a bit of logic for this:

https://github.com/testing-library/dom-testing-library/blob/d719edd658ce6ad616f2632f378b3a7f4bf03897/src/queries/role.js#L33-L38

**Comment by SavePointSam** [comment]
I would like to do this!

**Comment by SavePointSam** [comment]
I believe this can be closed now! 🎉

**Comment by kentcdodds** [comment]
Thanks!
