### ISSUE TITLE
should waitForElementToBeRemoved take an element as the argument?

### ISSUE THREAD

**Issue by alexkrolick** [testing-library/dom-testing-library#329]
Currently `waitForElementToBeRemoved` takes a callback function that should return an element. Couldn't it also accept a plain element?

**Comment by kentcdodds** [comment]
I suppose it could 👍

**Comment by kentcdodds** [comment]
After working on this for a while, this is harder than I originally thought. How would we know whether the element has been removed? Is it: "This element has been removed if it no longer has a `parentNode`?" if so, then what if the _parent_ is removed? In that case, is it "if it's not in the `document.body`?" in that case, do we require that people using this utility insert their DOM nodes into the body? That's required for React, but not for all frameworks.

I don't think this is really a generically solvable problem, so I think we'll have to close this one :-(
