### ISSUE TITLE
Can't find wrapped textarea with getByLabelText

### ISSUE THREAD

**Issue by amannn** [testing-library/dom-testing-library#343]
- `DOM Testing Library` version: 6.0.0
- `node` version: v12.3.1
- `npm` (or `yarn`) version: yarn@1.17.3

### Relevant code or config:

```js
const {getByLabelText} = render(
  <label>
    Label
    <textarea defaultValue="value" />
  </label>
);
getByLabelText('Label');
```

### What you did:

Run the test.

### What happened:

```
Unable to find a label with the text of: Label

<body>
  <div>
    <label>
      Label
      <textarea>
        value
      </textarea>
    </label>
  </div>
</body>

  113 |     </label>
  114 |   );
> 115 |   getByLabelText('Label');
      |   ^
  116 | });
  117 | 

  at getElementError (node_modules/@testing-library/dom/dist/query-helpers.js:22:10)
  at getAllByLabelText (node_modules/@testing-library/dom/dist/queries/label-text.js:104:43)
  at node_modules/@testing-library/dom/dist/query-helpers.js:59:17
  at Object.getByLabelText (src/components/Test/__tests__/Test-test.js:115:3)
```

Interestingly it works once you remove `defaultValue="value"`

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-olewk

### Problem description:

According to [the docs](https://testing-library.com/docs/dom-testing-library/api-queries#bylabeltext) this should work:
```html
<label>Username <input /></label>
```

### Suggested solution:

I guess the bug is somewhere here: https://github.com/testing-library/dom-testing-library/blob/master/src/queries/label-text.js

**Comment by amannn** [comment]
I dug a bit in. It seems like you're using the `textContent` here to assert if the label matches:

https://github.com/testing-library/dom-testing-library/blob/master/src/queries/label-text.js#L20

However a textarea value is also part of the `textContent`. 

E.g.:
```
<label>Label<textarea>Value</textarea></label>
```
has a `textContent` of:
```
LabelValue
```

When you try to match for the label later, it fails because "value" is in the string as well.

I guess we need to remove textarea content from the string somewhere?

**Comment by amannn** [comment]
Ok, I've got a PR up 🙂

**Comment by pawbor** [comment]
Hi guys!

First of all, I appreciate your work. This lib is great! 

I've been scanning the code and found out the change introduced by @amannn. It fixes the initial bug but introduces another one:
```
it('passes', () => {
    const { getByLabelText } = render(<label>test 1<textarea defaultValue="test"/></label>);
    const textarea = getByLabelText('1test');

    expect(textarea).toBeTruthy();
  });

  it('fails', () => {
    const { getByLabelText } = render(<label>test 1<textarea defaultValue="test"/></label>);
    const textarea = getByLabelText('test 1');

    expect(textarea).toBeTruthy();
  });
```
I guess it's not common situation, but I thought you may wanna know about it. 

Good luck and thanks for your work!

**Comment by kentcdodds** [comment]
Thanks for bringing that up @pawbor. If that ever becomes a legitimate problem for someone in the real world then maybe we can investigate a better solution.
