### ISSUE TITLE
[TS] Default install for React is nonfunctional due to incorrect typing

### ISSUE THREAD

**Issue by Jhawins** [testing-library/dom-testing-library#349]
- `DOM Testing Library` version: 6.2.0
- `node` version: 8.16.0
- `npm` (or `yarn`) version: 6.10.3

### Relevant code or config:

```js
it('hello world', async () => {
  const { getByText } = render(
    <div>
      <h1>hello world</h1>
    </div>
  );
  expect(getByText('hello world'));
});
```

### What you did:
Installed bare minimum for testing-library and ran a test with ts-jest

### What happened:
```
Argument of type '"hello world"' is not assignable to parameter of type 'SelectorMatcherOptions'.
```
The type for `getTextBy` is from `@types/testing-library__dom`
It should be from `@types/testing-library__react` in this case.

### Reproduction:
https://github.com/Jhawins/react-testing-bug-mvce

1. Clone the repo
2. Run `npm i`
3. Run `npm run test` or `jest`

### Suggested solution:
I'm new to type script, it seems like this is probably a simple fix in the way the types are used. In a sentence the problem is that `@types/testing-library__dom` is overriding `@types/testing-library__react`.

If you delete `@types/testing-library__dom` from node_modules suddenly the types are correct and the code compiles. They are both dependencies tho so that's not a real fix.

I'd gladly fix the issue if I could get some direction / confirmation

**Comment by afontcu** [comment]
Hi! 👋 

Haven't used TS that much, but I noticed in your repo that you shouldn't be installing `@testing-library/dom` manually (it is a dependency from React Testing Library). Is it possible that RTL definitions are being burdened because of that?

**Comment by Jhawins** [comment]
> Hi! 👋
> 
> Haven't used TS that much, but I noticed in your repo that you shouldn't be installing `@testing-library/dom` manually (it is a dependency from React Testing Library). Is it possible that RTL definitions are being burdened because of that?

That is a good point. I tried removing that and found the same result unfortunately

**Comment by Jhawins** [comment]
I'm actually realizing now that it's not an issue of conflicting types. Removing the DOM typing just gives implicit Any to all the getBy queries... I wonder if this ever worked properly with `testing-library__react`, it seems the typings were hosted from old DefinitelyTyped files.

**Comment by kentcdodds** [comment]
Seems to be working ok for others. I'm not sure what the problem is, but you'll probably get more help [on spectrum](https://spectrum.chat/testing-library).

Sorry!
