### ISSUE TITLE
Firing a click event on label nested element is not propagating as expected

### ISSUE THREAD

**Issue by herecydev** [testing-library/dom-testing-library#351]
Firing a click event on label nested element is not propagating as expected

- `React Testing Library` version: 9.1.4
- `node` version: 10.16.0
- `yarn` version: 1.17.3

### Relevant code or config:

```js
let calls = 0;
const { findByText } = render(<div>
<input type="radio" id="foo" onClick={() => calls++} />
<label htmlFor="foo">
  <strong>Click me</strong>
<label>
</div>
);

// does not work
const label = await findByText("Click me");

// works
//const label = await findByLabelText("Click me");

fireEvent.click(label)
expect(calls).toBe(1);
```

### What you did:

`findByText` returns the strong element and `findByLabelText` returns the label input element but both would fire the onClick method as it does in a browser

### What happened:

firing a click event on `findByText` did not subsequently call the onClick method. I have tried to recreate on repl.it for JSDOM: https://repl.it/repls/WingedLastingFreesoftware

This looks like it's working correctly, but I have also never used JSDOM directly before so not sure if my implementation is totally correct.

**Comment by kentcdodds** [comment]
Hi @herecydev,

I believe this is a JSDOM issue which has been solved in the latest version of JSDOM. I'd recommend you upgrade it for your setup (if you're using jest, then [try this](https://www.npmjs.com/package/jest-environment-jsdom-sixteen)).

Good luck!
