### ISSUE TITLE
Ability to suppress logging full DOM

### ISSUE THREAD

**Issue by benmonro** [testing-library/dom-testing-library#360]
### Describe the feature you'd like:

Looking for a way to disable the full DOM logging.  In RTL it makes sense to see the rendered output when a query fails, as it's usually pretty small.  But when using Testcafe testing library, its dumping the entire DOM and pretty much takes over my entire terminal.  Would be nice to have a flag you can set in the `configure()` function that allows you to suppress the full DOM logging.
### Suggested implementation:
`configure({showLogOnFail:false})` (default's to current behavior, true) 

### Describe alternatives you've considered:
I noticed an environment variable that lets you control the size, but testcafe runs the tests in-browser so i don't think that will work.

**Comment by eps1lon** [comment]
I would like to use the opportunity and make the verbosity a bit more granular. Most of the time it isn't necessary to log the full dom of the available roles. A shallow log for roles + their top level element with attributes is usually enough.

**Comment by herecydev** [comment]
On a similar note, it would be nice to trim out react's internal comments like `<!-- /react-text --><!-- react-text: 28 -->`

They are important for react to track it's nodes but not important for seeing what's rendered (at least in most cases). This can be easily achieved using [ReactDOMserver](https://reactjs.org/docs/react-dom-server.html#rendertostaticmarkup), but that won't technically be the window.document, so perhaps removing comments from prettyDOM might be better?

**Comment by kentcdodds** [comment]
I'm fine with changing the behavior here a little bit. Anyone who feels strongly about this can feel free to open a PR with some suggested APIs for this and we can make it happen (hopefully without breaking changes).

@herecydev, I'm not sure we can reliably remove those commends without causing more confusion, but maybe we could expose an API that [inverts control](https://kentcdodds.com/blog/inversion-of-control) to you so you can do that yourself.

**Comment by kentcdodds** [comment]
Whoops, didn't mean to close this.

**Comment by Volox** [comment]
I was looking for the same feature and stumbled upon the following in the doc:
https://testing-library.com/docs/dom-testing-library/api-helpers#debugging

Basically by setting the env `DEBUG_PRINT_LIMIT` to something it will cap the output.

Not sure if it helps :)

Also I agree with @eps1lon a finer grained control can be a lot useful...

**Comment by MatanBobi** [comment]
Hi @g-wozniak,
you can go ahead and use `getElementError` which is a function that runs everytime a `getBy*` query fails:
https://github.com/testing-library/dom-testing-library/blob/main/src/config.ts#L33
