### ISSUE TITLE
Support fireEvent.change with valueAsNumber attribute

### ISSUE THREAD

**Issue by dlbnco** [testing-library/dom-testing-library#366]
### Describe the feature you'd like:

I was testing a range input which used an `onChange` prop that took the element's [`valueAsNumber` attribute](https://www.w3.org/TR/html50/forms.html#dom-input-valueasnumber). The implementation was done this way to avoid having to transform the string into a number:

```jsx
<input
  type="range"
  onChange={e => seekTo(e.target.valueAsNumber)}
  min={min}
  max={max}
  value={value}
  data-test="slider-input"
/>
```

So the tests were written taking that into account:

```js
test('should trigger seek function when clicking the slider', () => {
  const { container } = render()
  const slider = container.querySelector('[data-test="slider-input"]')
  const value = 12345
  fireEvent.change(slider, {
    target: {
      valueAsNumber: value,
    },
  })
  expect(seekTo).toHaveBeenCalledWith(value)
})
```

The tests were failing with:

```
Expected mock function to have been called with:
    [12345]
But it was not called.
```

So after messing around a little bit, I tried firing the event with `value` instead of `valueAsNumber` and it worked.

```js
fireEvent.change(slider, {
  target: {
    value,
  },
})
```

My implementation had to change to enable testing. My `onChange` function went from:

```jsx
onChange={e => seekTo(e.target.valueAsNumber)}
```
to
```jsx
onChange={e => seekTo(Number(e.target.value))}
```

...which is fine, but it would be nice to also support the `valueAsNumber` attribute.

### Describe alternatives you've considered:

- Documentation note warning about the lack of support
- Console error warning about the lack of support when firing an event with this attribute

**Comment by eps1lon** [comment]
Have you tried providing `value` and `valueAsNumber`?

**Comment by dlbnco** [comment]
@eps1lon 

Just tried, it worked! Thanks.

**Comment by eps1lon** [comment]
This was a source of frustration for me as well. I think you always have to specify the value though I'm not sure about the specifics. I guess we can close this issue?

**Comment by chrisdemetriad** [comment]
Hi @dlbnco, I need to test a similar thing, but my `input type=range` is inside a component I render, so I won't have access to the `seekTo` method. How would I go about it?
