### ISSUE TITLE
Custom queries contain `__esModule` field

### ISSUE THREAD

**Issue by mbelsky** [testing-library/dom-testing-library#370]
Hey,

I followed [this guide](https://testing-library.com/docs/react-testing-library/setup#custom-render) to setup custom renderer with some custom queries and faced an issue:

```
TypeError: fn.bind is not a function
```

It happens because in my environment queries maps contain `__esModule` fields and the library falls there:

https://github.com/testing-library/dom-testing-library/blob/master/src/get-queries-for-element.js#L14-L15

I may make a pr with `key` or `fn` filtration but I'm not sure this will be an appropriate solution and that this should be handled by this library. So I'm here for your suggestion.

```javascript
function getQueriesForElement(element, queries = defaultQueries) {
  return Object.keys(queries).reduce((helpers, key) => {
    const fn = queries[key]
    helpers[key] = 'function' === typeof fn : fn.bind(null, element) ? undefined
    return helpers
  }, {})
}
```

- `DOM Testing Library` version: 6.4.1
- `node` version: 10.13.0
- `yarn` version: 1.17.3

**Comment by eps1lon** [comment]
> It happens because in my environment queries maps contain __esModule fields and the library falls there:

This property should be marked as not enumerable. Babel already does this by using 
```
Object.defineProperty(exports, "__esModule", {
  value: true
});
```
which means `__esModule` will not be included in `Object.keys(exports)`.

Maybe your environment has a bad implementation of `Object.defineProperty`?

**Comment by mbelsky** [comment]
Yes, it happened because `loose` mode was `true` for `@babel/preset-env` in my environment. So suggested above code looks like a bad hack.

Thanks!
