### ISSUE TITLE
[RFC] "not" queries

### ISSUE THREAD

**Issue by kandros** [testing-library/dom-testing-library#371]
### Describe the feature you'd like:

Being able to use `getByText("hello")` to check the presence of an element is super convenient due to `getBy*` doing the assertion

Checking that an element is NOT present is a bit more cumbersome, we have to use `queryBy*` and have to create the full assertion ourself `expect(queryByText("not present")).not.toBeInTheDocument()`

it would be great to have a way to check for missing elements and assert that the same way `getBy*` does
 

#### Using a new `not` object

```jsx
    function App() {
      const showError = false
      return (
        <div>
          <h2>hello</h2>

          {showError ? <div data-testid="error">invalid</div> : null}
        </div>
      )
    }

 test('not queries', () => {
    const { getByText, not } = render(<App />)

    getByText('hello')
    not.getByTestId('error')
    not.getByText('tomorrow')
  })
```

#### Using not modifier on current queries

```jsx
    function App() {
      const showError = false
      return (
        <div>
          <h2>hello</h2>

          {showError ? <div data-testid="error">invalid</div> : null}
        </div>
      )
    }

 test('not queries', () => {
    const { getByText, not } = render(<App />)

    getByText('hello')
	getByTestId.not('error')
    getByText.not('tomorrow')
  })
```

### Why not using new methods like `notGetByText()`

the main reason is that I enjoy following this flow inside a single test

- use query to assert something I expect(pass)
- fire event/other interaction
- same as the first query but with different parameter (mostly negation of the first test)
- implement feature to make the test pass

having maby new methods will have the user to import a lot more stuff from render result, and is a bit cumbersome if it happens that you want to change the type of query you are using

### Teachability, Documentation, Adoption, Migration Strategy:

the adoption and teaching would be straightforward given the `not` convention in testing frameworks is well adopted

**Comment by kentcdodds** [comment]
I have mixed feelings on this one. I'd love to hear input from others.

**Comment by alexkrolick** [comment]
I usually don't use the getBy as standalone assertions myself, but I could see why you might want this if you do. It would have to fit into the async query model though, with similar semantics to waitForElementToBeRemoved I would guess.

**Comment by kentcdodds** [comment]
One benefit of this is if `not.getByText(/abc/i)` fails, we can give a better error message than `expect(queryByText(/abc/i)).not.toBeInTheDocument()` could give.

**Comment by pheeria** [comment]
In my opinion, this proposal needs more ideas on the wording side. Currently it feels a bit unnatural, whereas _expect smth not to be in the document_ is very self-explanatory.

**Comment by kentcdodds** [comment]
Hi folks,

This hasn't had much discussion since it was opened, so I think we're going to close it and we can bring it up again in the future if someone feels strongly about it.

Thanks!
