### ISSUE TITLE
Can't get styles with CSS `calc()`

### ISSUE THREAD

**Issue by Kiarash-Z** [testing-library/dom-testing-library#387]
Hello, I found out that I can't get inline styles which has [CSS calc function](https://developer.mozilla.org/en-US/docs/Web/CSS/calc). Please consider these cases:
### ✅ Case 1: without `calc` function and using normal css values for inline styles:
Component:
```
const TestComponent = () => (
  <div
    style={{ width: '100px' }} 
    data-testid="wrapper"
  >
    Some content
  </div>
);
```

Test:
```
test('gets the correct style', () => {
 // some code which gets element by dom testing library
  console.log(element.style.width) // 100px
  expect(element.style.width).toBe('100px') // passes
})
```

### ❌ Case 2: using `calc` function for inline styles:
Component:
```
const TestComponent = () => (
  <div
    style={{ width: 'calc(100% - 100px)' }} 
    data-testid="wrapper"
  >
    Some content
  </div>
);
```

Test:
```
test('gets the correct style', () => {
 // some code which gets element by dom testing library
  console.log(element.style.width) // ''
  expect(element.style.width).toBe('calc(100% - 100px)') // fails because width is an empty string
})
```

### Reproduction:
Here's [an example on CodeSandBox](https://codesandbox.io/embed/react-testing-library-demo-98mrc)

### Problem description:
It looks like dom testing library doesn't parse inline styles which include `calc()`. I used the `debug` function to inspect DOM and there's no `style` attribute for such elements.

**Comment by pheeria** [comment]
This is most probably not a `dom-testing-library` issue, because internally, it relies on ready DOM nodes, provided either by JSDOM or Jest. As I just found out, JSDOM [still has this issue unresolved](https://github.com/jsdom/jsdom/issues/1332).

**Comment by kentcdodds** [comment]
Hi @Kiarash-Z,

As @pheeria suggests, it's a JSDOM issue. I'm afraid there's nothing this library can do to help with that.
