### ISSUE TITLE
[RFC] - MutationObserver Snapshots

### ISSUE THREAD

**Issue by nathanforce** [testing-library/dom-testing-library#394]
### Describe the feature you'd like:

This idea branches from the MutationObserver idea that @kentcdodds [mentioned on Twitter](https://twitter.com/kentcdodds/status/1182738518088376320) last week.  

The original idea was to auto check all DOM mutations generated from a user flow against something like `jest-axe` to validate against accessibility best practices.

As @kentcdodds mentions in the live stream, this functionality does not make sense for all use cases.  For example, testing a standalone `<Input />` component will fail because it is meant to be used alongside a corresponding `<Label />` component.

My proposal is to have `render()` return an array of HTML "snapshots" or "frames" containing a DOM snapshot of the mutations that happened during the test.  The developer can use these snapshots to validate whatever they want! You could even `jest.toMatchSnapshot(snapshot)` all of them.

```
const { container, snapshots } = render(<ComplicatedOrderForm />);

// Use the form/rerender

for (const snapshot of snapshots) {
    expect(await axe(snapshot)).toHaveNoViolations();
}

```

As this will (probably?) add some overhead to the tests, we could have this functionality be opt-in.

### Suggested implementation:

This is for an individual test, but it is the same general code:

https://pbs.twimg.com/media/EHgiAA_X0AEQUB1?format=jpg&name=4096x4096

### Describe alternatives you've considered:

1. Automatically doing the axe check for all tests
2. Exposing a function/pattern to be used in `afterEach`

### Teachability, Documentation, Adoption, Migration Strategy:

📚

**Comment by kentcdodds** [comment]
I don't think this will work. Just tried this and it's not passing. If you can figure out how to get this to pass then we can consider it. But again, I think that it's not something that works well for unit and even some integration testing. Probably fits better for E2E.

Here's what's failing for me. Get it to pass and we'll seee :)

```jsx
test('auto-axe', async () => {
  function MyForm() {
    const [bad, setBad] = React.useState(false)
    return (
      <>
        <form>
          {bad ? null : <label htmlFor="username">Username</label>}
          <input id="username" placeholder="username" />
        </form>
        <button onClick={() => setBad(b => !b)}>toggle bad</button>
      </>
    )
  }
  const changes = []
  const observer = new MutationObserver(mutations => {
    for (const mutation of mutations) {
      const dom = mutation.target.innerHTML
      changes.push(dom)
    }
  })

  observer.observe(document.body, {
    attributes: true,
    childList: true,
    characterData: true,
    subtree: true,
  })

  const {getByText} = render(<MyForm />)
  fireEvent.click(getByText(/toggle bad/i))

  observer.disconnect()

  expect(changes).toHaveLength(2)
  expect(await axe(changes[0])).toHaveNoViolations()
  expect(await axe(changes[1])).toHaveNoViolations()
})
```

**Comment by kentcdodds** [comment]
To be clear, here's the failure output:

```
 FAIL
  ✕ auto-axe (33ms)

  ● auto-axe

    expect(received).toHaveLength(expected)

    Expected length: 2
    Received length: 0
    Received array:  []

      53 |   observer.disconnect()
      54 | 
    > 55 |   expect(changes).toHaveLength(2)
         |                   ^
      56 |   expect(await axe(changes[0])).toHaveNoViolations()
      57 |   expect(await axe(changes[1])).toHaveNoViolations()
      58 | })

      at Object.toHaveLength
```

**Comment by kentcdodds** [comment]
I'm going to close this for now. If there's progress then we can open it up again :)

**Comment by nathanforce** [comment]
@kentcdodds Took a stab at getting this working, just out of curiosity.

https://github.com/nathanforce/dom-testing-library-mutation-observer/blob/master/test/mutations.test.js

It seems that the observer disconnects too soon. I was only able to get it working by adding a `wait()`, which is a bummer.  Maybe if this were happening in the testing library itself there would be a better way to know when to disconnect.
