### ISSUE TITLE
breaking change in 6.8.1

### ISSUE THREAD

**Issue by benmonro** [testing-library/dom-testing-library#396]
- `DOM Testing Library` version: 6.8.1
- `node` version: 10.x
- `npm` (or `yarn`) version: 6.x

### Relevant code or config:

```js
const allFavoritesTab = within(favoritesTabContainer).getAllByRole('tabpanel')
```

### What you did:

After updating RTL from 9.1.1 to 9.3.0 (which updated DTL from 6.0.0 to 6.8.1) we started having tests that break.  I believe the failure could potentially be related to this PR: https://github.com/testing-library/dom-testing-library/pull/381/files

### What happened:

our component is rendering 2 tab panels, 1 visible, 1 hidden, and our test is verifying that as you click on tabs, the tab panels are shown hidden etc.  If this is an intended behavior for RTL/DTL, I totally get it, but it should be a breaking change, and thus a new major rev, not part of 8.x which works for us previously.

### Reproduction:

can't provide internal code,  but if you have 2 tab panels 1 hidden 1 shown and test that `getAllByRole('tabpanel')` using the 2 versions mentioned above you should see it.

**Comment by eps1lon** [comment]
This was introduced in 6.4 with https://github.com/testing-library/dom-testing-library/pull/352. You can pass `{ hidden: true }` to get the old behavior back.

**Comment by benmonro** [comment]
so why didn't that get deployed as a 7.x since it's a breaking change?

**Comment by eps1lon** [comment]
> so why didn't that get deployed as a 7.x since it's a breaking change?

See https://github.com/testing-library/dom-testing-library/pull/352#issuecomment-534238975

**Comment by kentcdodds** [comment]
Ugh. Yeah, I guess it probably should have been 😬 I honestly didn't think many people relied on that functionality and didn't even consider this kind of case at all. Sorry about that.

This whole situation would be way easier if performance weren't such a pain for that filtering function :-( I'm just not sure what to do with this.

**Comment by benmonro** [comment]
all good. 👍
