### ISSUE TITLE
If a selector is passed in to ByText query add element text value to the error info

### ISSUE THREAD

**Issue by pllee** [testing-library/dom-testing-library#402]
It would be nice to see the value of the text selector (or even just the element) in the error message when a `ByText` query does not match.  

My use case is that I have a large element (and in turn "complicated" selectors) that I am rendering for example if I want to check the rendering of `$7.00` but I tried to match `7.00` I can't easily see why the `getByText` query failed.  If just used a jest assertion for example I would be able to see easily that I forgot the `$`.

```
    expect(received).toBe(expected) // Object.is equality

    Expected: "7.00"
    Received: "$7.00"
```
vs

```
    Unable to find an element with the text: 7.00. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        ... lots of markup
```

### Suggested implementation:

This is pretty hacky but the following might work: 

https://github.com/testing-library/dom-testing-library/blob/master/src/queries/text.js#L34

```js
const getMissingError = (c, text) =>
  `Unable to find an element with the text: ${text}. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.`
```

Looks like it can be replaced with:

```js
const getSelectorInfo = (container, selector) => {
  if (selector !== DEFAULT_SELECTOR) {
    const el = container.querySelector(selector);
    if (!el) {
      return `Element not found for selector ${selector}`;
    }
    return `Element text found: ${getNodeText(el)}`;
  }
};

const getMissingError = (c, text, { selector }) => {
  const extraInfo = getSelectorInfo(c, selector);
  `Unable to find an element with the text: ${text}. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.${
    extraInfo ? `  ${extraInfo}` : ''
  }`;
};

```

### Describe alternatives you've considered:

I can add this as a custom override query to my app but I think this behavior would be useful to everyone.

### Teachability, Documentation, Adoption, Migration Strategy:

I don't think there would be extra docs for this feature.

**Comment by kentcdodds** [comment]
Hi @pllee,

I'm not sure how effective doing this will be I'm afraid. There's an issue with the suggestion you're proposing and that is that it's very likely that the `selector` will match multiple elements on the page, so passing it to `querySelector` like that will only get the first one which may not be the correct element.

**Comment by pllee** [comment]
Hi @kentcdodds,

Thanks for the quick feedback.  I guess it could do `querySelectorAll` to get all the elements that it matched.  Ideally it would get the nodes that are returned by the `queryAllByText` function but I assume that would be a change not worth making.

I think for my use cases the value that I pass to the selector field should always return a unique element but that is not a requirement for everyone.  It would be nice to have a `uniqueSelector` attribute but I would assume that is not worth doing either haha.  I can stick to just keeping this as a local override unless the community sees merit in having the extra debugging info.


Updated code:

```js
const getSelectorInfo = (container, selector) => {
  if (selector !== DEFAULT_SELECTOR) {
    const els = Array.from(container.querySelectorAll(selector));
    if (!els.length) {
      return `Element(s) not found for selector ${selector}`;
    }
    return els.map((el) => `Element text found: ${getNodeText(el)}`).join('\n');
  }
};

const getMissingError = (c, text, { selector }) => {
  const extraInfo = getSelectorInfo(c, selector);
  `Unable to find an element with the text: ${text}. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.${
    extraInfo ? `\n${extraInfo}` : ''
  }`;
};
```

**Comment by kentcdodds** [comment]
Yeah, the problem is that in practice your updated code would result in showing the text content for every element on the page which could be a LOT of text. I don't think it would be very helpful. Sorry :-/
