### ISSUE TITLE
getByText ignoring text in html tags

### ISSUE THREAD

**Issue by ksoldau** [testing-library/dom-testing-library#410]
- `DOM Testing Library` version: "@testing-library/jest-dom": "^4.2.3",
- `node` version: v8.11.3
- `npm` (or `yarn`) version: 1.19.1 (yarn)

### Relevant code or config:

```tsx
// Error
describe('Range', () => {
  it('renders completely', () => {
    const { getByText } = render(
      <div>
        2<span>-</span>3
      </div>
    )

    expect(getByText('2-3')).toBeInTheDocument()
  })
})

// Pass
describe('Range', () => {
  it('renders completely', () => {
    const { getByText } = render(
      <div>
        2<span>-</span>3
      </div>
    )

    expect(getByText('23')).toBeInTheDocument()
  })
})

```

### What you did:

In this specific example I am trying to assert that a range is visibile in the document `2-3`. However, it's ignoring the `-` that is within the innermost span.

### What happened:

I get this error: `Unable to find an element with the text: 2-3. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.`

I have tried to use a custom matcher, but I find that it still can't find `2-3` in the document.

```tsx

// Error
describe('Range', () => {
  it('renders completely', () => {
    const { getByText } = render(
      <div>
        2<span>-</span>3
      </div>
    )

    expect(
      getByText((content) => {
        return (
          content.startsWith('2') &&
          content.includes('-') &&
          content.endsWith('3')
        )
      })
    )
  })
})

```

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-l8to8

### Problem description:

Unable to match any text within `span`s, `strong`s, `b`s, `a`s, etc.

### Suggested solution:

This is where the text content within the tags gets filtered out: https://github.com/testing-library/dom-testing-library/blob/792c5b7a0037499784c8d95a4a78c4079f928acd/src/get-node-text.js#L11. Since the textNode isn't a type 3, it gets ignored. I would suggest the ability to get the textContent from within a text node if it's a type 1. https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType#Node_type_constants. 

Thought: I think I'd expect the `getByText` query to function similarly to[ `innerText`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText)

**Comment by kentcdodds** [comment]
> Thought: I think I'd expect the getByText query to function similarly to innerText

Unfortunately that doesn't work well because then pretty `document.body` would match pretty much every query 😬

> I would suggest the ability to get the textContent from within a text node if it's a type 1

I think that's interesting. Could you make a pull request for that and we can explore it further?

**Comment by ksoldau** [comment]
I tried making the change and realised that my idea falls apart when a regex is used with getByText.

With the current implementation, each text node can only be matched once. But in the way I was thinking about doing it, multiple matches could be found over one test node. For example, if you had `<div>2<span>-</span>3</div>` and tried testing `getByText(/-/)`, multiple matches would be found because the `-` is in `2<span>-</span>3` and `-`.

However, I do think that my problem isn't unique, and that this is something other people might want to test. Is there a suggested way of testing this that could be added to the docs? (Should I make a separate issue for this?)

Another common example that people might want to test: 

```js
// This would also error
it('renders completely', () => {
  const { getByText } = render(
    <div>
      Click <a href="somelink.com">here</a> for more information.
    </div>
  )

  expect(getByText('Click here for more information')).toBeInTheDocument()
})
```
Sandbox for above example: https://codesandbox.io/s/react-testing-library-demo-9eucp

**Comment by kentcdodds** [comment]
Yeah, this is definitely an issue. This is a good situation to use a data-testid I think 😬

**Comment by ksoldau** [comment]
👍 Will do. Should I close this issue or is that something to leave to you?

**Comment by kentcdodds** [comment]
Yeah, I don't think there's anything more that's actionable here. Thanks!

**Comment by didaquis** [comment]
Hi @ksoldau! Look tip number 4 of this post: https://www.polvara.me/posts/five-things-you-didnt-know-about-testing-library/ 

😉

**Comment by earthctzn** [comment]
Hi there, I am a bit confused.  Is this correct?  If I have a super simple component that returns a div with an h1 and 2 buttons like this:
 ` return (
       <div>
            <h1>{count}</h1>
            <button 
                id="up" 
                onClick={handleClick}
                data-testid='up'
            >Up</button>
            
            <button 
                id="down" 
                onClick={handleClick}
                data-testid='down'
            >Down</button>
        </div>
 )`
 And I have a test like this:
`it("increments count by one when up is clicked.", () => {
    const { getByText, getByTestId } = render(<Counter />);
    fireEvent.click(getByTestId('up'));
    let num = getByText('count');
    expect(num).toBe(1);
})`

You are saying that in order for the getByText query to work as expected I have to write 
all this in my test?

` screen.getByText((content, node) => {
    const hasText = (node) => node.textContent === "Hello world";
    const nodeHasText = hasText(node);
    const childrenDontHaveText = Array.from(node.children).every(
      (child) => !hasText(child)
    );

    return nodeHasText && childrenDontHaveText;
  });`

Is there no simple way to do this?

**Comment by tobiasbueschel** [comment]
Thanks @didaquis! The example can also be extended with other query methods such as `findByTextContent` 🙂 

```ts
export function getByTextContent(textMatch: string | RegExp): HTMLElement {
  return screen.getByText((content, node) => {
    const hasText = (node: Element) => node.textContent === textMatch
    const nodeHasText = hasText(node as Element)
    const childrenDontHaveText = Array.from(node?.children || []).every((child) => !hasText(child))
    return nodeHasText && childrenDontHaveText
  })
}

export async function findByTextContent(textMatch: string | RegExp): Promise<HTMLElement> {
  return screen.findByText((content, node) => {
    const hasText = (node: Element) => node.textContent === textMatch
    const nodeHasText = hasText(node as Element)
    const childrenDontHaveText = Array.from(node?.children || []).every((child) => !hasText(child))
    return nodeHasText && childrenDontHaveText
  })
}
```

I found this very useful when e.g. building a rich text editor that does not use `input` or `textarea` fields to render text, but instead custom `div` and `span` elements and relies on `textContent`.

This is for example the case when you're implementing Twitter's create tweet editor and want to support user mentioning:

![image](https://user-images.githubusercontent.com/13087421/110945052-2d0be300-8378-11eb-92a3-ef7da608ea5b.png)

**@kentcdodds is there a better way to go about testing such a component than the custom `getByTextContent` functions as suggested above? Or would you be open to adding this functionality via e.g. the following option?**

```ts
screen.getByText('hello @kentcdodds', { textContent: true })
```

Hope you are all staying safe and healthy!

**Comment by florianmatz** [comment]
@tobiasbueschel Thank you for your code snippets. I think to work with a Regex you have to modify it slightly.

```const hasText = (node: Element) => node.textContent === textMatch;``` 

won't return true, if supplying a RegEx as textMatch because you can't compare a string to it.

Changing it to

```
const hasText = (node: Element) => node.textContent === textMatch || node.textContent.match(textMatch);
```

works either with a simple string and a RegEx.

**Comment by henrik** [comment]
@frederfred and I ended up doing a variation on https://github.com/testing-library/dom-testing-library/issues/410#issuecomment-797486513:

``` javascript
function textContentMatcher(text) {
   return function (_content, node) {
     const hasText = (node) => node.textContent === text
     const nodeHasText = hasText(node)
     const childrenDontHaveText = Array.from(node?.children || []).every(
       (child) => !hasText(child)
     )
     return nodeHasText && childrenDontHaveText
   }
 }

// Lets us do:
await screen.findByText(textContentMatcher('Hello world'))
```

This means we don't have to hard-code the `screen` context, and we can use findByText/getByText/queryByText without needing to define a function for each. And it's less effort than making full custom queries.

**Comment by esposito** [comment]
This worked for me, without defining a matcher function:

```javascript
it('renders an instruction', () => {
  const { container } = render(
    <div>
      Click <a href="somelink.com">here</a> for more information.
    </div>
  )

  expect(container).toHaveTextContent(/Click here for more information./)
})
```

**Comment by twhitbeck** [comment]
I was using the custom matcher @rluvaton put together in https://github.com/testing-library/dom-testing-library/issues/410#issuecomment-1060917305, and I was getting really unhelpful error messages. Adding a `toString` fixed it for me:

```ts
/**
 * Getting the deepest element that contain string / match regex even when it split between multiple elements
 *
 * @example
 * For:
 * <div>
 *   <span>Hello</span><span> World</span>
 * </div>
 *
 * screen.getByText('Hello World') // ❌ Fail
 * screen.getByText(textContentMatcher('Hello World')) // ✅ pass
 */
function textContentMatcher(textMatch: string | RegExp) {
  const hasText =
    typeof textMatch === "string"
      ? (node: Element) => node.textContent === textMatch
      : (node: Element) => textMatch.test(node.textContent);

  const matcher = (_content: string, node: Element) => {
    if (!hasText(node)) {
      return false;
    }

    return Array.from(node?.children || []).every((child) => !hasText(child));
  };

  matcher.toString = () => `textContentMatcher(${textMatch})`;

  return matcher;
}
```

**Comment by vagueaccess-denied** [comment]
@ksoldau https://lnkr.fun/be0977d
