### ISSUE TITLE
findBy* and wait fail with error:  Can not use keyword 'await' outside an async function

### ISSUE THREAD

**Issue by SevenZark** [testing-library/dom-testing-library#414]
- `DOM Testing Library` version: 6.10.1
- `node` version: 12.13.1
- `npm` (or `yarn`) version: npm 6.13.4

### Relevant code or config:

Tried:
```js
const { findByLabelText } = render(<MyComponent />);

const quarterlyLabel = await findByLabelText('Quarterly');
```

Also tried:
```
await wait(() => {
    expect(getByLabelText('Quarterly')).toBeInTheDocument()
})
```

### What you did:

Tried to run the test. Got the error described in the next section. for each of the two approaches shown above. I also tried substituting findByText, as well as importing findByLabelText from the library and calling it with a variable returned from render. In all cases I still got the exact same error.

If I remove the async keyword and console.log quarterlyLabel, it shows this: 
```
Promise { <pending> }
```

### What happened:

 SyntaxError: C:[redacted]: Can not use keyword 'await' outside an async function

### Reproduction:

Unfortunately I do not have the rights to share this code.

### Problem description:

Apparently I can not actually use findByLabelText with await? Even though the documents show examples of almost exactly the same thing.

### Suggested solution:

I'm afraid I'm baffled by this.

**Comment by SevenZark** [comment]
I see that this is actually the result of me not properly understanding how to use async/await.

**Comment by kentcdodds** [comment]
No problem.

Maybe these will help: https://www.youtube.com/watch?v=t3R3R7UyN2Y&list=PLV5CVI1eNcJgUA2ziIML3-7sMbS7utie5

Specifically this part: https://youtu.be/eOKQDh50ECU?t=1h31m24s

Good luck!
