### ISSUE TITLE
 fireEvent.click on "a" tag not working triggering onClick

### ISSUE THREAD

**Issue by goncaloflf** [testing-library/dom-testing-library#422]
- `DOM Testing Library` version: 6.11.0
- `node` version: 12.14.0
- `npm` version: 6.13.4

### Relevant code or config:

https://codesandbox.io/s/nameless-sky-0uqcg

### What you did:

I was testing a React Application using `dom-testing-library`. One of the tests implies creating a DOM element, render a React Application on it, click an `anchor` and expect the onClick handler to be called. 

### What happened:

The `fireEvent.click(anchor)` did not trigger the onClick handler defined for this element. 

### Reproduction:

See [codesandbox](https://codesandbox.io/s/nameless-sky-0uqcg
). On the tests tab. 

### Problem description:

`fireEvent.click` should work the same way as without using `ReactDOM.render` directly.

**Comment by eps1lon** [comment]
Thanks for opening this issue an providing a reproduction.

Could you reduce it to an example that's using the recommende approach for testing react components by using `render` from `@testing-library/react`? Right now it's hard to distinguish if the problem is on our side or with your setup.

**Comment by goncaloflf** [comment]
Hello, thanks for your time.

We can't reduce it anymore, this is already reduced a lot to mimic our use case without the complexity. However, we have found the problem (and the solution, as well).

The problem is that, on the test, we are creating a instance of index (renamed it to app on the codesandbox below because of some bug with codesandbox itself) on a `rootElement`, which is created on the document. However, we were not appending it do the DOM. Because of that, the click event was not triggering (can't bubble if not appended to the DOM), and the test was failing. 

On [this codesandbox](https://codesandbox.io/s/beautiful-almeida-lvg43) you can see the same test passing by adding `document.body.appendChild("rootElement")`.

**Comment by eps1lon** [comment]
For testing React components please use `@testing-library/react` not `@testing-library/dom`. If the issue still persists please open a new issue using `@testing-library/react` in the react-testing-library repo: https://github.com/testing-library/react-testing-library/issues/new?template=Bug_Report.md
