### ISSUE TITLE
Unnecessary commented out code in event types?

### ISSUE THREAD

**Issue by JonathanStoye** [testing-library/dom-testing-library#423]
- `DOM Testing Library` version: 9.4.0
- `node` version: 13.4.0
- `npm` (or `yarn`) version: yarn 1.19.1

### Relevant code or config:

I just came across the events in the repo and found [this](https://github.com/testing-library/dom-testing-library/blame/4fed5aeab5334e871c71bd53e2da61907119d0f3/src/events.js#L213):

```
  // error: {
  //   EventType: Event,
  //   defaultInit: {bubbles: false, cancelable: false},
  // },
```

Which I guess should be removed. It also exists [here](https://github.com/testing-library/dom-testing-library/blame/4fed5aeab5334e871c71bd53e2da61907119d0f3/src/events.js#L282) without comments so I am assuming this was supposed to be cleaned up at some point? Git blame says its been there for the last two years so I would say it is save to remove it.

### Suggested solution:

Remove it. I am happy to help.

**Comment by kentcdodds** [comment]
Sure, you can make a PR to remove that. Thanks!
