### ISSUE TITLE
Transfer eslint-plugin-testing-library

### ISSUE THREAD

**Issue by Belco90** [testing-library/dom-testing-library#424]
Hi again! I feel like the plugin originated while ago in #345 is mature enough to be transferred so I'm happy to do this now. I would like to know what's the proper process to transfer eslint-plugin-testing-library to testing library organization, keeping the package not scoped so it can be referenced as `eslint-plugin-testing-library`.

Thanks!

**Comment by kentcdodds** [comment]
Closing in favor of https://github.com/Belco90/eslint-plugin-testing-library/issues/27

Sorry it took so long for me to get to this, just took a break for a few weeks :) Thanks!
