### ISSUE TITLE
Test in element-queries.js causes a linting warning jest/valid-title

### ISSUE THREAD

**Issue by seetdev** [testing-library/dom-testing-library#436]
- `DOM Testing Library` version: 6.11.1
- `node` version: v13.3.0
- `npm` (or `yarn`) version: 6.13.6

### Relevant code or config:

https://github.com/testing-library/dom-testing-library/blob/3805b2772f93d2e5a16858d50231eeafb6c6e484/src/__tests__/element-queries.js#L680

### What you did:

I was running `npm run lint` on repo pulled down from a fork of `git@github.com:testing-library/dom-testing-library.git`

### What happened:
The warning `680:6  warning  should not have duplicate prefix  jest/valid-title` gets return from the console

<img width="574" alt="Screen Shot 2020-01-28 at 10 38 19 PM" src="https://user-images.githubusercontent.com/35116035/73326074-ef550500-421e-11ea-871f-68df63861a2a.png">

### Problem description:

1. Open terminal / shell and run `git clone git@github.com:testing-library/dom-testing-library.git`
2. Go into the clone repo `cd dom-testing-library` 
3. Install all dependencies `npm install`
4. Run lint on the repo `npm run lint`
5. The warning should show on the command prompt

### Suggested solution:

Remove the word `test` from the description

https://github.com/seetdev-opensource/dom-testing-library/blob/973664c802bffc578950d9cef1635d660f2002ce/src/__tests__/element-queries.js#L680

**Comment by kentcdodds** [comment]
Thanks! Would you like to open a PR for this?
