### ISSUE TITLE
Feature request: StorageEvent on the Window

### ISSUE THREAD

**Issue by seetdev** [testing-library/dom-testing-library#438]
### Describe the feature you'd like:

I am working on a project that makes use of the localStorage one of the W3C web storages. I need to handle the StorageEvent on the window that gets fired when the underlying storage medium is modified. I will be happy to put in the PR for this.

### Suggested implementation:

It will involve adding a new entry to the eventMap in src/events.
The test implementation will be similar to `fires history popstate event on Window`

w3c specs for event: https://html.spec.whatwg.org/multipage/webstorage.html#the-storageevent-interface
MDN documentation: https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event

### Describe alternatives you've considered:

Maybe do `window.dispatchEvent( new Event('storage') );` and handle the event listener

```
window.addEventListener("storage", e => {
    // Tests here
});

window.dispatchEvent( new Event('storage', { key: "key", oldValue: "oldValue", newValue: "newValue", url: "https://www.example.com", Storage: localStorage  }) );
```

**Comment by alexkrolick** [comment]
Is this something that should be implemented in JSDOM?

**Comment by seetdev** [comment]
Looking at the code in the code in https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/webstorage/Storage-impl.js
 it appears JSDom does have the storage and associated event implemented. Should the approach be putting in an EventListener that handles the event triggered here if I need to test that the storage event is fired based on my application code?

**Comment by aw-davidson** [comment]
I would just spy on localStorage setItem

**Comment by kentcdodds** [comment]
Hi @seetdev,

Thanks for the issue. I agree with what's been said. I think this should be something that's implemented by JSDOM. For now, I would go with @aw-davidson's suggestion of spying on `localStorage` setItem:

```javascript
beforeAll(() => {
  jest.spyOn(window.localStorage, 'setItem')
  // you may want to call window.localStorage.setItem.mockImplementation
  // depending on what you're trying to do...
})

beforeEach(() => {
  // cleanup between tests
  window.localStorage.setItem.mockClear()
})

afterAll(() => {
  // restore the original implementation
  window.localStorage.setItem.mockRestore()
})
```

**Comment by mentierd** [comment]
I know this is closed, but JSDOM has yet to fix this as of v16.2.1

A non-jest/sinon solution would look like this:

`
import { implSymbol } from 'jsdom/lib/jsdom/living/generated/utils';

type StorageEventCallback = (key: string, oldValue: any, newValue: any) => void;

export class ObservableMap extends Map {

    private readonly _callback: StorageEventCallback

    constructor(callback: StorageEventCallback) {
        super();

        this._callback = subscribe;
    }

    set(key, newValue): void {

        const oldValue = super.get(key);

        super.set(key, newValue);

        this._callback(key, oldValue, newValue);
    }
}

Object.defineProperty(window.localStorage[implSymbol], '_items', {
      value: new ObservableMap((key, oldValue, newValue) => {
            (window[implSymbol]._eventListeners.storage || []).forEach(({callback}) => {
                  callback({
                        storageArea: window.localStorage,
                        newValue,
                        oldValue,
                        key
                    });
             });
      }),
      configurable: true
});
`

**Comment by zendesk-chrants** [comment]
This worked for me on `@testing-library/react: 12.1.2`

```js
act(() => {
  fireEvent(
    window,
    new StorageEvent('storage', {
      key: 'STORAGE_KEY', // your value here
      storageArea: localStorage,
      newValue: 'VALUE', // your value here
    })
  );
});
```

**Comment by bruno-vinicius** [comment]
This answer [in stackoverflow](https://stackoverflow.com/questions/50767241/observe-localstorage-changes-in-js) worked for me. The only thing it's weird is why we needed to manually dispatch the event after a localstorage.setItem call (Maybe because the [`storage` event](https://developer.mozilla.org/en-US/docs/Web/API/StorageEvent) was suppose to just be listened by another tab?).

**Comment by airtonix** [comment]
> This answer [in stackoverflow](https://stackoverflow.com/questions/50767241/observe-localstorage-changes-in-js) worked for me. The only thing it's weird is why we needed to manually dispatch the event after a localstorage.setItem call (Maybe because the [`storage` event](https://developer.mozilla.org/en-US/docs/Web/API/StorageEvent) was suppose to just be listened by another tab?).

yep, people using rooks `useLocalStorage` expect two instances in separate tabs to affect each other.
