### ISSUE TITLE
.findAllByTestId failing in Vr5.1.1

### ISSUE THREAD

**Issue by JoeEarly** [testing-library/dom-testing-library#439]
- `DOM Testing Library` version: 5.1.1
- `node` version: 11.4.0
- `npm` (or `yarn`) version: npm: 6.13.1 yarn: 1.21.1

### Relevant code or config:

```js
cy.visit("/admin")
      .withConfig({})
      //.findAllByTestId("Get Started with the Building Directory app")
      .findAllByTestId("onboard-title-0")
      .should("be.visible")
      .and("contain", "Get Started")
```

### What you did:

I am creating a set of tests here and few weeks ago this was passing fine. Now with an upgrade in package version, the 'findAllByTestId' is failing. 

I rolled back versions of the cypress-testing-library so it seems this has been introduced as of Vr 5.1.1 

### What happened:
<img width="1678" alt="Screenshot 2020-01-30 at 12 01 59" src="https://user-images.githubusercontent.com/5208459/73449466-229cae80-435b-11ea-9291-8fb983983ddc.png">
<img width="557" alt="Screenshot 2020-01-30 at 12 02 07" src="https://user-images.githubusercontent.com/5208459/73449467-23354500-435b-11ea-90f3-6f7fb71b710d.png">

**Comment by eps1lon** [comment]
Did you bump the version of `testing-library/cypress` or `testing-library/dom`?

**Comment by JoeEarly** [comment]
Would of been **testing-library/cypress** only

**Comment by eps1lon** [comment]
Could you [open an issue on their repo](https://github.com/testing-library/cypress-testing-library) then please and include the version of testing-library/cypress?

**Comment by JoeEarly** [comment]
Will do, opened it here as when I went to open it there it told me to open it here. 

Will close this out and open one over in the correct repo
