### ISSUE TITLE
Support Selection and Range APIs - jsdom 16

### ISSUE THREAD

**Issue by tgonzalez-asapp** [testing-library/dom-testing-library#441]
### Describe the feature you'd like:

Add support for Selection and Range APIs

### Suggested implementation:

Bump jsdom dependency to 16.x.x
https://github.com/jsdom/jsdom/blob/master/Changelog.md#1600

**Comment by eps1lon** [comment]
We're not responsible for your testing environment. If you're using jest, try jest-environment-jsdom-sixteen.

However, we should bump it internally as well. But that's unrelated to Selection and Range API support.
