### ISSUE TITLE
firing keyboard events should throw if the target isn't focused.

### ISSUE THREAD

**Issue by eps1lon** [testing-library/dom-testing-library#449]
### Describe the feature you'd like:

`fireEvent.keyDown` (and other keyboard events) should throw if the passed element isn't focused.

### Suggested implementation:

Compare the passed element against `document.activeElement || document.body || document.documentElement` following 

> The event target of a key event is the currently focused element [...]  If no suitable element is in focus, the event target will be the HTML body element if available, otherwise the root element.

-- https://www.w3.org/TR/uievents/#events-keyboard-event-order

### Describe alternatives you've considered:

Use a custom wrapper or prefer `fireEvent.keyDown(document.activeElement)`. I've been preaching this for some time now. I realized that this reduces readability of tests though. I now have to keep in my head which element is actually focused. Reading `fireEvent.keyDown(treeitem)` while testing-library verifying that the treeitem is actually focused would help a lot here.

### Teachability, Documentation, Adoption, Migration Strategy:

The benefit is to force tests to be closer to the state your component under test will actually be. Your component will only receive keyboard events (from a user) when focused. Your test should match this. 

This will catch bad button implementations that are not focusable e.g. `<div onKeyDown onClick />`.

This is likely to cause a lot of test breakage. I'm interested to hear if you think this is  worth it or better handled in a custom implementation or a new `user-event` function.

**Comment by kentcdodds** [comment]
I agree 👍 Let's make this happen in the upcoming breaking change.

If you'd like to make a PR that would be good. Let's make certain the error message is very clear!

**Comment by kentcdodds** [comment]
I'll go ahead and do this right now.

**Comment by kentcdodds** [comment]
Actually, I'm not sure on this one, but shouldn't lots of the events we fire only be fired on the active element? Like keyUp and click, etc?

**Comment by eps1lon** [comment]
key events, sure. But click not so much. You're probably thinking about some platforms where a mousepress triggers focus before the click event is dispatched? I think that's not the default for iOS. And then it's always possible to `.preventDefault` in mousedown.

**Comment by kentcdodds** [comment]
After considering this a bit I think it'd be better to put this logic in user-event (or just have it handle setting the activeElement automatically which I think it does).

The reason being, what about MouseEvents? For mousedown, you'd want to make sure that the element recently received a mouseenter and mouseover event for the same reason, right? So I'm thinking, let's just make sure user-event handles this properly.

Sorry for the trouble.
