### ISSUE TITLE
Inifinite loop when clicking on a select inside a label element

### ISSUE THREAD

**Issue by foxbunny** [testing-library/dom-testing-library#453]
- `DOM Testing Library` version: 6.12.0
- `node` version: 13.7.0
- `npm` (or `yarn`) version: 6.13.6

### Relevant code or config:

Component:

```jsx
export default function App() {
  return (
    <label>
      Select me:
      <select>
        <option value="1">first</option>
      </select>
    </label>
  );
}
```

Test:

```jsx
test('click select', function () {
  let { getByRole } = render(<App/>)
  fireEvent.click(getByRole('listbox'))
})
```

### What you did:

Simulated a click on a `<select>` element that is inside a `<label>` element.

### What happened:

Get `Maximum call stack size exceeded`.

### Reproduction:

https://codesandbox.io/s/eloquent-pike-7uw1h

### Problem description:

When clicking a select (or possibly input) element which is inside a label, the code is thrown into an infinite loop, which shouldn't happen.

**Comment by kentcdodds** [comment]
Hi @foxbunny,

This works locally for me when I pull it down

![image](https://user-images.githubusercontent.com/1500684/75808135-d1118600-5d43-11ea-964b-321ed1bde367.png)

So I'm guessing this is an issue with codesandbox. Please [open an issue on codesandbox-client](https://github.com/codesandbox/codesandbox-client/issues/new).

Thanks!

**Comment by foxbunny** [comment]
Code sandbox is a demo for an issue I've encountered locally, though.

**Comment by foxbunny** [comment]
I'll see if I can come up with a repro git repo.

**Comment by kentcdodds** [comment]
Gotcha. Yes, if you could do that, it would be very helpful. Thank you!

**Comment by hesxenon** [comment]
maybe related (or solvable) by https://github.com/testing-library/user-event/issues/1237?
