### ISSUE TITLE
Decide what to do with `getQueriesForElement` and `within`

### ISSUE THREAD

**Issue by NMinhNguyen** [testing-library/dom-testing-library#471]
### Describe the feature you'd like:

Decide whether to keep both `getQueriesForElement` and `within`. I spoke to @kentcdodds on Twitter and he thinks that perhaps we should keep both. He suggested that I create an issue to discuss.

If both are kept, perhaps the docs could be improved to help people decide between the two.

**Comment by kentcdodds** [comment]
I'd love to hear from other people. I'm not a fan of two ways to do the same thing (which is all aliases are), but I kind of like the way it reads in the different situations people use them in:

- `getQueriesForElement`: used by framework integration libraries
- `within`: used by users who want to scope some queries within an element (like a modal).

**Comment by NMinhNguyen** [comment]
What about the third though, `bindElementToQueries`? Or do you see value in it being used by framework integration libraries too?

**Comment by kentcdodds** [comment]
Oh, right, whoops, I honestly totally forgot about that and didn't even bother to read it because I assumed this was talking about the `within` alias.

Yeah, let's get rid of `bindElementToQueries` 💯

**Comment by NMinhNguyen** [comment]
> Yeah, let's get rid of `bindElementToQueries` 💯

I can repurpose the issue description :) Would you like to deprecate it first or just remove it?

**Comment by kentcdodds** [comment]
It's not been documented for a long time so I doubt anyone would be mad if we removed it. And renaming would be really trivial anyway.
