### ISSUE TITLE
waitFor in 7.x no longer works with Apollo `MockedProvider` testing utility.

### ISSUE THREAD

**Issue by lifeiscontent** [testing-library/dom-testing-library#485]
- `DOM Testing Library` version:
- `node` version:
- `npm` (or `yarn`) version:

### Relevant code or config:

https://github.com/lifeiscontent/realworld/blob/master/web/src/components/article-form/index.spec.js

### What you did:

Migrated this repo https://github.com/lifeiscontent/realworld from `wait` to `waitFor`.

### What happened:

jest never finishes running.

### Reproduction:

https://github.com/lifeiscontent/realworld/pull/25

### Problem description:

There's a hook in the `InputTag` component and this makes a query via apollo client.

Previously, I had just wrapped the render in a `wait` and things seemed to work.

**Comment by kentcdodds** [comment]
Hi @lifeiscontent,

These tests are pretty problematic: https://github.com/lifeiscontent/realworld/blob/83cc565ca5826ae47c8795a27bce2e593579a373/web/src/components/article-form/index.spec.js

Wrapping everything you're doing in `await wait` calls was never recommended, is completely unnecessary in most cases, and in some cases could cause some seriously unexpected and confusing failures. For example:

```javascript
    await wait(() => {
      const submitButton = getByRole('button');
      fireEvent.click(submitButton);
      const errors = getAllByText(/is a required field$/);

      expect(errors).toHaveLength(3);
    });
  });
```

This could result in firing a click event on the submit button multiple times.

I recommend that you remove all usages of `wait` and only use `waitFor` when you actually need to wait for things. In addition, I'd suggest using `find*` queries over `waitFor` where possible.

If you have trouble with that, please get help by following the instructions in https://kcd.im/rtl-help

Good luck!

**Comment by lifeiscontent** [comment]
Oh Wow, @kentcdodds I had no idea this API even existed `screen` this makes it much cleaner. Thank you.

Is there a place in the docs that show some common test cases in React? I think that would be helpful if it currently doesn't exist.

**Comment by lifeiscontent** [comment]
@kentcdodds that still didn't seem to solve my issue, from a few articles I've seen on the web, it also seems that a lot of people are not sure how to test formik in RTL.

Here's my example: https://codesandbox.io/s/intelligent-diffie-7j8fq

articles I came across:

- https://timonweb.com/tutorials/how-to-test-if-element-existsdoesnt-exist-with-jest-and-react-testing-library/
- https://dev.to/charlespeters/formik-react-testing-library-and-screaming-at-a-computer-for-an-hour-5h5f

**Comment by lifeiscontent** [comment]
I seemed to have fixed my issue, does this look correct @kentcdodds ? https://github.com/lifeiscontent/realworld/blob/master/web/src/components/article-form/index.spec.js

**Comment by kentcdodds** [comment]
Close! The last waitFor should either be removed or it should wrap the assertion and not the click
