### ISSUE TITLE
TypeScript definitions missing waitFor

### ISSUE THREAD

**Issue by NiGhTTraX** [testing-library/dom-testing-library#486]
- `dom-testing-library` version: 10
- `node` version: 12.16.0
- `yarn` version: 1.22

Relevant code or config

```ts
import { waitFor } from '@testing-library/dom';
```

What happened:

```
TS2305: Module '"../../../node_modules/@types/testing-library__dom"'
has no exported member 'waitFor'.
```

Problem description: saw the deprecation warnings after upgrading to latest version, tried to take the action suggested in the message, ran into this problem.

Suggested solution: add the type in [testing_library__dom](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/32ea5fc74dfc237ad888790bff9e767f6677e7d4/types/testing-library__dom)?

**Comment by eps1lon** [comment]
Already in the pipeline over at `@types/`: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43102

**Comment by NiGhTTraX** [comment]
Thanks!

**Comment by davidgilbertson** [comment]
While you're waiting, you can drop this into your own project to extend the existing definitions.

```ts
declare module '@testing-library/dom' {
  export function waitFor(
    callback: () => void,
    options?: {
      container?: HTMLElement;
      timeout?: number;
      interval?: number;
      mutationObserverOptions?: MutationObserverInit;
    },
  ): Promise<void>;
}
```

Definition copy/pasted from @abraham's PR linked above.
