### ISSUE TITLE
waitForElementToBeRemoved is not expecting params on TS

### ISSUE THREAD

**Issue by MuraraAllan** [testing-library/dom-testing-library#490]
- `DOM Testing Library` version:
- `node` version:
- `npm` (or `yarn`) version:

### Relevant code or config:
```const [
  queryByPlaceholderText,
  getAllByPlaceholderText,
  getByPlaceholderText,
  findAllByPlaceholderText,
  findByPlaceholderText,
] = buildQueries(queryAllByPlaceholderText, getMultipleError, getMissingError)
looks like this abstraction is confusing TS, not sure although
```
```js
await waitForElementToBeRemoved(getByPlaceholderText(t('auth.signin.fields.email.placeholder')) as any)
```

### What you did:
 
I'm using typescript and testing-library, when trying to wait for an HTML Element to be removed, I need to pass hard-coded ```any``  type to the element,  otherwise Typescript is gonna validate an invalid argument for the function.

### What happened:

Argument of type 'HTMLElement' is not assignable to parameter of type '() => unknown'.
  Type 'HTMLElement' provides no match for the signature '(): unknown'.ts(2345)

**Comment by timdeschryver** [comment]
This will get resolved when `@types/`: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43102 gets merged.

If this is not the case, feel free to re-open this issue.
