### ISSUE TITLE
Utilities for dispatching events?

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/dom-testing-library#5]
I'm thinking there could be room for a utility for dispatching events in elements. Similar to react's test utils Simulate utilities except with actual browser events. What should the API look like?

**Comment by kentcdodds** [comment]
I also prefer the former option. But let's call it `fireEvent` rather than `Simulate`:

```javascript
fireEvent.click(domNode)
// the `change` event in react is actually the `input` event.
// the actual change event only fires on blur for inputs
// https://developer.mozilla.org/en-US/docs/Web/Events/change
// https://developer.mozilla.org/en-US/docs/Web/Events/input
// we'll need to document this in react-testing-library with big bold letters.
fireEvent.input(
  document.querySelector('input[name="username"]'),
  {target: {name: 'username', value: '1234'}}
)
```

If we can find a module with list of all events that would be super. Then we could use that to generate these.

Alternatively, we could use a Proxy, which would probably be really handy. That actually could be preferable... 🤔

**Comment by kentcdodds** [comment]
Thanks @antoaravinth. That wont quite be enough because it doesn't allow you to specify custom options (as in the `fireEvent.input` call.

**Comment by jomaxx** [comment]
@kentcdodds so funny story. i literally worked on a similar library last week and just found out about your project https://github.com/jomaxx/react-dom-test-env. I have a `simulate` utility that I started which does real DOM events with some sane defaults https://github.com/jomaxx/react-dom-test-env/blob/master/src/simulate.js. I'm happy to contribute it to this project.

I also have a `debug` helper that pretty prints a dom tree in an error message https://github.com/jomaxx/react-dom-test-env/blob/master/src/debug.js

let me know if i can help

**Comment by kentcdodds** [comment]
Oh hey! That's so cool @jomaxx! I'd love to join forces! How would you like to make a PR that adds your simulate functionality to this library? I think it'll need a few changes (change it from `simulate` to `fireEvent` and allow for passing additional properties for the event), but it's pretty close to what I was hoping for!

About the `debug` helper, @antoaravinth is working on adding that by default for errors in #3. I'm thinking that'll probably be enough for now. Thanks so much! This is great!

It's validating to me that you were working on something similar recently @jomaxx! I hope we can work together to make testing React (and DOM related stuff in general) really awesome!

**Comment by jomaxx** [comment]
@kentcdodds will do!

**Comment by igomezal** [comment]
Maybe you could also use something like: https://github.com/PolymerElements/iron-test-helpers
