### ISSUE TITLE
Query getByRole("textbox") stopped working for input of type file.

### ISSUE THREAD

**Issue by afmfe-iul** [testing-library/dom-testing-library#500]
- `@testing-library/jest-dom` version: 4.1.1
- `@testing-library/react` version: 9.5.0
- `node` version: 10.17.0
- `yarn` version: 1.22.0

### What happened:

After upgrading `@testing-library/react` version: 9.5.0 the test given in the bellow codesandbox started failing. 

### Reproduction:

https://codesandbox.io/s/react-testing-library-getbyrole-demo-c6dvr

### Problem description:

The test now fails with the following error:
`Unable to find an accessible element with the role "textbox"`

The fix suggested in this issue https://github.com/testing-library/react-testing-library/issues/606 is to add `type=text` to the input, but in my case I'm already using `type=file`.

Also, I'm not sure if `getByRole` is the correct query to use in this scenario. I managed to fix the test for now by using `container.querySelector("input")` instead. Let me know if this isn't the right approach, thanks!

**Comment by eps1lon** [comment]
Thanks for opening this issue and filling out the template.

Unfortunately this is expected. [`<input type="file" />`](https://www.w3.org/TR/html-aam-1.0/#details-id-60) has no corresponding role. `container.querySelector` is a possible fallback (or ByTestId).

**Comment by DanielGibbsNZ** [comment]
I've noticed the same issue with `type="password"`.

**Comment by kentcdodds** [comment]
Yep, for these types of generic inputs it's best to use `*ByLabelText`
