### ISSUE TITLE
expecting rgba format color getting in #

### ISSUE THREAD

**Issue by MuraraAllan** [testing-library/dom-testing-library#501]
```
const { getByText, findAllByText, getByTestId } = render(
      <ThemeWrapper>
        <VerificationStatusInner i18n={i18n} tReady={true} t={t} tier={1} type={'success'} />
      </ThemeWrapper>)  
    const element = getByTestId('successFaIcon')
    expect(element).toHaveStyle({
      color: theme.Green02
    })
```

I'm trying to expect the color to be my theme color ( expressed in RGBA ) although when rendering the dom assigns #69CB0A instead of RGBA.
I want to test using the same schema as my themes.

```        memoizedProps:
          { 'aria-hidden': 'true',
            focusable: 'false',
            'data-prefix': 'fas',
            'data-icon': 'check-circle',
            className: 'svg-inline--fa fa-check-circle fa-w-16 ',
            role: 'img',
            xmlns: 'http://www.w3.org/2000/svg',
            viewBox: '0 0 512 512',
            style: {},
            'data-testid': 'successFaIcon',
            color: '#69CB0A',
            children: [Object] },
         updateQueue: null,
```

- `DOM Testing Library` version:
- `node` version:
- `npm` (or `yarn`) version:

### Relevant code or config:

```js
var your => (code) => here;
```

**Comment by eps1lon** [comment]
This is how `color` is computed. Might be a bit hard to understand but it's specified in the [css-color spec](https://drafts.csswg.org/css-color/#resolving-color-values).

It might actually be better to assert th rgb calue since that is robust to changes to the color format you use (e.g. named or hex).
