### ISSUE TITLE
Narrowing TS types after `toBeInTheDocument` call.

### ISSUE THREAD

**Issue by afmfe-iul** [testing-library/dom-testing-library#502]
### Describe the feature you'd like:

As a Typescript user of the library and given the following code:
```js
// inputElement is of type `HTMLInputElement | null`
const inputElement = container.querySelector("input"); 
expect(inputElement).toBeInTheDocument();

// I'm assuming that since `toBeInTheDocument()` didn't throw from  now on
// `inputElement` should be of type `HTMLInputElement`, is this assumption correct?

// I get TS errors on inputElement
expect(inputElement.id).toMatch(inputLabel.id); // Object is possibly 'null'.
// (...)
fireEvent.change(inputElement); // Type 'null' is not assignable to type ...
```
I'm wondering if it would be possible to, after performing `toBeInTheDocument`, narrow the type of the argument passed in the respective `expect` from `T | undefined | null` to `T`.

The alternative solution I'm using at the moment is adding:
```js
if (!inputElement) {
   throw new Error("Couldn't find the input element.");
}
```
Which seems redundant after doing `expect(inputElement).toBeInTheDocument()`.

### Suggested implementation: 
I'm not sure if what I'm suggesting is even doable, I looked a bit at the code and it seems that jest expects a specific return type from extended matchers, so something like [type predicates](https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates) wouldn't work?

**Comment by eps1lon** [comment]
This is possible with [assert functions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions) in TypeScript 3.7. 

Either way: Please open a [new issue in the types repository](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/new). This repository does not own the types.

**Comment by afmfe-iul** [comment]
Thanks again for the quick answer @eps1lon 🙂

**Comment by tremby** [comment]
To save the next person the search, the ticket opened is this: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/43421

**Comment by MatanBobi** [comment]
Thanks @tremby!
I'm moving this to `jest-dom` since it relates to that library and not directly to dom-testing-library :)
