### ISSUE TITLE
Button element - Default (native) behavior

### ISSUE THREAD

**Issue by archik408** [testing-library/dom-testing-library#517]
- `DOM Testing Library` version: 6.11.0
- `node` version: 12.12.0
- `yarn` version: 1.19.1

### Relevant code or config:
```js
// It's very rough example
expect.extend({
  toBeAccessibleFromKeyboard (received) {
    received.focus();
    expect(received).toHaveFocus();
    const tempCallback = received.onclick;
    received.onclick = jest.fn();

    fireEvent.keyDown(received, { key: 'Enter', keyCode: 13 });
    fireEvent.keyDown(received, { key: 'Space', keyCode: 32 });
    fireEvent.click(received);
    expect(received.onclick).toHaveBeenCalledTimes(1);

    received.onclick = tempCallback;
    return {
      pass: true,
      message: `Expected ${received} is accessible from keyboard`
    };
  }
});
```

### What you did:
Often, someone can use a styled `div` with an `onclick` callback instead of a `button`. This is not so bad, but in this case, he should add `tabIndex` - to make `div` focusable, and keyboard events to handle `Enter` and `Space`, because it's standard behavior for buttons - trigger `onclick` event by `Space/Enter` keys.

I have some custom matcher for checking that element is accessible from the keyboard. But I have a problem with the button tag. If someone uses button then he do not implement keyboard event handlers cuz this behavior by default.

### What happened:

So, in this case my matcher failing because instead of 3 mock calls I get 1 call.

```js 
expect(received.onclick).toHaveBeenCalledTimes(3); // will be only 1 if you put only onclick event handler to the button tag.
```

### Suggested solution:
I am not sure is it correct, but can we trigger `onclick` handler by `fireEvent.keyDown` in case if the element is `button` and key is `Space` or `Enter` - it's closest to the native button behavior. I think this idea we can extend for other native elements.

**Comment by eps1lon** [comment]
Thanks for the detailed issue and code examples! 

Why could you not check this in your matcher? Expect 1 if `received.tagName === "button"` or `3` otherwise. 

If we would dispatch a click event on keydown then we wouldn't correctly display how a user would interact with your component.

Also: Your matcher is incorrect. Click is fired on keyup for Space not keydown. Space and Enter behave differently for buttons and anchors.

**Comment by archik408** [comment]
Thanks for answer! 
Yep, I think you are right and I can add few conditions to the matcher. And thanks for correction.
