### ISSUE TITLE
container.querySelector always returns null

### ISSUE THREAD

**Issue by mhuggins** [testing-library/dom-testing-library#518]
- `DOM Testing Library` version: 7.0.3
- `node` version: 10.19.0
- `npm` (or `yarn`) version: npm 6.13.4

### Relevant code or config:

```js
const { container, debug } = render(<FormModal isOpen />);
const el = container.querySelector(selector);

console.log(document.querySelector('div'));
// => HTMLElement< ...snip... >

console.log(el.querySelector('div'));
// => null

debug();
// => <div> ...snip... </div>
```

### What you did:
Using `@testing-library/react`, I'm attempting to use the `container` object returned by the `render` function to query for an ambiguous DOM element.

### What happened:
Unfortunately, `querySelector` *always* returns `null` no matter what selector I pass to it.  However, if I use `document.querySelector`, it works as expected.

### Problem description:
The provided documentation doesn't match what is necessary to make this work.

### Suggested solution:
Fix it somehow, but I'm not sure why it's not working.  The `getByXXX` functions being returned by the `render` function work as expected.

**Comment by eps1lon** [comment]
We'd need the full example to understand the issue. But considering you're rendering a modal the element you want to query is probably inside a react portal. It is expected that querySelector would return null if the element is portaled to another part of the tree.

**Comment by alexkrolick** [comment]
You probably want to use the `screen` import which is bound to the document body, instead of the `container`

**Comment by kentcdodds** [comment]
And if you *really* can't use one of the queries exported by `screen` (it's strongly recommended that you do), then you can use `document.querySelector`.

With that, I think we can close this. Thanks!

**Comment by alexkrolick** [comment]
That said, I though `container` was bound to the document body already? https://github.com/testing-library/react-testing-library/issues/392
