### ISSUE TITLE
Documentation for waitFor() should explain how to replace existing wait() calls

### ISSUE THREAD

**Issue by timrobinson33** [testing-library/dom-testing-library#519]
I see that that wait() has been deprecated and the documentation simply says to use waitFor instead but doesn't explain how.

I have been using `waitFor( () => {} )` which seems to work. if this is the "official" way to do it, it would be nice to put that in the docs.

**Comment by kentcdodds** [comment]
Hi @timdeschryver,

The docs are here: https://testing-library.com/docs/dom-testing-library/api-async#waitfor

How do you think that could be improved?

It's not recommended to have an empty callback (which is why that's not in the docs). If that "fixes" your tests, it's incidental. You should include an assertion in the callback.

**Comment by timdeschryver** [comment]
Forwarding to @timrobinson33

**Comment by kentcdodds** [comment]
Lol, sorry about that.

**Comment by timrobinson33** [comment]
As far as I understand, the old wait() is the equivalent to having an empty callback, so since it wasn't deprecated before, there will be people (like me) who have existing empty wait() calls in their existing tests. When they upgrade, they see that it's deprecated but it's not clear what to replace it with because an empty `waitFor()` doesn't work.

So I think there should at least be a note saying it's no longer recommended to have an empty callback, and maybe that if you really can't think of a better way you should use `waitFor( () => {})`.

**Comment by timrobinson33** [comment]
OK I think I've done it, sorry this is my first time contributing on github so let me know if I've got it  wrong

https://github.com/testing-library/testing-library-docs/pull/432

**Comment by kentcdodds** [comment]
Thanks!
