### ISSUE TITLE
Build failure on Node 10

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/dom-testing-library#521]
As noted here: https://github.com/testing-library/dom-testing-library/pull/520#issuecomment-609961780

![image](https://user-images.githubusercontent.com/1500684/78592280-1709b000-7802-11ea-8ed3-23259100c5a6.png)

```
[test]  FAIL   node  src/__node_tests__/index.js
[test]   ● Test suite failed to run
[test] 
[test]     ReferenceError: BigInt is not defined
[test] 
[test]       at createLongLongConversion (node_modules/webidl-conversions/lib/index.js:162:51)
[test]       at Object.<anonymous> (node_modules/webidl-conversions/lib/index.js:224:24)
[test]       at Object.<anonymous> (node_modules/jsdom/lib/jsdom/browser/Window.js:3:27)
[test] 
```

I have no idea why that's happening. I'm guessing that we've got a devDependency that does not support Node 10. This is unfortunate and I'm kinda thinking the easiest solution is to just drop Node 10 from CI and hope we don't ever ship anything that breaks Node 10... 😬 That said, Node 10 doesn't get EOL until mid-2021 (and that's how long I think we should support it) so it may be better to find another solution to this.

Any ideas?

**Comment by eps1lon** [comment]
This looks like it originates from jsdom. Would be nice to isolate that to a minimal example just using JSDOM.

**Comment by alexkrolick** [comment]
Looks like this commit changed webidl to use BigInt https://github.com/jsdom/webidl-conversions/commit/d610eb656f36b7447953bf385d36cf3777f440ba 

Node 10.4.0+ supports it, maybe we can just update the lts/dubnium version? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by MichaelDeBoey** [comment]
After some investigation in https://github.com/testing-library/dom-testing-library/pull/525#issuecomment-612422897, I [reported](https://github.com/jsdom/jsdom/issues/2941) this upstream.

This was [answered](https://github.com/jsdom/jsdom/issues/2941#issuecomment-612444907) by @TimothyGu:
> Let’s call this a duplicate of [#2939](https://github.com/jsdom/jsdom/issues/2939).
> 
> I’m inclined to say that it’s your own responsibility to use the latest branch release, especially for LTS branches. Considering jsdom often uncover bugs in Node.js that get fixed in a bugfix release, I don’t know if we can ever “support” an ancient pre-LTS LTS branch release – especially not a *.0.0 release 2 years after its release. It is unfortunate that the changes slipped by without a major bump though.

**Comment by alexkrolick** [comment]
> I think we should bump our minimum supported Node version back to 10.18, like we did before d2885c9

That commit is pretty new (Mar 13, 2020), so the number of packages that would have gotten a warning when installing between then and now, but did not because of the lowered version, should be pretty small. To actually experience an issue, they would also have had to have installed a version of JSDOM higher than [16.2.2](https://github.com/jsdom/jsdom/commit/fe164b3b39f61846193b1f2d06ef7c27da554ebf), which was released on Jan 28, 2020. Jest 25 still installs JSDOM 15 by default.
