### ISSUE TITLE
<input type="password" /> should not be query-able `byDisplayValue`

### ISSUE THREAD

**Issue by bkong88** [testing-library/dom-testing-library#527]
### Describe the feature you'd like:

When testing an input of type `'password'`, the user should not be able to `queryByDisplayValue` the actual value in the input element. Instead, if the user tries to `queryByDisplayValue` the value in the input element, it should return null. And if the user tries to `queryByDisplayValue` the actual number of asterisks or dots shown on a regular browser, the input element is returned.

Example:
```javascript
render(<input type="password" />)
await userEvent.type("password")
expect(screen.queryByDisplayValue("password")).toBeFalsy() // Actual result: truthy
expect(screen.queryByDisplayValue("********")).toBeTruthy() // Actual result: falsy
```

The reason for implementing this feature is because of the [guiding principles of testing-library](https://testing-library.com/docs/guiding-principles), which state that we should:   

> expose methods and utilities that encourage [one] to write tests that closely resemble how [one's] web pages are used

As such, if a test developer tries to test functionality of a `show` / `hide` button of a password input component, the only way for the developer to test that is to check if the input prop has properly changed to `type="password"` when hidden, and check if the input component has props of `type="text"` if showing value. However, that goes against the guiding principles as that would be testing implementation details.

### Suggested implementation:

Currently `src/queries/display-value.js` only checks if the component is of `tagName === "SELECT"`. We can add an additional check for if it is `tagName === "INPUT" && type === "password"`.
Example:  

```javascript  
if ( ... ) { ... }
else if (node.tagName === "INPUT") {
  if (node.type === "password") {
    return matcher("*".repeat(node.value.length), node, value, matchNormalizer)
  }
} else { ... }
```  

This will only return a match if the user passed the correct number of asterisks to the `byDisplayValue` function, all other cases will not be matched as the user technically only sees that many number of asterisks on the screen.

### Describe alternatives you've considered:

Alternatively, instead of only returning a `matcher()` for asterisks (`*`), we can add another matcher for dots (`•`) since Mozilla states [either the asterisk or the dot are the most commonly used characters](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password) to replace a password input's characters. eg. `return matcher("*".repeat(node.value.length), node, value, matchNormalizer) || matcher("•".repeat(node.value.length), node, value, matchNormalizer)`

### Teachability, Documentation, Adoption, Migration Strategy:

Users can use this feature when testing a `show` / `hide` button of an input component.  
If mods approve this feature, I can push PRs for this ticket.

**Comment by kentcdodds** [comment]
Hi @bkong88,

Thanks for the issue.

At a certain point, I think it's ok to rely on browser semantics. Even though it's *technically* implementation details to check the `type` of the input, I'm comfortable with it because I'm relying on the browser to treat that properly and implementing this myself in a different way would likely lead to a worse user experience.

Also, I would argue that counting the `*` or `•` would be more implementation details focused anyway because there's no browser specification for how they display these (or what characters they display).

So my opinion of this is to not make any changes. Open to hear other's thoughts.

**Comment by gautamkrishnar** [comment]
IMO it doesnt matter, we use testing library only for testing stuff, not to be used on production or anything as a library. So its okay to have this rather than removing it.
