### ISSUE TITLE
Unexpected Behaviour - Renderer and Async Setup causes two renders in DOM

### ISSUE THREAD

**Issue by isaacrowntree** [testing-library/dom-testing-library#529]
Versions:
```
    "@testing-library/jest-dom": "5.5.0",
    "@testing-library/react": "10.0.3",
    "jest": "25.4.0",
```

As part of my test suite I had to set up 

```
import { MockedProvider } from '@apollo/react-testing';
import { Provider } from 'react-redux';
...

const allTheProviders = ({ children }) => (	
  <MockedProvider mocks={[]} addTypename={false}>	
    <IntlProvider locale={locale}>	
      <Provider store={store}>	
        { children }	
      </Provider>	
    </IntlProvider>	
  </MockedProvider>	
);
```

All well and good, the test setup just needs a renderer to give it the component to be tested. So: 

```
  const customRender = async (ui, options) => {
    let rendered = '';
    await act(async () => {
      rendered = await render(ui, { wrapper: allTheProviders, ...options });
    });
    return rendered;
  };
```

This seems rather wasteful and a little bit over the top. So I refactored:

```
const customRender = (ui, options) => {	
  return waitFor(() => render(ui, { wrapper: allTheProviders, ...options }));	
};
```

This broke, big time! I was getting two versions of the rendered DOM appended one after another (seemingly randomly in my single test suite, probably based on seed numbers for Jest). This would also be really flaky and work sometimes and not others in CI, depending on where in our test suite of 268 test groups the test would be run. 

I don't know why one version of my customRender func would work and the other wouldn't, other than that one explicitly enforces a torn-down customRender var (`rendered`). The other thing that didn't work (I'm running the latest react testing library) is obviously the `cleanup` function. That seemed to do nothing (probably as it should).

The actual error I was getting was just simply that doing getByText would fail because of the doubled-up DOM because there would be two matches, not one. So I reverted back to my initial customRender code and all was well. Leaving this here for posterity.

**Comment by kentcdodds** [comment]
Yeah, your custom render should probably just be:

```javascript
const customRender = (ui, options) => {
  return render(ui, {wrapper: allTheProviders, ...options})
}
```

No reason to make it all async like you had there...
