### ISSUE TITLE
Build: umd build invalid if the define method exists on the browser page

### ISSUE THREAD

**Issue by Dolinskaya** [testing-library/dom-testing-library#533]
I encountered this when I tried to connect the testing-library/nightwatch into my tests.
There is my simple test example:
```js
const { getQueriesFrom } = require("@testing-library/nightwatch");

module.exports = {
  beforeEach(browser, done) {
    browser.url("https://tutu.ru/poezda");
    done();
  },
  async myFunc(browser) {
    const { queryAllByText } = getQueriesFrom(browser);

    await queryAllByText("Войти");
  },
};

```

And now I've got an error:
`Cannot read property 'queryAllByText' of undefined`
After some research, I was able to find what testing-library/nightwatch inject into browser page next script:
https://github.com/testing-library/nightwatch-testing-library/blob/master/src/index.js#L18

Where is DOM_TESTING_LIBRARY_UMD path like `dist/@testing-library/dom.umd.js`. This script added into global window object define TestingLibraryDom, that uses there https://github.com/testing-library/nightwatch-testing-library/blob/master/src/index.js#L56 and there https://github.com/testing-library/nightwatch-testing-library/blob/master/src/index.js#L62.

So, I had a question: "Why TestingLibraryDom didn't add into browser"?
Answer for this question - incorrect build in dom.umd.js. Because, now it startes with:
```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
  typeof define === 'function' && define.amd ? define(['exports'], factory) :
  (global = global || self, factory(global.TestingLibraryDom = {}));
}(this, (function (exports) {...}
```
And so my page have define metod in global - TestingLibraryDom was registered as module.

The solution for my case:
In order for this script to work correctly, I need the build to look something like this:

```js
//dist/@testing-library/dom.umd.js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
  global || self ? (global = global || self, factory((global ? global : self).TestingLibraryDom = {})) :
  define(['exports'], factory)
}(this, (function (exports) {...}
```

- `DOM Testing Library` version: ^6.3.0
- `node` version: 10.17.0
- `npm` (or `yarn`) version: npm@6.11.3

**Comment by kentcdodds** [comment]
Hmmm.... We're using a pretty standard UMD build via rollup. I think if you need it to be different you'll need rollup to change their format. I don't have much control over that output from outside rollup.

**Comment by Dolinskaya** [comment]
Oh, okay. I thought it will be possible via something rollup plugins, but, perhaps, I'm mistook.
So, today, I found an another way for resolve my issue, that's not so beautiful, but it is works :)
```js
const { getQueriesFrom } = require("@testing-library/nightwatch");

module.exports = {
  beforeEach(browser, done) {
    browser.url("https://tutu.ru/poezda");
    done();
  },
  "Hello world": async function (browser) {
    browser.execute(function () {
      setTimeout(() => {
        window.define = null;
      }, 0);
    });

    const { getAllByText } = getQueriesFrom(browser);

    const links = await getAllByText(/Войти/);
    browser.expect.elements(links).count.to.equal(2);
  },
};
``` 
Before using the testing-library selectors, I removed define function from global and now TestingLibraryDom is adding into global window object.
