### ISSUE TITLE
Improve error stack traces for async errors

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/dom-testing-library#539]
Here's the stack trace I get:

```
      at Object.getElementError (node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/config.js:30:19)
      at node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:76:38
      at node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:59:17
      at node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:86:84
      at checkCallback (node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/wait-for.js:56:22)
```

Here's the line of code that caused the error:

```javascript
await screen.findByRole('heading', {name: /example/i})
```

I think rather than a stacktrace in the `@testing-library` code, we should give them an error that has the stacktrace in their own code. Similar to what we do for [timeout errors](https://github.com/testing-library/dom-testing-library/blob/9007a673a138a50becd764c58d08c28477bcfc33/src/wait-for.js#L29-L30).

Kinda thinking it could be as simple as changing this:

https://github.com/testing-library/dom-testing-library/blob/9007a673a138a50becd764c58d08c28477bcfc33/src/wait-for.js#L65-L67

to:

```javascript
function onTimeout() {
  let error = timedOutError
  if (lastError) {
    error = lastError
    const userStackTrace = timedOutError.stack.split('\n').slice(1).join('\n')
    error.stack = `${error.stack.split('\n')[0]}\n${userStackTrace}`
  }
  onDone(error, null)
}
```

Technically we do lose some information with this, but I'm pretty sure it's information worth losing. Thoughts?

**Comment by alexkrolick** [comment]
Good idea, it's pretty useless to get a stack trace into the library

**Comment by eps1lon** [comment]
> Good idea, it's pretty useless to get a stack trace into the library

If we assume that we're bug free, sure. But I think we should still have the opportunity to print the whole stack trace. Otherwise debugging can become an issue.

**Comment by kentcdodds** [comment]
I agree, any ideas on how to do that? We could combine the stack traces I guess.

**Comment by eps1lon** [comment]
> I agree, any ideas on how to do that?

Add a config option `showFullStackTrace` and don't mutate the stack if it is true?

**Comment by kentcdodds** [comment]
That sounds good to me 👍 Though "full" doesn't seem like the right word. Maybe `showOriginalStackTrace` is better?

**Comment by Attrash-Islam** [comment]
I really considered doing so in my `react-fp-context` library when use `console.trace` to show execution flows when updating the state.. but what if your user executed things from a series of stacked functions? I think they'll lose that with the `slice` thing and showing them the whole path would make their life easier.
