### ISSUE TITLE
findByRole - document ignored

### ISSUE THREAD

**Issue by alex-vukovity-cko** [testing-library/dom-testing-library#549]
![image](https://user-images.githubusercontent.com/57100733/81214642-0ea6bf80-8fd0-11ea-8269-c4ab59734dfd.png)

Unable to find role "document" and then logs out a list of available roles and clearly shows there is "document".
What gives?

Thank you

**Comment by eps1lon** [comment]
Please follow the issue template. More specifically, include the code that lead to this error and ideally provide a https://codesandbox.io.

**Comment by alex-vukovity-cko** [comment]
```
test('should simulate network failure on mount', async () => {
  useJestFetch.reject();

  render(<MyScreen />);

  await screen.findByRole('document');

  expect(screen.queryByRole('main')).not.toBeInTheDocument();
  expect(fetch).toHaveBeenCalledWith(getUrl);
  expect(fetch).toHaveBeenCalledTimes(1);

  useJestFetch.restore();
});
```

This fails with the error in the screenshot above. But it's not only this test case. In every test case where I try to `findByRole('document');` it fails to find it and then proceeds to log out a list where it says there is "document" role. It's contradicting itself

Any other role such as "article" "button" "main" works fine as expected.

To me, it seems like, "document" is not even findable and yet it is listed under the list of findable roles.

P.S.
When i replace `findByRole('document');` with `  await wait();` the test case passes.

**Comment by eps1lon** [comment]
I suspect we query down from `document.body` but log roles including `document.body`. The question is: Do we log down from `document.body` or do we include `document.body` in the query?

**Comment by eps1lon** [comment]
What I don't understand: How would this even work that `MyScreen` removes the document in which it should be rendered?

**Comment by alex-vukovity-cko** [comment]
I doubt it removes it. It wouldn't add up. From what I gather "document" in this case represents `<body>` element, and in the screenshot we can see that `<body />` in fact did render and exists.
I think it's even safe to say "document" role = `<body />`

What it seems to me is that "document" is not findable just like e.g. `findByRole("form")` is not findable (unless `role` attribute is defined on `<form />`)

Are you positive "document" is in fact a role that could be found by `findByRole`? 
It could be that, "document" only shows up on the list but its not actually a role.

> Do we log down from document.body or do we include document.body in the query?

According to that console-logged list, we do include it, but the list could be wrong, as in not representing actual findable roles

**Comment by eps1lon** [comment]
>  doubt it removes it. It wouldn't add up. From what I gather "document" in this case represents <body> element, and in the screenshot we can see that <body /> in fact did render and exists.

Then why do you query for it? I don't understand what `await screen.findByRole('document');` does for you.

> What it seems to me is that "document" is not findable just like e.g. findByRole("form") is not findable (unless role attribute is defined on <form />)

A `<form />` requires a name to have the `form` role e.g. `<form aria-label />`.

**Comment by eps1lon** [comment]
Doesn't really matter what role we're talking about. The current error message is misleading since we never included the container in the list of available roles. #550 fixes this issue.

**Comment by alex-vukovity-cko** [comment]
![image](https://user-images.githubusercontent.com/57100733/81224441-9ba54500-8fdf-11ea-9d2f-7a59abd85a65.png)

In another test case, I have a pop-up toaster component that I would like to test for rendering.

In the screenshot, it can be seen that the component renders as a direct child of  `<body />` 
One way to test it, is to `findByRole( "document")` and then `toHaveTextContent('something')`
and this doesn't work as "document" can't be found as a role even though according to the logged out list, it should be.

Of course there are alternatives to test this component, like data-testid, which is what I am doing, becuase "document" thing doesn't work and this is why I posting here

> Then why do you query for it? I don't understand what await screen.findByRole('document'); does for you.

According to the console-logged list of available roles, it is a legimite way to test something so why not use it

**Comment by alex-vukovity-cko** [comment]
> Doesn't really matter what role we're talking about. The current error message is misleading since we never included the container in the list of available roles. #550 fixes this issue.

Ok, that settles it then. Thanks.
