### ISSUE TITLE
getByRole's error message is incorrect on button with role "tab"

### ISSUE THREAD

**Issue by mattstobbs** [testing-library/dom-testing-library#553]
- `DOM Testing Library` version: 5.5.0
- `node` version: 13.12.0
- `npm` (or `yarn`) version: 1.22.4

### Relevant code or config:

```js
import React from 'react';
import { render, screen } from '@testing-library/react';

const Button = () => <button role="tab" aria-label="my-button" />;

test('button exists', () => {
  render(<Button />);

  screen.getByRole('button', { name: 'my-button' });
});
```

### What happened:

The test (correctly) failed because it could not find an element with the role of button (the button has a role of "tab"). However, when the error message listed the accessible roles, it listed the button's role under "button":

    TestingLibraryElementError: Unable to find an accessible element with the role "button" and name "my-button"

    Here are the accessible roles:

      document:

      Name "":
      <body />

      --------------------------------------------------
      button:

      Name "my-button":
      <button
        aria-label="my-button"
        role="tab"
      />

### Reproduction:

[Code Sandbox](https://codesandbox.io/s/react-testing-library-demo-pvsse?file=/src/__tests__/button.js)

### Problem description:

The current behaviour is confusing because the error message says there is no element with the role of "button" and then shows that there is an element with the role of "button".

### Suggested solution:

Buttons with other roles (e.g. [tab](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role)) should be shown under their correct roles in the error message.

I'm happy to put up a PR for this but would need pointing in the right direction as I'm unfamiliar with the code 😁

**Comment by eps1lon** [comment]
Thanks for the report. That is indeed weird.

You should start with adding a test to src/__tests__/role.js. The code for ByRole lives in src/queries/role.js.

**Comment by mattstobbs** [comment]
It looks like there are actually 2 issues here.

The first is the library [aria-query](https://github.com/A11yance/aria-query), which we're using to get a map of the elements to their possible roles. Under [elementRoles](https://github.com/A11yance/aria-query#elements-to-roles), the button element only has the role "button". This would need to be extended to include other roles, such as tab.

The second is that the [matches](https://github.com/testing-library/dom-testing-library/blob/a03f05671f849802c2d890e6de4532fb6b52f28c/src/matches.js#L16) function correctly determines that `<button role="tab />` has the role of tab, but [`currentNode.matches`](https://github.com/testing-library/dom-testing-library/blob/752ff667d52efd452273232a6a48319a207c66c2/src/role-helpers.js#L68) determines the node has the role of button. Do you know where that is defined?

**Comment by mattstobbs** [comment]
Just dug a bit more into this. [`currentNode.matches`](https://github.com/testing-library/dom-testing-library/blob/752ff667d52efd452273232a6a48319a207c66c2/src/role-helpers.js#L68) returns true for the selector "button" because it is a button. The way this is handled in the aria-query library is to have more specific selectors first, so they will match first (i.e. the button would match with `button[role="tab"]` before it matches with `button`).

Therefore, the solution would be to put up an issue and PR in the aria-query library, and once that is merged, update the version used by dom-testing-library. If you're happy with that, @eps1lon, I can go ahead and do that.

**Comment by eps1lon** [comment]
Great investigation! We do sort by specificity: https://github.com/testing-library/dom-testing-library/blob/429de04d023f2c49af2cb7b10d6daa537d417999/src/role-helpers.js#L118. I think we just need to refine the logic so that an explicit "role" has the highest specificity: https://github.com/testing-library/dom-testing-library/blob/429de04d023f2c49af2cb7b10d6daa537d417999/src/role-helpers.js#L92-L94

**Comment by mattstobbs** [comment]
That would make sense. It looks like that logic is still manipulating the map from aria-query, so it still wouldn't include `button[role="tab"]` because that library doesn't include it?

**Comment by eps1lon** [comment]
`aria-query` definitely includes `tab`.

**Comment by mattstobbs** [comment]
When I `console.log(elementRoleList)`, which is the output of 

https://github.com/testing-library/dom-testing-library/blob/429de04d023f2c49af2cb7b10d6daa537d417999/src/role-helpers.js#L5

I get the following list: [elementRoleList.txt](https://github.com/testing-library/dom-testing-library/files/4604254/elementRoleList.txt)

which doesn't include tab, or a selector called button[role="tab"]. Am I missing something?

**Comment by anndroow** [comment]
When is this fix coming for https://github.com/testing-library/cypress-testing-library ? ;)
