### ISSUE TITLE
🐛Passing options to a PointerEvent through createEvent doesn't work

### ISSUE THREAD

**Issue by dbismut** [testing-library/dom-testing-library#558]
Hey, I'm maintaining **react-use-gesture** and heavily rely on **testing-library** for tests (thanks so much btw).

I'm planning to move to PointerEvent instead of a mix of TouchEvent and MouseEvent for our drag recognizer. Our set of tests implies creating events that simulate pointer coordinates in the form of `{ clientX: number, clientY: number }`.

- `DOM Testing Library` version: 7.5.1 (from yarn.lock, I'm using @testing-library/react)
- `node` version: 12.16.1
- `yarn` version: 1.22.4

### Relevant code or config:

```js
// this works
const event = createEvent.mouseMove(element, { clientX: 30, clientY: 80 })
console.log(event.clientX) // <-- prints 30

// this doesn't work
const event = createEvent.pointerMove(element, { clientX: 30, clientY: 80 })
console.log(event.clientX) // <-- prints undefined
```

I'll link to a repro as soon as codesandbox works properly.

**Comment by dbismut** [comment]
Sorry, I thought I had identified the problem but it seems more complex than this. I'll reopen when I understand where this comes from.

**Comment by dbismut** [comment]
For reference, this actually comes from here: https://github.com/jsdom/jsdom/pull/2666

**Comment by adamochayon** [comment]
@dbismut I am seeing the same behavior. Is the issue upstream (lack of jsdom support)?

**Comment by dbismut** [comment]
@adamochayon That's my understanding indeed 😕

**Comment by evenmark** [comment]
> I was able to hack around this by adding my own implementation of `PointerEvent` that allows me to pass through the properties I care about for testing on the Event object.
> 
> ```js
> const pointerEventCtorProps = ['clientX', 'clientY', 'pointerType'];
> export default class PointerEventFake extends Event {
>   constructor(type, props) {
>     super(type, props);
>     pointerEventCtorProps.forEach((prop) => {
>       if (props[prop] != null) {
>         this[prop] = props[prop];
>       }
>     });
>   }
> }
> ```
> 
> Then in my test:
> 
> ```js
>  window.PointerEvent = PointerEventFake;
>  fireEvent.pointerDown(myElement, new PointerEventFake('pointerdown', {clientX: 20}));
>  fireEvent.pointerMove(myElement, new PointerEventFake('pointermove', {clientX: 30}));
> ```
> 
> And they get fired and hit as I would expect in my React components.

Adding that to my fireEvent didnt work but adding your class to my setupTests.js file along with
```
global.PointerEvent = PointerEventFake;
```
worked a treat! Thank you!

**Comment by steveruizok** [comment]
Still an issue. That "hack" could make it into the library, I think!

**Comment by dannyharding10** [comment]
I'm not sure this is actually a bug. According to MDN, the `PointerEvent` constructor does not take `clientX` or `clientY` https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/PointerEvent. This is in contrast with the `MouseEvent` constructor, which says it *does* accept clientX and clientY https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent

**Comment by hatpick** [comment]
@dannyharding10 it's not about that:
```typescript
fireEvent.pointerDown(targetBox, { clientX: 0 });
```
element will not receive options passed (e.g., clientX)

**Comment by dannyharding10** [comment]
@hatpick what I’m saying is the options *are* passed to the the PointerEvent constructor, just that `clientX` Is not a valid option for PointerEvent, as you can see here https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/PointerEvent. Try switching to fireEvent.mouseDown with the `clientX` option, use `pointerDown` with one of the options from the mdn docs, such as `pressure`. Either way, you should see that those options are set on the event. This can also be confirmed by looking into the createEvent code, where you will see that the options are passed to the constructor for the Event or PointerEvent

**Comment by hatpick** [comment]
the original concern is that how can one send `clientX` to `pointerDown`, are you saying instead one can do  `fireEvent.mouseDown` and it will be captured by handler defined in `elm.addEventListerner('pointerdown' handler)`?
that's not true.

**Comment by itaylor** [comment]
@dannyharding10 , from the PointerEvent MDN page that you linked:

> options Optional
An object that, _in addition of the properties defined in_ [MouseEvent()](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent), can have the following properties:

My reading of that is that it should support `clientX`, since it is one of the properties of `MouseEvent`.  Do you agree?

**Comment by itaylor** [comment]
@dannyharding10 Yes, the issue in jsdom is here: https://github.com/jsdom/jsdom/pull/2666
Basically it's stuck because there is functionality related to `setPointerCapture` that is non-trivial, difficult to test, and is not currently implemented in jsdom, and they don't want to ship a partial implementation of `PointerEvents` that doesn't support the full spec.  That wouldn't necessarily prevent `dom-testing-library` from adding a workaround though, if the maintainers wanted to.

**Comment by schorfES** [comment]
I'm using this TypeScript "polyfill" in my test setup file based on the initial idea by @jljorgenson18, originally posted here: https://github.com/jsdom/jsdom/pull/2666#issuecomment-691216178.

In my `setup.ts` file:

```ts
class PointerEvent extends MouseEvent {
  public isPrimary: boolean;
  public pointerId: number;
  public pointerType: string;
  public height: number;
  public width: number;
  public tiltX: number;
  public tiltY: number;
  public twist: number;
  public pressure: number;
  public tangentialPressure: number;

  constructor(type: string, params: PointerEventInit = {}) {
    super(type, params);

    // Using defaults from W3C specs:
    // https://w3c.github.io/pointerevents/#pointerevent-interface
    this.isPrimary = params.isPrimary ?? false;
    this.pointerId = params.pointerId ?? 0;
    this.pointerType = params.pointerType ?? '';
    this.width = params.width ?? 1;
    this.height = params.height ?? 1;
    this.tiltX = params.tiltX ?? 0;
    this.tiltY = params.tiltY ?? 0;
    this.twist = params.twist ?? 0;
    this.pressure = params.pressure ?? 0;
    this.tangentialPressure = params.tangentialPressure ?? 0;
  }
}

global.PointerEvent = global.PointerEvent ?? (PointerEvent as typeof globalThis.PointerEvent);
```

Now, I can use it as expected in my tests:

```ts
// In any.spec.ts

fireEvent.pointerMove(target, { clientX: 200, clientY: 60, pointerType: 'mouse' });
```

(I'm sharing this here for anyone else who spends a lot of time searching for a solution, as I did. :wink:)
