### ISSUE TITLE
Follow up: findBy* & findAllBy* generated by buildQueries have wrong argument types for TS

### ISSUE THREAD

**Issue by denysdovhan** [testing-library/dom-testing-library#564]
Opening a new issue as @kentcdodds [asked](https://github.com/testing-library/dom-testing-library/issues/534#issuecomment-626260378).

Follow up for #563 

Please, note that this problem is related to `findBy` and `findAllBy` queries _generated by `buildQueries`_.

**Comment by kentcdodds** [comment]
Sorry to ask you to open this issue, it's probably better to just stick with the one you made originally.

My brain wasn't working properly. Thanks for your patience 😅
