### ISSUE TITLE
Allow installation as a git or github dependency. 

### ISSUE THREAD

**Issue by Raynos** [testing-library/dom-testing-library#565]
### Describe the feature you'd like:

Allow installing the `test-library` modules as a git or github dependency; aka

```sh
raynos at raynos-Precision-5530  
~/optoolco/logs on test-renderer*
$ npm i testing-library/dom-testing-library -S
...
+ @testing-library/dom@0.0.0-semantically-released
updated 1 package and audited 89 packages in 8.921s
raynos at raynos-Precision-5530  
~/optoolco/logs on test-renderer*
$ npm i testing-library/user-event -S
...
+ @testing-library/user-event@0.0.0-development
```

I would like to be able to install the `user-event` and `dom-testing-library` packages as a git or github dependency. This would allow me to install these packages by a branch or a fork + a branch. This is very useful for local development when using temporary feature branches or using bug fixes.

### Suggested implementation:

Check in the source code that is published and included in the `main` target into git. Currently the file `dist/index.js` is missing from the git repository so i cannot require('@testing-library/dom').

One of two options can be used :

 - check `dist` into git.
 - remove babel & `dist` and point `main` at src/index.js and make the source code compatible with npm ; aka replace import/export with CJS and refactor the code to use ES5 instead of babel.js

### Describe alternatives you've considered:

Publish a fork to npm so that i can install a temporary hotfix or bugfix ( like http://npmjs.org/raynos-user-event ).

### Teachability, Documentation, Adoption, Migration Strategy:

This is an optional feature and makes the module "just work" for both `npm install @testing-library/dom` and `npm install test-library/dom-testing-library` ;

**Comment by kentcdodds** [comment]
Hi @Raynos,

I can understand why you'd like to do this. You could actually do this in your own fork (commit `dist` to the repo) and install your fork. We won't do this in the main repo for various reasons mentioned here: https://kentcdodds.com/blog/why-i-dont-commit-generated-files-to-master

Thanks though!
