### ISSUE TITLE
Reduce dependency count

### ISSUE THREAD

**Issue by Raynos** [testing-library/dom-testing-library#566]
# Describe the feature you'd like:

Reduce the number of dependencies installed when installing `dom-testing-library`. The feature set of this package is fantastic for anyone writing tests against the DOM.

Being able to query against the DOM in the language of your users and using waitFor & other techniques to deal with asynchronous frameworks is really really nice.

Currently when I install this library I get

```
├─┬ @testing-library/dom@7.5.2
│ ├─┬ @babel/runtime@7.9.6
│ │ └── regenerator-runtime@0.13.5
│ ├─┬ aria-query@4.0.2
│ │ ├── @babel/runtime@7.9.6 deduped
│ │ └─┬ @babel/runtime-corejs3@7.9.6
│ │   ├── core-js-pure@3.6.5
│ │   └── regenerator-runtime@0.13.5 deduped
│ ├── dom-accessibility-api@0.4.3
│ └─┬ pretty-format@26.0.1
│   ├─┬ @jest/types@26.0.1
│   │ ├── @types/istanbul-lib-coverage@2.0.1
│   │ ├─┬ @types/istanbul-reports@1.1.1
│   │ │ ├── @types/istanbul-lib-coverage@2.0.1 deduped
│   │ │ └─┬ @types/istanbul-lib-report@3.0.0
│   │ │   └── @types/istanbul-lib-coverage@2.0.1 deduped
│   │ ├─┬ @types/yargs@15.0.4
│   │ │ └── @types/yargs-parser@15.0.0
│   │ └─┬ chalk@4.0.0
│   │   ├── ansi-styles@4.2.1 deduped
│   │   └─┬ supports-color@7.1.0
│   │     └── has-flag@4.0.0
│   ├── ansi-regex@5.0.0
│   ├─┬ ansi-styles@4.2.1
│   │ ├── @types/color-name@1.1.1
│   │ └─┬ color-convert@2.0.1
│   │   └── color-name@1.1.4 deduped
│   └── react-is@16.13.1
```

29 dependencies, from these it looks like only ( `@testing-library/dom` ; `dom-accessibility-api` ; `aria-query` ; `pretty-format` ; `ansi-styles` ; `color-convert` ; `color-name` ) are useful dependencies.

It would be great if installing this library only installed 3 dependencies and if it had 4 optional dependencies ( `pretty-format` & `ansi-*` make great optional dependencies )

### Suggested implementation:

To reduce dependency count the following could be implemented

  - Removing babel dependency
  - Remove nested babel dependency from `aria-query`
  - Make `pretty-format` an optional dependencies 
  - Remove `@jest/types` from `pretty-format` or replace `pretty-format` with a smaller library.

### Describe alternatives you've considered:

:shrug: 

### Teachability, Documentation, Adoption, Migration Strategy:

Having an optional dependency does require teaching users that `pretty-format` can be installed to pretty print the errors and warnings generated by `dom-testing-library`. 

Your tests will work fine as is but might not be as pretty when looking at the output of a test failure without having installed `pretty-format`

An optional dependency looks like

```js
let prettyFormat
try {
  prettyFormat = require('pretty-format')
} catch (err) {
  console.warn('If you would like a pretty error; please npm install pretty-format')
}

/* ... */

// In the library itself; wrap every usage of `prettyFormat` in a ternary or if statement
console.log(prettyFormat ? prettyFormat(x) : x)
```

**Comment by eps1lon** [comment]
Having readable error messages is an essential part of a good testing setup in my opinion. Your dependency tree is 50% made up of types. What would you gain by having a smaller tree?

**Comment by Raynos** [comment]
> What would you gain by having a smaller tree?

I am whitelisting and auditing all the code I install for security. Every dependency is something I have to read, I have to whitelist that module name, I have to audit the authors that publish it to npm. 

Also, every dependency I install is something I might have to fork, maintain and fix if my app is being used on a longer term then the author of the package maintains his package.

Less dependencies, less problems.

Currently my application looks like this

```
$ npm ls --dev
my-app @ 1.0.4
├── @pre-bundled/rimraf@3.0.0-patch-1
├── @pre-bundled/tape@4.11.0
├── @types/node@13.1.5
├── collapsed-assert@1.0.3
├── fake-s3@3.1.3
├── npm-bin-deps@1.6.0
├── styles@1.1.0 ({private})
└── tape-harness@4.0.0
$ npm ls --prod
my-app @ 1.0.4
├── @optoolco/components@8.6.1
├── @optoolco/tonic@11.1.1
├── @raynos/private-components@3.2.0 ({internal})
├── @raynos/append-fs-logger@1.1.0 ({internal})
├── @raynos/async-level {internal}
├── @raynos/cache-disk@1.5.2 ({internal})
├── @raynos/data-layer-view@2.0.0 ({internal})
├─┬ @raynos/electron-main@3.1.1 ({internal})
│ ├── @raynos/append-fs-logger@1.1.0 ({internal})
│ ├── @raynos/cache-disk@1.5.2 deduped ({internal})
│ └── ini@1.3.5 deduped
├── charwise-compact@4.1.0
├── error@10.2.0
├── ini@1.3.5
├── s-ago@2.1.0
├─┬ supports-color@7.1.0
│ └── has-flag@4.0.0
└── uuid@3.4.0
├─┬ aws-sdk@2.600.0
│ ├─┬ {16 nested deps ... aws-sdk is whitelisted and critical}
├─┬ leveldown@5.4.1
│ ├─┬ {7 nested deps ... leveldb database driver is whitelisted and critical}
```

I've audited all my dependencies and chosen two whitelist two critical third party libraries ( `aws-sdk` & `leveldown` )

**Comment by Raynos** [comment]
> Having readable error messages is an essential part of a good testing setup in my opinion.

I'm fine with installing `pretty-format` by default. As an alternative to an optional dependency we could vendor it. ( https://github.com/Raynos/npm-bin-deps/blob/master/package.json#L8-L10 )

For example

```bash
cp -r node_modules/pretty-format/build ./vendor/pretty-format
sed -i /require('pretty-format')/require('./vendor/pretty-format')/
npm i ansi-regex ansi-styles react-is --save
```

**Comment by eps1lon** [comment]
> As an alternative to an optional dependency we could vendor it.

So we would need to maintain it rather than the folks over at `jest`? That doesn't sound like a solution to me.

I understand the general concern but I don't agree with the extreme step to simply cut it. All of the listed dependencies (with the exception of `dom-accessibility-api` maybe) are maintained either by large orgs or long term OSS maintainers.

The security risk they pose seems to be on the same level as using testing-library itself. It sounds like there is some subtext here I'm not getting. Could you explain why `pretty-format` is such an issue for you?

**Comment by Raynos** [comment]
> So we would need to maintain it rather than the folks over at jest? That doesn't sound like a solution to me.

You can have the folks at jest maintain it.

```bash
npm install pretty-format --save-dev
```

Then if you want to get a newer version of `pretty-format`

```bash
npm install pretty-format@latest --save-dev
cp -r node_modules/pretty-format/build ./vendor/pretty-format
```

You are correct that if a security hotfix of `pretty-format` is released you will have to manually release a new security hotfix of `dom-testing-library` . 

This would be the same maintenance burden if you set the version of `pretty-format` in package.json to `"pretty-format": "26.0.1"` or `"pretty-format": "~26.0.1"` . There are people with different opinions on whether `^` ; `~` or `exact versions` are the best practice to follow.

**Comment by Raynos** [comment]
> The security risk they pose seems to be on the same level as using testing-library itself. It sounds like there is some subtext here I'm not getting. Could you explain why pretty-format is such an issue for you?

There is no subtext; the particular modules being used are a not an issue. I mentioned `pretty-format` as proposing a solution for reducing dependency count; any solution to reducing dependency count is fine for me.

When I install a library I would prefer to install a library with zero dependencies.

As an example, the user experience of installing `typescript` or `rollup` ( both zero deps ) is great; the user experience of installing `eslint` or `babel` is frustrating.

I am also the author of https://github.com/Raynos/tapzero#tapzero and believe that installing 33MB of code to use a testing library like `jest` is insanity.

**Comment by kentcdodds** [comment]
Thanks for sharing your opinions @Raynos, but I think there's a values misalignment here so I don't expect this to go anywhere. Sorry.

**Comment by Raynos** [comment]
No worries; thanks for listening.
