### ISSUE TITLE
getByRole() doesn't recognize header's implicit banner role

### ISSUE THREAD

**Issue by darekkay** [testing-library/dom-testing-library#578]
- `@testing-library/dom` version: `7.5.1`
- `@testing-library/jest-dom`: `5.7.0`
- `@testing-library/react`: `10.0.4`
- `jest`: `24.9.0`

### Relevant code or config:

```js
import React from "react";
import { render, screen } from "@testing-library/react";

describe("getByRole", () => {
  test("doens't consider a <header> as banner role", () => {
    render(<header>Test</header>);
    expect(screen.getByRole("banner")).toBeInTheDocument();
  });
});
```

### What you did:

The `header` tag has an implicit `banner` role. RTL's `getByRole` should be able to identify this.

### What happened:

```
TestingLibraryElementError: Unable to find an accessible element with the role "banner"

There are no accessible roles. But there might be some inaccessible roles. If you wish to access them, then set the `hidden` option to `true`. Learn more about this here: https://testing-library.com/docs/dom-testing-library/api-queries#byrole

<body>
  <div>
    <header>
      Test
    </header>
  </div>
</body>
```

### Problem description:

From the official [W3C specs](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/banner.html):

1. The HTML `header` element defines a `banner` landmark when its context is the `body` element.
2. The HTML `header` element is not considered a `banner` landmark when it is descendant of any of following elements:
- `article`
- `aside`
- `main`
- `nav`
- `section`

Chrome gets this one right:

![image](https://user-images.githubusercontent.com/3101914/82117707-3fc28500-9772-11ea-92c4-0d289de84d1b.png)

### Suggested solution:

RTL should be able to identify the role correctly with respect to the above `banner` specs for the `header` tag.

**Comment by OCmilo** [comment]
Just complementing:
In the documentation it states:

>Testing Library uses aria-query under the hood to find those elements by their default ARIA roles, you can find in their docs [which HTML Elements with inherent roles are mapped to each role.](https://github.com/A11yance/aria-query#elements-to-roles)

If you follow the link, you'll see that aria-query doesn't actually support any landmark roles, which seems to be the issue.

**Comment by darekkay** [comment]
Thanks for the information, I've created an [issue](https://github.com/A11yance/aria-query/issues/47) in the aria-query project.

**Comment by OCmilo** [comment]
Nice find! I came here for the same problem, so I'm hoping this happens soon.

**Comment by darekkay** [comment]
I've updated `aria-query` to the latest version, but the [issue still occurs](https://github.com/A11yance/aria-query/issues/47), unfortunately.
