### ISSUE TITLE
feature request: remove queryAllBy

### ISSUE THREAD

**Issue by benmonro** [testing-library/dom-testing-library#592]
### Describe the feature you'd like:

OK i fully expect this request to get closed, but in the off chance it doesn't...

If the purpose of queryBy is to check the non existence of things... why even have queryAllBy in the first place?  when would you ever check for the non existence of multiple things?  seems to me that only get & find should have the 'all' variants.

As I was implementing the suggestions feature, and was a bit stuck on how to give the full query name in the suggestion, i was staring at `queryAllBy` and wondering why it was even there.  i mean i know it's there as the underlying implementation of all the queries, but like... should it be exported?  I know it'd be a breaking change to remove it, but if there's no suggested use case for it... should it just be deprecated?

feel free to close this, but just in case you agree, i figured i'd file it as a ticket.

### Suggested implementation:
remove queryAllBy variants. :)

**Comment by kentcdodds** [comment]
Without `queryAllBy`, How would you do something like this?

```javascript
expect(screen.queryAllByRole('listitem')).toHaveLength(0)
```

Aside from that, removing these would violate the principle of least surprise so I don't think we'll want to do it either way 😅

Thanks though!

**Comment by benmonro** [comment]
@kentcdodds no worries, i figured it wouldn't be, i guess it'd be weird to have an `allBy` for get and find, but not query, but to answer your question:

```js
expect(screen.queryByRole('listitem')).toBeNull()
```

:)

**Comment by kentcdodds** [comment]
That's fine, but I don't think that looks quite as good as:

```javascript
expect(screen.queryAllByRole('listitem')).toHaveLength(3)
userEvent.click(screen.getByRole('button', {name: /remove all/i})
expect(screen.queryAllByRole('listitem')).toHaveLength(0)
```

😉

**Comment by ElvenMonky** [comment]
@kentcdodds Which in turn doesn't look as good as:
```
expect(screen.getAllByRole('listitem')).toHaveLength(3)
userEvent.click(screen.getByRole('button', {name: /remove all/i})
expect(screen.getAllByRole('listitem')).toThrow()
```

**Comment by ElvenMonky** [comment]
@alexkrolick Right. Have not tested it, just wanted to show an idea.
