### ISSUE TITLE
Cannot find listitem, term or definition (and more?) elements with getByRole

### ISSUE THREAD

**Issue by ntsim** [testing-library/dom-testing-library#603]
- `@testing-library/dom` version: 7.9.0
- Testing Framework and version: Jest 25.2.7
  
- DOM Environment: jsdom 15.2.1
  

### Relevant code or config:

```js
test('there should be a list item', () => {
  render(
    <div>
      <ul>
        <li>Test</li>
        <li>Test 2</li>
      </ul>
    </div>,
  );

  expect(
    screen.getByRole('listitem', {
      name: 'Test',
    }),
  ).toBeInTheDocument();
});

test('there should be a term and definition', () => {
  render(
    <div>
      <dl>
        <dt>Test</dt>
        <dd>Test 2</dd>
      </dl>
    </div>,
  );

  expect(
    screen.getByRole('term', {
      name: 'Test',
    }),
  ).toBeInTheDocument();

  expect(
    screen.getByRole('definition', {
      name: 'Test 2',
    }),
  ).toBeInTheDocument();
});
```

### What you did:

Created tests using:
- `getByRole('listitem', { name: '...' })`
- `getByRole('term', { name: '...' })`
- `getByRole('definition', { name: '...' })`

### What happened:

Get the following errors from Testing Library for each respective test:

```
TestingLibraryElementError: Unable to find an accessible element with the role "listitem" and name "Test"

Here are the accessible roles:

  list:

  Name "":
  <ul />

  --------------------------------------------------
  listitem:

  Name "":
  <li />

  Name "":
  <li />

  --------------------------------------------------

```

```
TestingLibraryElementError: Unable to find an accessible element with the role "term" and name "Test"

Here are the accessible roles:

  term:

  Name "":
  <dt />

  --------------------------------------------------
  definition:

  Name "":
  <dd />

  --------------------------------------------------
```

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-ryxq7

### Problem description:

It seems like `getByRole` isn't able to identify `listitem`, `term` and `definition` roles. I would suspect that it isn't limited to just these roles. Perhaps this is happening for non-interactive role types ?

**Comment by eps1lon** [comment]
`listitem` cannot be named by text content but by author (e.g. aria-label). Though you shouldn't name just to be able to query them.

The same applies to term and definition.

It's not clear what you're trying to do from your code example but for listitem querying by index is actually the closest you're going to get to how screen readers access them i.e. `getAllByRole('listitem')[4]`.
