### ISSUE TITLE
docs: `waitForElementToBeRemoved` incorrect promise return type

### ISSUE THREAD

**Issue by mdjastrzebski** [testing-library/dom-testing-library#610]
- `@testing-library/dom` version: v7.10.1
- Testing Framework and version: N/A
- DOM Environment: N/A

### Relevant code or config:
N/A

### What you did:
Read docs/types/code for `waitForElementToBeRemoved`.

### What happened:
Found discrepancy between declared return type for `waitForElementToBeRemoved` (docs & typescript types state `Primise<T>`) and actual implementation (`Promise<true>`).

### Reproduction:
Compare docs or typescript types with `waitForElementToBeRemoved` implementation.

### Problem description:

[Documentation](https://testing-library.com/docs/dom-testing-library/api-async#waitforelementtoberemoved), states the promise return type is `T`.

With following declaration:

```js
function waitForElementToBeRemoved<T>(
  callback: (() => T) | T,
  options?: {
    container?: HTMLElement
    timeout?: number
    interval?: number
    mutationObserverOptions?: MutationObserverInit
  }
): Promise<T>
```

The same is declared in [typescript types](https://github.com/testing-library/dom-testing-library/blob/master/types/wait-for-element-to-be-removed.d.ts):

```ts
export function waitForElementToBeRemoved<T>(
    callback: (() => T) | T,
    options?: waitForOptions,
): Promise<T>;
```

However `waitForElementToBeRemoved` implementation returns however `true` instead of `T`. 

Additionally, the same above docs later states that "Here is an example where the promise resolves with true because the element is removed:"

### Suggested solution:

Make documentation and code agree with each other. For which I see 3 available options:

1. Updated the docs & typescript types so that `Promise<Boolean>` or `Promise<true>` is used.
2. Update the code, so that instead of returning `true`, the code returns the initial value of `callback` evaluation. This seems feasible, since in the implementation, `callback` is immediately called in order to check that elements are initially present & and only then subsequently removed. We might capture that initial value, and return it to the caller. Hence resolving the promise with `T` indeed.
3. Change both code and docs so that promise without meaningful values is returned like `Promise<null>`. The advantage of this options is that it avoids using `Boolean` type where the return value is always `true` hence does not add meaning.

**Comment by tjefferson08** [comment]
Hey @mdjastrzebski, I noticed this little hiccup as well!

I jumped the gun and gave a PR a shot, maybe have a look if you're interested ❤️

**Comment by kentcdodds** [comment]
@all-contributors please add @mdjastrzebski for bugs
