### ISSUE TITLE
return value from `act`?

### ISSUE THREAD

**Issue by kmckee** [testing-library/dom-testing-library#613]
### Describe the feature you'd like:

I want the `act` method to return whatever value is returned by the callback that's passed into it.

Currently, I'm writing tests like this:

```
test("loading", async () => {
    // ...
    let getByRole;
    await act(async () => {
      getByRole = render(<Foo/>).getByRole;
    });
    expect(getByRole("heading")).toHaveTextContent("Loading...");
});
```

If `act` returned the value returned by the callback, I could instead write this:

```  
test("loading", async () => {
    // ...
    const getByRole= await act(async () => render(<Foo />).getByRole);
    expect(getByRole("heading")).toHaveTextContent("Loading...");
});
```

Is this something that's been considered?  I'd be interested to dig in, I just want to make sure I'm not spending time on something with no hope of going anywhere.

Thanks for all your work on this library - it's a joy to use. ✌

**Comment by kentcdodds** [comment]
Hi there,

`act` is a simple wrapper (and polyfill) around react-dom/test-utils `act`. So you'll need that to get updated first. Feel free to file an issue over on the react issue if you'd like to give that a try. For now, I don't think we'll do this. Thanks anyway.

**Comment by JoshuaKGoldberg** [comment]
For reference, that issue has since been closed: https://github.com/facebook/react/issues/16366
