### ISSUE TITLE
Make *every* event fire only after a tick of the event loop

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/dom-testing-library#636]
Users don't fire a keyUp *immediately* after a keyDown and neither should our tests.

I'm thinking this could be pretty easy to add by making our own copy of `fireEvent` which adds a `tick` before executing the event.

This means that every util would be async.

**Comment by nickmccurdy** [comment]
It seems like this is already implemented in #616. Please reopen this if I'm mistaken.
