### ISSUE TITLE
Regression in getByTestId when using custom testIdAttribute v7.13.0

### ISSUE THREAD

**Issue by geoffharcourt** [testing-library/dom-testing-library#643]
- `@testing-library/dom` version: 7.14.0 (issue appears in all versions after 7.13.0)

- Testing Framework and version:
  
  Jest 0.26.1

- DOM Environment:
  
  jsdom-environment-jsdom 0.26.1

### Relevant code or config:

```js
// setup
import * as Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import 'jest-enzyme';
import 'jest-extended';
import { configure } from '@testing-library/dom';
import I18n from 'utils/i18n';

Enzyme.configure({ adapter: new Adapter() });

configure({
  testIdAttribute: 'data-test',
});

I18n.locale = 'en';
```

### What you did:

We use `data-test` as our test attribute for items we can't reach by accessible handlers. After upgrading this stopped working.

### What happened:

In the error output for missing nodes when we use `getByTestId` we see the DOM tree we expected, but testing-library fails because it can't find an element with the same attribute value for `data-testid`.

### Reproduction:

https://github.com/geoffharcourt/dom-testing-library-template
### Suggested solution:

Not sure yet!

**Comment by smeijer** [comment]
By looking at the releases, the only thing changed in relation to the testid in 7.14 are these lines:

https://github.com/testing-library/dom-testing-library/blob/d5e17bd63c5c339d4ae29e0090f449b2c8364755/src/suggestions.js#L123:L126

To verify, they can be easily commented out. To fix, the `testIdAttribute` config option should be used there instead of `data-testid`.

I'm not sure though if/how a suggestion is able to stop queries from working.

**Comment by geoffharcourt** [comment]
I'm having a lot of trouble producing a proper test case for this or even figuring out how this is breaking. Continuing to investigate.

**Comment by smeijer** [comment]
I honestly have no idea either. But the issues has been fixed by #651 right?

So, let's close this issue and continue with the more important matters? :innocent:

**Comment by geoffharcourt** [comment]
@smeijer that didn't resolve the issue... Still investigating.

**Comment by smeijer** [comment]
Hmm. That sucks. And just to be clear, `7.13.0` does NOT have this issue correct? Only 7.14 and later?

**Comment by geoffharcourt** [comment]
@smeijer that's correct. I tried 7.13.0 and each of the 7.14.x versions, and it looks like 7.14.0 is where the problem comes.

I've narrowed down that it doesn't have anything to do with being called in `waitFor`, etc. It just seems like our previously working global `testIdAttribute` assignment gets ignored. Configuring it inline in the example also doesn't fix the issue.

**Comment by geoffharcourt** [comment]
The configuration is somehow not getting pulled when it's invoked from the suggestion code. Here's a test example from our suite:

```typescript
describe('and the lesson is view_data', () => {
  it('renders the view assessment data call to action', () => {
    configure({testIdAttribute: 'data-test'});
    const lessonActivity = LessonActivityFactory.build({
      format: FormatEnum.quiz,
    });
    const lesson = LessonFactory.build({
      average: 100,
      lessonActivities: [lessonActivity],
    });
    const stubToggle = (): void => {};

    const { getByTestId } = render(
      <CallToAction
        actionableLessonState={ActionableStateEnum.view_data}
        lesson={lesson}
        toggleModal={stubToggle}
      />,
    );

    getByTestId('cta-view-assessment-data');
  });
});
```

When I insert some debug statements to catch the config as it's seen in `makeGetAllQuery` as it's called in the suggestion chain, I get this:

```
  console.log
    [Function: queryAllByTestId]

      at makeGetAllQuery (node_modules/@testing-library/dom/dist/query-helpers.js:81:11)

  console.log
    {
      testIdAttribute: 'data-testid',
      asyncUtilTimeout: 1000,
      asyncWrapper: [Function: asyncWrapper],
      eventWrapper: [Function: eventWrapper],
      defaultHidden: false,
      showOriginalStackTrace: false,
      throwSuggestions: false,
      getElementError: [Function: getElementError],
      _disableExpensiveErrorDiagnostics: false
    }

```

**Comment by geoffharcourt** [comment]
OK, we figured out why this is still not working. `react-testing-library` is still requiring an unfixed different version of `@testing-library/dom`, so the default `testIdAttribute` was being set by the wrong `configure` call. This should be resolved when `react-testing-library` bumps its dom dependency.

h/t @devinrm
