### ISSUE TITLE
v7.16.2 "unexpected token" with "catch {" in helpers.js

### ISSUE THREAD

**Issue by BrentonCozby** [testing-library/dom-testing-library#660]
From my Jenkins build log:

![image](https://user-images.githubusercontent.com/5513633/85319042-04148c80-b48f-11ea-97a7-e91674916d09.png)

from Dev Dependecies:
```json
    "@babel/cli": "^7.10.1",
    "@babel/core": "^7.10.2",
    "@babel/plugin-proposal-class-properties": "^7.10.1",
    "@babel/plugin-transform-runtime": "^7.10.1",
    "@babel/preset-env": "^7.10.2",
    "@babel/preset-react": "^7.10.1",
    "@babel/runtime": "^7.10.2",
    "@testing-library/jest-dom": "^5.9.0",
    "@testing-library/react": "^10.0.5",
```

@testing-library/react v10.0.5 installs testing-library/dom v7.16.2 which breaks our build, resulting in the error shown in the picture above. I can only show/provide limited information because this is from a private repo, but **adding "@testing-library/fom": "7.16.0" to our dev dependencies fixed our build (without any other changes).**

I'm sorry for not reporting more information as requested but I figured it was better to report this with missing information than not to report at all. I'm happy to provide more specifics if requested and able.

**Comment by kentcdodds** [comment]
Which version of node are you running? Optional catch bindings are supported in Node 10 which is the version that Testing Library supports.

**Comment by BrentonCozby** [comment]
@kentcdodds damn, I think you solved it. It builds fine on my laptop (node v12.16.1) but fails on the jenkins server (node v8.11.1). I'll bump the node version and see if that fixes things.

**Comment by BrentonCozby** [comment]
Turns out we won't be able to update the Node version any time soon so I guess we'll just stick with v7.16.0.

Anyway, thanks for chiming in. Love your libraries and blog posts.
