### ISSUE TITLE
Fix default branch CI build

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/dom-testing-library#663]
I think when I merged [this PR](https://github.com/testing-library/dom-testing-library/pull/656) I had assumed the build passed because of [codecov's comment](https://github.com/testing-library/dom-testing-library/pull/656#issuecomment-647007727) which shouldn't appear until we have a successful build. I'm still not sure what happened there to be honest.

But in any case, since that PR was merged (which really just updated `aria-query`) our tests have been failing. Mostly the suggestion tests, but some others as well.

Could someone dive in and help. You don't have to do it all. Even fixing a few would be helpful.

I think we could especially use help from @benmonro who wrote most of the suggestion tests. In particular, aria-query now gives us a role of `generic` for generic elements. I'm not 100% certain I want to recommend `screen.getByRole('generic', {name: /bob/i})` over `screen.getByText(/bob/i)`... So I'm thinking we should probably skip that suggestion if the role is `generic`.

**Comment by marcosvega91** [comment]
very weird 😕

**Comment by benmonro** [comment]
Cool glad this got resolved

**Comment by kentcdodds** [comment]
@marcosvega91 was fast as lightning! ⚡
