### ISSUE TITLE
Intellisense with getByRole

### ISSUE THREAD

**Issue by timdeschryver** [testing-library/dom-testing-library#666]
### Describe the feature you'd like:

I got the feeling that we could make it easier to use the `getByRole` queries.
From what I can see not all developers know (all of) the WAI-ARIA Roles.
The suggestions and the playground are definitely helping, but I think it would be nice if we can type the roles so that the IDE can pick them up and suggest them (shorter feedback loop).

### Suggested implementation:

Add a `ByRoleMatcher` that includes all of the ARIA Roles, and use this type in the `byRole` queries.

```ts
export type ByRoleMatcher =  'button' | 'listitem' | 'textbox' | String | RegExp | MatcherFunction

export type AllByRole = (container: HTMLElement, role: ByRoleMatcher, options?: ByRoleOptions) => HTMLElement[];
export type GetByRole = (container: HTMLElement, role: ByRoleMatcher, options?: ByRoleOptions) => HTMLElement;
export type QueryByRole = (container: HTMLElement, role: ByRoleMatcher, options?: ByRoleOptions) => HTMLElement | null;
```

This won't be a breaking change because the user would still have the possibility to use a role that isn't included in the type.

This looks like this:

![image](https://user-images.githubusercontent.com/28659384/85445999-470c5800-b594-11ea-95ec-ffea002e7fcf.png)

### Describe alternatives you've considered:

It's important to use `String` while defining the type, otherwise it will either result that the passed role must be one of the options, or that there won't be any intellisense. That's also the reason why it isn't possible to reuse the existing `Matcher` type (e.g. `export type ByRoleMatcher = Matcher | 'button' | 'listitem' | 'textbox'`)

See the [TS playground](https://www.typescriptlang.org/play/?ssl=18&ssc=21&pln=18&pc=12#code/PTAEAsEMGdQSwHYBcCmAbNdoodgNKAPYJoCeokAxpSgA5KzEpEBmoS4z0SATogOagArgjjFoAKBYjKSMQlDRIpABLo0hAIwAKRLSFIAXKADknDIROgAPqYBGxAFaEhPK7bOQLJgJSgA3hKgoJTihGgoAHQa-LoI+kg+ANwSAL4SEiAQMKAIhPDI6lg4+BTUdAwUGIq8AqAAbl5CKJLSCLLyispqFgBMcQnGZuqWNvZOLm5jnt5j3HwI-H6BwaG44VExAwbJaRlZULCIqBjFuCgEVDT0VWg1C4KNaM2tMnLEXaojAMzbRqb8QiEAAmdlIKHcpkgQlAPBQ9UIcCmHiUzyQkIAyrVFssgiEwhFooRYnodil0hIlF8LDoTPwDDh2JB+L4UlSehp+nSGQokMzWZTuj9tNzULz+bsJEA) for examples.

**Comment by kentcdodds** [comment]
Let's do it 👍

**Comment by marcosvega91** [comment]
It will be very helpful 👯

**Comment by eps1lon** [comment]
The types for `aria-query` list all supported roles. Though I think we need to allow any string regardless. Not sure if vscode will still display all string literals if you have `AllowedRoles | string`;

**Comment by timdeschryver** [comment]
@eps1lon  it does, if String is used. See the TS playground in the issue description.
