### ISSUE TITLE
fireEvent.change remove element event not triggered after change

### ISSUE THREAD

**Issue by Auroralias** [testing-library/dom-testing-library#674]
react-testing-library version: 6.12
    react version: 16.9
    npm (or yarn) version: yarn 1.22.4

Relevant code or config:

```javascript
fireEvent.submit(getByTestId('testForm.form'))

fireEvent.change(getByLabelText('Dropdown'), {
  target: { value: 'test2' },
})

//Without this, the error text remains
fireEvent.submit(getByTestId('testForm.form'))

await wait(() => {
  expect(queryByText('Error Message')).not.toBeInTheDocument
})
```

What you did:

I am trying to test that error text disappears when a specific option is selected from a dropdown. The drop down is on a form hook.

This bit:

```javascript
fireEvent.change(getByLabelText('Dropdown'), {
  target: { value: 'test2' },
})
```

is changing the option value, but the event to delete the element containing the error text does not appear to.

**Comment by kentcdodds** [comment]
Hi @Auroralias, when the user interacts with a dropdown like this, they typically fire a lot more events than a simple `change` event. So we've got [`@testing-library/user-event`](https://github.com/testing-library/user-event) that might be more helpful to you than `fireEvent` by itself. Can you give that a shot?

If that doesn't work, if you could create a reproduction following [the instructions here](https://kcd.im/rtl-help) and post it to [our discord chat](https://testing-library.com/discord) that would be best.

I don't think this is a bug, so I'm going to close the issue, but please do reach out to our community on discord if you need further assistance. Good luck!
