### ISSUE TITLE
findAllBy ignore same tag name

### ISSUE THREAD

**Issue by eliyaomid** [testing-library/dom-testing-library#676]
In this test case `findAllBy*` ignore same tag and failed test

```js
const page = render(<div><p class="a">this is test</p><p class="b">this is test</p><div />)
expect(
      await page.findAllByText("this is test")
).toHaveLength(2);
```

**Comment by marcosvega91** [comment]
Hi @eliyaomid thanks for opening this issue 😄 

I have created a [sandbox](https://codesandbox.io/s/dom-testing-library-template-4sbbf?file=/src/__tests__/index.test.js) but I have no issue. 
Can you please add more details ? 
Which version of `testing-library` are you using?

**Comment by nickmccurdy** [comment]
Adding to this comment, it would help if you could fork the sandbox and link to your fork with the issue reproduced.

**Comment by marcosvega91** [comment]
I think that we can close this for now. @eliyaomid if you need further help you can add a comment here 😄
