### ISSUE TITLE
Query by autocomplete attribute

### ISSUE THREAD

**Issue by tigt** [testing-library/dom-testing-library#682]
### Describe the feature you'd like:

Consider this HTML that’s gone through localization into (my amateur) Spanish:

```html
<form method=post lang=es>
  <p><label>Nombre de usuario: <input autocomplete=username name=u></label>

  <p><label>Contraseña: <input autocomplete=current-password name=p></label>

  <p><button>Acceder</button>
</form>
```

Because the `autocomplete` attribute is standardized to map directly to user expectations for the purpose of autofill, browser/extension login managers, and password generators, it seems about as robust as the `role` attribute.

In the above example, you could query the right input across languages via the `name` or maybe a prefilled `value`, but those are more likely to change in the case of new tests, new backends, additional auth endpoints, new providers, etc.

However, you can be certain that `[autocomplete=username]` will always map to the User ID field (or you’ve got bigger problems than a rotting test). In fact, it‘s specified to mean the same thing regardless of the underlying element (banks love using `<select>` for some reason) or input type; consider login forms that ask for a handle, email address, phone number, ID number, or any combination thereof, but only use them as an opaque user identifier. It even works for `<input type=hidden>`, as suggested by Chrome for multi-step login flows.

### Suggested implementation:

`ByAutocomplete` seems like the simplest thing that could possibly work.

### Describe alternatives you've considered:

React’s JSX mappings have unfortunately camel-cased the `autocomplete` DOM property as `autoComplete`, but that might just be a specific quirk for only `react-testing-library`.

### Teachability, Documentation, Adoption, Migration Strategy:

I think this would go under “Queries Accessible to Everyone”, as it’s roughly as exposed as `role`. But I’m certainly not pretending to know for sure.

**Comment by nickmccurdy** [comment]
I like this idea. Making sure autocompletion is set up is good for accessibility and security.

Do you have a specific API in mind? I'm assuming you'd usually use something like `ByAutocomplete("username")`, but would it make sense without an id?

**Comment by tigt** [comment]
Without an ID? Like, `ByAutocomplete()`?

**Comment by nickmccurdy** [comment]
Yea. I mean, would it make sense to get all elements with the `autocomplete` attribute? I see a pattern like this occasionally, and I could see it being useful for completable forms:

```js
const [username, password] = getAllByAutoComplete()
userEvent.type(username, "nick")
userEvent.type(password, "password")
```

**Comment by kentcdodds** [comment]
This would make more sense as an assertion that a query. The user will still primarily know what the field is for based on it's label and will therefore "query" the screen based on the label. But you could definitely use jest-dom's `toHaveAttribute` assertion to get confidence that the autocomplete is set up properly.

**Comment by eps1lon** [comment]
I agree with https://github.com/testing-library/dom-testing-library/issues/682#issuecomment-654019232. We should have a very high barrier for introducing new queries because they introduce new choices.

**Comment by nickmccurdy** [comment]
If I'm modeling a login flow, I'd rather test from the perspective of a password manager (which specifically looks for autocompleted username and password fields) to encourage security and accessibility. As a user, I don't look for username/password fields anyway, I just tell my password manager to fill them.

That being said, I think it might be better to solve this problem by introducing new behavior to `user-event` rather than coupling the behavior to queries. For example, `userEvent.fill("username", "nick")` would find the element with `autocomplete="username"` and call `userEvent.type(element, "nick")` internally.

**Comment by eps1lon** [comment]
> If I'm developing a login flow, I'd rather test from the perspective of a password manager

You can do that. It's out of scope currently for testing library where we focus on human users/screen readers. Targetting those is much easier especially because we have a spec. For password managers this is not necessarily the case. If we want those we should define the scope first. Just adding a "ByAutocomplete" query is insufficient.

**Comment by nickmccurdy** [comment]
It seems like the names of autofilled fields are standardized by WHATWG: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill

**Comment by kentcdodds** [comment]
I just really don't think the use case is strong enough to justify am official query. This is what custom queries support is for. For that reason, I'm going to close this. Thanks for the discussion.
