### ISSUE TITLE
ByRoleOptions doesn't contain text

### ISSUE THREAD

**Issue by martin-arusalu** [testing-library/dom-testing-library#696]
- `@testing-library/dom` version: 7.20.0
- Testing Framework and version: jest 26.0.1
  
- DOM Environment: jsdom 16.2.2
  

### Relevant code or config:
From https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA22.html
```html
<div role="status">5 results returned.</div>
```
My test:
````js
// the element is added to the screen in a previous beforeEach function.
test('should have a status role', () => {
  expect(
    screen.getByRole('status', { text: '5 results returned.' })
  ).toBeTruthy();
});
````

### What you did:
I wanted to create a test for a message element with certain status and text.

### What happened:
TypeScript threw an error ` Object literal may only specify known properties, and 'text' does not exist in type 'ByRoleOptions'.`

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-2l5kw?fontsize=14&hidenavigation=1&theme=dark

### Problem description:

The test works with the `text` selector in js but it throws an error in TypeScript.

### Suggested solution:
Add the `text` prop to `ByRoleOptions` interface or in some other way allow `getByRole` to provide text filter. Or make it clear that you can't use the `text` filter option with `getByRole` function.

**Comment by eps1lon** [comment]
You can [filter by accessible name instead.](https://testing-library.com/docs/dom-testing-library/api-queries#byrole).

If you're sure you want the text content you can always do `getAllByRole('status').filter(element => element.textContent === "5 results returned.")`.

Or you can use `getByText`.

Seems to me we have plenty of existing solutions for this problem. Do these work for you?

> Or make it clear that you can't use the text filter option with getByRole function.

I think that

> Object literal may only specify known properties, and 'text' does not exist in type 'ByRoleOptions'.

is already sufficient in that regard.

**Comment by martin-arusalu** [comment]
Thanks for the quick reply!
Yes I believe we can make this work with those solutions.
I was just wondering if it was just accidentally left out of the interface because in JS the text option works and looks a lot better and cleaner than adding this filter.

**Comment by eps1lon** [comment]
> Yes I believe we can make this work with those solutions.

Great to hear! Seems like we can close this.
