### ISSUE TITLE
`getByLabelText` matching strategy inconsistent with other queries

### ISSUE THREAD

**Issue by NeekSandhu** [testing-library/dom-testing-library#712]
- `@testing-library/dom` version: 7.21.x
- Testing Framework and version: NA
  
- DOM Environment: NA
  

### Problem description:

Take this HTML fragment as an example:

```html
 <label>
  Prefix
  <span>Please choose a prefix</span>
  <select>
    <option>Mr</option>
    <option>Mrs</option>
  </select>
 </label>
```

```js
// this does not get me the handle to the control
// (and I cannot use regex because it conflicts with other controls on the page)
const prefixSelect = getByLabelText('Prefix')
```

Because of the logic [here](https://github.com/testing-library/dom-testing-library/blob/f854cde7cef103c939c40f3b56c11543604ce627/src/queries/label-text.js#L19), the match is performed against the text content of the entire label which after processing resolves to `"Prefix Please choose a prefix"`. This not only doesn't work but also goes against matching strategy of other queries where they don't match text spanning multiple elements, but only the contents of each isolated element at a time.

### Suggested Solution:

Instead of capturing all labels on the page at once and then matching against their text content. We should instead simply run `queryAllByText` and then leverage `matched.find(e => e.closest('label')` to pin-point first label which is parent of the matched elements. Cross-referencing `for` and `id` shouldn't be hard I assume. This will remove all inconsistencies between queries.

**Comment by delca85** [comment]
Hi @NeekSandhu !
Thanks for sharing your opinion.

I would like to try to give you an answer, even if I am not so expert in this field.
I think in this case it could be right that the label is considered for its entire text content, because the whole label (`label` element and its children values) content composes the label value.

If there is something else I could add it's that this query
```js
getByLabelText('Prefix', {exact: false})
```
makes you get the `select` element, even if I am not so sure this helps you because you mentioned some issue with other controls on the page. 

Once again, I don't pretend to be right at all so be patient if I am missing something.

**Comment by kentcdodds** [comment]
According to [this jsbin](https://jsbin.com/wunebemozu/edit?html,output), pulling up the accessibility devtools, the label for the `<select>` (combobox) is: "Prefix Please choose a prefix"

![image](https://user-images.githubusercontent.com/1500684/88319752-d57e1180-ccd9-11ea-9c68-7836ee438740.png)

So what we're doing is correct according to the accessibility behaviors of the browser which we are striving to follow. So you wouldn't be able to find it with `screen.getByLabelText('Prefix')` I'm afraid. You *could* find it with `screen.getByLabelText('Prefix', {exact: false})` or `screen.getByLabelText(/prefix/i)` (case insensitive regex are actually recommended for all queries).

So I think there's nothing actionable here and the query is behaving properly. Thanks!

**Comment by NeekSandhu** [comment]
very well clarified Kent, makes sense now on why it is the way it is.
