### ISSUE TITLE
Problem with *ByLabelText queries

### ISSUE THREAD

**Issue by romain-trotard** [testing-library/dom-testing-library#713]
- `@testing-library/dom` version: 7.21.2 (and higher)
- Testing Framework and version: 
`jest` version 24.9.0
`@testing-library/react` version 10.4.7 
- DOM Environment: version 14.1.0

### Relevant code or config:
Having this HTML template example:
```js
        <div
            aria-labelledby="dropdown-dropaction"
        >
            <button
                id="dropaction"
            >
                <span
                    id="dropdown-dropaction"
                >
                    global.more.action
                </span>
            </button>
            <div
                aria-labelledby="dropaction"
            >
                A div element
            </div>
        </div>
```

```js
getAllByLabelText(container, 'global.more.action')
```

### What you did:

I want to get the parent _div_ with the `aria-labelledby="dropdown-dropaction"` from the label _global.more.action_, considering that I don't have control on the div with `aria-labelledby="dropaction"` which is handled by an external library.

### What happened:
I am getting two elements instead of one.
![image](https://user-images.githubusercontent.com/17161484/88293454-51d51c80-ccfb-11ea-896a-3b2b9d4926e8.png)

### Reproduction:
I have made a reproduction repository that you can find here: https://github.com/romain-trotard/TLDReproductionProblem

Sorry I did not follow the template. I hope it will not be a problem.

### Problem description:
When having the version _7.21.1_, I get 1 element which is what I want (the parent _div_ with the `aria-labelledby="dropdown-dropaction"`). But going to the version _7.21.2_, I'm now getting 2 elements (visible on the screenshot).

### Suggested solution:
Sorry I don't have a suggestion, I just know it's coming from this line https://github.com/testing-library/dom-testing-library/blob/master/src/queries/label-text.js#L55 with _label.textContent_.

To be honest I'm not sure if it's a regression from the _testing-library/dom_. Or if it's the expected behavior to select the both elements and in this case I don't really know how to select the wanted div from my label.

**Comment by eps1lon** [comment]
I recommend using `ByRole('button', { name: 'the name you expect' })` for more complex labeling mechanics. `ByLabelText` is really only for simple labels.

**Comment by kentcdodds** [comment]
I agree with @eps1lon. I think this is a limitation with the `ByLabelText` query and there's nothing that can reasonably be done to help in this case. Additionally, using `ByRole` queries provides us with more confidence anyway. Thanks!
