### ISSUE TITLE
Mocked dataTransfer items are overwritten by rtl

### ISSUE THREAD

**Issue by Snizhana** [testing-library/dom-testing-library#727]
- `@testing-library/react` version: `10.2.1`
- Testing Framework and version: jasmine version `3.5.0`
- Test runner: karma version `4.0.1`
- DOM Environment: chrome version `83`

### Relevant code or config:

```js
const dragNdropZone = component.getByTestId('drag-n-drop-zone');
const fileName = 'testFileName';

const fileItem = {
  name: fileName,
  size: 100,
  type: 'file',
};

const fileEntry = {
  name: fileName,
  fullPath: `folder_one/folder_two/${fileName}`,
  file: (resolve) => resolve(fileItem),
};

const itemOne = {
  webkitGetAsEntry: () => fileEntry,
};

const dataTransfer = new DataTransfer();

Object.defineProperty(dataTransfer, 'items', {
  value: [itemOne],
});

fireEvent.drop(dragNdropZone, { dataTransfer });

```

### What you did:
I am trying to test drag-and-drop functionality.

### What happened:
rtl overrides items in `dataTransfer` object assigning an empty array to it

### Reproduction:
If we check an event object passed to the `onDrop` handler of  `dragNdropZone` we'll see that `e.dataTransfer.files` is an empty array even though we assigned an array with one item.

### Problem description:

I am not able to mock items as a prop of `dataTransfer` object and test drag-and-drop functionality properly. **NOTE:** mocking worked correctly in rtl version `9.2.0`

**Comment by marcosvega91** [comment]
I have moved the issue 😄

**Comment by kentcdodds** [comment]
No worries @Snizhana :)

Thanks @marcosvega91!

**Comment by delca85** [comment]
I would be glad to work on it.

Does it sound good to all of you?

**Comment by kentcdodds** [comment]
I'd still love to give @Snizhana a chance to work on it if they'd like. If we don't hear anything in the next day or so then go for it @delca85 👍 thanks!

**Comment by Snizhana** [comment]
@kentcdodds @delca85 my apology for the late reply. I have the [PR](https://github.com/testing-library/dom-testing-library/pull/734), it is WIP since I still need to test it. if anyone has started work on the issue I'll close my PR. otherwise I will be grateful for any advice on testing and work verification.
