### ISSUE TITLE
I got error message with screen's methods

### ISSUE THREAD

**Issue by keiya01** [testing-library/dom-testing-library#735]
- `@testing-library/react` version: 10.4.8
- `@testing-library/dom` version: 7.17.1
- Testing Framework and version: jest@26.2.2
  
- DOM Environment: jsdom@16.2.2
  

### Relevant code or config:

jest.config.js
```js
module.exports = {
  roots: ['<rootDir>/src'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
  },
  globals: {
    'ts-jest': {
      tsConfig: 'tsconfig.json',
    },
  },
  testEnvironment: 'jsdom',
  transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$'],
  moduleFileExtensions: ['ts', 'tsx', 'js'],
  testMatch: ['**/*.test.ts?(x)'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
};
```

### What you did:

I wrote test about updating counter.

counter.test.ts
```ts
test('should update count, () => {
  const Text = () => {
    const [count, setCount] = React.useState(0);
    return (
      <div>
        <p>{count}</p>
        <button type="button" onClick={() => setCount((c) => c + 1)}>
          count
        </button>
      </div>
    );
  };
  const Component = () => {
    return <Text />;
  };

  render(<Component />);

  fireEvent.click(screen.getByRole('button', { name: /count/i }));

  expect(screen.queryByText('2')).toBeDefined();
  expect(renderCount.current.Text).toBe(2);
});
```

### What happened:

I got error message bellow when I use `screen.*`.

![スクリーンショット 2020-08-10 13 58 59](https://user-images.githubusercontent.com/34934510/89753058-c4beff80-db11-11ea-8ae9-228e5fe51cbe.png)

Thanks.

**Comment by kentcdodds** [comment]
I just noticed this in my own project. Looks like it's [`dom-accessibility-api`'s use of `getComputedStyle`](https://github.com/eps1lon/dom-accessibility-api/blob/895d296edc38564c92e2db71bc550ea17d2361d2/sources/accessible-name-and-description.ts#L360).

Looks like `getComputedStyle` is used several places in that file. @eps1lon, are you aware of this? It looks like JSDOM doesn't support the second argument to `getComputedStyle`: https://github.com/jsdom/jsdom/blob/5279cfda5fe4d52f04b2eb6a801c98d81f9b55da/lib/jsdom/browser/Window.js#L650-L658

Is there a possibility we could have a fallback here?

**Comment by kentcdodds** [comment]
What's interesting is I'm not sure what changed because dom-accessibility-api has been using the second argument for a while now 🤔

**Comment by eps1lon** [comment]
Fix incoming. `jsdom@^16.4.0` decided to console.error when using the second argument. Apparently that's important. Not the fact that virtually every property is not computed correctly.

**Comment by keiya01** [comment]
@kentcdodds @eps1lon Thanks for your work 🙏
