### ISSUE TITLE
getByTitle finds any element text?

### ISSUE THREAD

**Issue by awesomeunleashed** [testing-library/dom-testing-library#741]
- `@testing-library/dom` version: 7.22.2
- Testing Framework and version: Jest 26.0.10
- DOM Environment: jsdom 11.12.0

### Relevant code or config:

```js
// component
export default () => <div title="WrongTitle">HelloWorld</div>;

// test
const wantTitle = "HelloWorld";
const { getByTitle } = render(<Hello />);

// I would expect this to fail here
expect(getByTitle(wantTitle)).toBeInTheDocument();

// ...but it fails here
expect(getByTitle(wantTitle).title).toBe(wantTitle);
```

### What you did:

I have a React component with some text, and a `title` attribute that matches that text. I was modifying the component (and tests) to have a different `title` (but the same text) when I disabled it.

### What happened:

I started getting unexpected behavior from my tests because they were expecting the title to have changed, and `getByTitle` was finding the element text.

### Reproduction:

[CodeSandbox](https://codesandbox.io/s/tl-getbytitle-finding-element-text-srtmy)

### Problem description:

Maybe I'm missing something, but it seems very unintuitive that this line:
`expect(getByTitle(wantTitle).title).toBe(wantTitle)`
can fail on the `toBe`. If it's going to fail, shouldn't it fail on the `getByTitle`?

### Suggested solution:

Looking at `queries/title.js`, I see this part:
```js
return Array.from(container.querySelectorAll('[title], svg > title')).filter(
    node =>
      matcher(node.getAttribute('title'), node, text, matchNormalizer) ||
      matcher(getNodeText(node), node, text, matchNormalizer),
  )
```
I assume the `matcher(getNodeText(node)` part is intended for `svg` `title` elements, which makes sense, but it looks to me like this will find the text for any element. Forcing that second condition to only be true for `title` elements would solve it, I think.

**Comment by kentcdodds** [comment]
Hi @awesomeunleashed,

You found a bug! 🐛 Thanks. I think that you're right, we should probably scope that second part to only apply to `svg > title` elements. Would you like to work on fixing this?

**Comment by wyze** [comment]
I did the initial implementation, and I got a PR ready to go on this.

**Comment by awesomeunleashed** [comment]
Thanks folks, looks like it works as expected now!
