### ISSUE TITLE
getByRole can't find button by name if title is ""

### ISSUE THREAD

**Issue by EvgenyOrekhov** [testing-library/dom-testing-library#747]
- `@testing-library/dom` version: 7.22.2
- Testing Framework and version: Jest (whatever version comes with CodeSandbox)
  
- DOM Environment: whatever version comes with CodeSandbox
  

### Relevant code or config:

```js
import React from "react";

export default function App() {
  return <button title="">OK</button>;
}
```

### What you did:

```js
screen.getByRole("button", { name: /ok/i });
```

### What happened:

```text
Unable to find an accessible element with the role "button" and name `/ok/i`

Here are the accessible roles:

  button:

  Name "":
  <button
    title=""
  />
```

### Reproduction:

https://codesandbox.io/s/happy-chandrasekhar-311qt?file=/src/App.js

### Problem description:

Chrome reports that the button has a name:

![image](https://user-images.githubusercontent.com/8045060/90762825-571f8a00-e2ee-11ea-83c3-6944b5867487.png)

But `getByRole` says it does not.

JSFiddle: https://jsfiddle.net/91retmv2/

**Comment by EvgenyOrekhov** [comment]
Firefox also report that the button has a name.

**Comment by eps1lon** [comment]
Thanks for the report. Will take a look at it over at https://github.com/eps1lon/dom-accessibility-api/issues/393
