### ISSUE TITLE
not able to get the window

### ISSUE THREAD

**Issue by isaacking5** [testing-library/dom-testing-library#749]
- `@testing-library/dom` version:
- Testing Framework and version:
  
- DOM Environment:
  

Relevant code or config

```js
```

What you did:

What happened:

Reproduction repository:
https://github.com/testing-library/dom-testing-library-template

Problem description:

Suggested solution:

**Comment by timdeschryver** [comment]
Hi @isaacking5 it's unclear what you're asking.
Could you please fill in the template so we can help.
