### ISSUE TITLE
Textbox not found by name with getByRole 

### ISSUE THREAD

**Issue by NextNebula** [testing-library/dom-testing-library#752]
- `@testing-library/dom` version: 7.22.0
- Testing Framework and version: jest 26.2.2
  
- DOM Environment: jsdom 11.12.0

### Relevant code or config:

```js
screen.getByRole("textbox", { name: "1-initials" })
```

### What you did:

I am making a test for filling in a form. Getting an element with getByRole based on name does not work. Element can't found, while it is in the accessible roles output.

### What happened:

This error show:
`TestingLibraryElementError: Unable to find an accessible element with the role "textbox" and name "1-initials"`

The accessible roles contains the input.
```
Here are the accessible roles:
      textbox:

      Name "":
      <input
        class=""
        name="1-initials"
        placeholder="Voorletters"
      />
```

### Reproduction:

See this code sandbox for a reporduction: https://codesandbox.io/s/react-testing-library-demo-forked-7cdhq

**Comment by marcosvega91** [comment]
Hi @NextNebula thanks for reaching us 😄 .

The problem with your code is that the `name` in the option object is the accessibility name of the input and not the attribute name.

If you look [here](https://testing-playground.com/gist/ae688f31d604eec2352783f5f8d60008/537a401556604387011bf76cd6762b19c9b8fa0e), I have created a little example for you. 

I also leave you a reference of how it works https://w3c.github.io/accname/#mapping_additional_nd_name.
I'll close this, let me know if you need further assistance. You can also ask for help on our [discord](https://testing-library.com/discord) 

Regards 
Marco
