### ISSUE TITLE
getByLabelText should find SVGs labelled by multiple elements

### ISSUE THREAD

**Issue by juanca** [testing-library/dom-testing-library#760]
- `@testing-library/dom` version: 7.24.0
- Testing Framework and version: jest@26.4.2
- DOM Environment: @testing-library/jest-dom@5.11.4
- In my env, I am using Node 14.4.0

### Relevant code or config:

It boils down to using `aria-labelledby` for an SVG:

```js
const div = document.createElement("div");
div.innerHTML = `
<div>
  <div id="first">Composed</div>
  <svg aria-labelledby="first second" id="second">
    <title>label text 2</title>
  </svg>
</div>`;

document.body.appendChild(div);
const { getByLabelText } = within(document.body);

expect(getByLabelText("Composed label text 2")).toBeInTheDocument();
```

### What you did:

I ran the tests. I used voiceover in OSX 10.15.6 with Firefox.

### What happened:

It failed in the testing environment: 

> TestingLibraryElementError: Unable to find a label with the text of: Composed label text 2

However, it has the expected label with voiceover. 

### Reproduction:

https://codesandbox.io/s/loving-microservice-b6ltz?file=/src/__tests__/nested-label.test.js

### Problem description:

A label of an SVG can be composed from multiple elements via `aria-labelledby`. 

### Suggested solution:

Leverage `aria-labelledBy` when using `getByLabelText`

**Comment by alexkrolick** [comment]
The SVG is labelled by itself (it references it's own ID?

**Comment by juanca** [comment]
I think I figured it out. The `id` needs to be on the `title` element. When this is the case, the accessibility tree computes the correct `name` and voiceover does the right thing too. Aaaand, testing-library `getByLabelText` also works. 

```
const div = document.createElement("div");
div.innerHTML = `
<div>
  <div id="first">Composed</div>
  <svg aria-labelledby="first second">
    <title id="second">label text 2</title>
  </svg>
</div>`;

document.body.appendChild(div);
const { getByLabelText } = within(document.body);

expect(getByLabelText("Composed label text 2")).toBeInTheDocument();
```
