### ISSUE TITLE
Typo in 

### ISSUE THREAD

**Issue by slowselfip** [testing-library/dom-testing-library#761]
- `@testing-library/dom` version: 7.22.6
- Testing Framework and version: jest@24.9.0
  
- DOM Environment: jsdom 16.4.0
  

### Relevant code or config:

```js
import { configure } from '@testing-library/react';

configure({ showOriginalStackTrace: false });
```

### What you did:

I was going to configure the showOriginalStackTrace option and

### What happened:
I got the following typescript error:
```
Argument of type '{ showOriginalStackTrace: boolean; }' is not assignable to parameter of type 'Partial<Config> | ConfigFn'.
  Object literal may only specify known properties, and 'showOriginalStackTrace' does not exist in type 'Partial<Config> | ConfigFn'
```

### Problem description:
The Config interface contains a typo:
https://github.com/testing-library/dom-testing-library/blob/741096b5763c850ae26441343e14f83034231946/types/config.d.ts#L8

### Suggested solution:
Change showOriginalStrackTrace to showOriginalStackTrace.

**Comment by eps1lon** [comment]
@all-contributors add @slowselfip for bug
