### ISSUE TITLE
should getByRole('textbox') and getByRole('link') return elements with no role

### ISSUE THREAD

**Issue by dagda1** [testing-library/dom-testing-library#779]
I did ask [this question](https://discordapp.com/channels/723559267868737556/723559267868737559/763095180400001054) on discord first.

I really like react-testing library so this is not a criticism and may very well be my misunderstanding of how this should work,

I was surprised to learn that the following will return matches for elements that do not have these roles

```ts
getByRole('textbox');  // will match <input type="text">
getByRole ('link'). // will match <a class="" href="/foo">Foo</a>

document.querySelector('[role="textbox"]');  // null
document.querySelecotry('[role="link"]'); // null
```

The `textbox` role is for non-standard text input elements as is described [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/textbox_role#Examples).

e.g.

```html
<div role="textbox" contenteditable="true" aria-multiline="true"></div>
```

Same goes for `link`, you would use the link role on a button for example.   You should just use a button in reality.

This is because react-testing library uses [aria-query](https://github.com/A11yance/aria-query).

These selectors do not work in the browser and it feels wrong to use them like this.

It definitely could be me being wrong though.

**Comment by alexkrolick** [comment]
This is intentional - aria-query supports implicit roles, which is what you'll see if you open up the Accessibility tab in devtoools. When using `ByRole` (and the other queries, to some extent), you're traversing elements by querying the accessibility tree.

**Comment by dagda1** [comment]
every day is a school day.  thank you for that
