### ISSUE TITLE
Add option to silence `accessibility warnings`

### ISSUE THREAD

**Issue by smeijer** [testing-library/dom-testing-library#785]
### Describe the feature you'd like:
The accessibility warning is nice! But if I'm going to update the `testing-playground` chrome extension to use the latest version of `dom-testing-library`, it will start logging errors because of the `console.warn` expressions. The user won't see them in their console. Instead, they appear on the `extensions` page, looking like something in the extension was broken.

Can we add an option to silence that warning? I still want to have that `warning` attribute on the return value, I just don't want it to invoke `console.warn`.

https://github.com/testing-library/dom-testing-library/blob/8eebd9e5b264ed8435fd3f531a7d0eb112d3faa9/src/suggestions.js#L54-L60

Instead of adding an option, it might also make sense to simply move the printing higher up the tree.

![image](https://user-images.githubusercontent.com/1196524/95867638-aa034400-0d69-11eb-830a-a90d8f533524.png)

**Comment by eps1lon** [comment]
> Can we add an option to silence that warning? I still want to have that warning attribute on the return value, I just don't want it to invoke console.warn.

Can you mock out `console` in chrome extensions?

**Comment by smeijer** [comment]
Although I'm not a fan of modifying native methods (stubbing out), it does seem to work.

Is there a reason that your hesitant to adding the option or moving the `warn` higher up the tree? I mean, having a `console.warn` in a method named `makeSuggestion`, which is invoked by `getSuggestedQuery` already sounds like a questionable side effect to me.

**Comment by eps1lon** [comment]
> Is there a reason that your hesitant to adding the option or moving the warn higher up the tree? 

I'm hesitant to modify code in general for one-off use cases. Especially if it means adding options. I can ask you the same question: Is there a reason you're not a fan of modifying native methods?

That doesn't mean that we'll never do it. If it's a common use case then we can talk about different API proposals.

Could you explain why you want to silence the warning in the first place? In what scenarios would you consider it a false positive?

**Comment by smeijer** [comment]
> I'm hesitant to modify code in general for one-off use cases. Especially if it means adding options. 

Fair enough.

> Is there a reason you're not a fan of modifying native methods?

Because for the [chrome extension](https://chrome.google.com/webstore/detail/testing-playground/hejbmebodbijjdhflfknehhcgaklhano?hl=en) it means that I need to mock out `console.warn` in the `content-script`. In my current browser, I see that stubbing out `console.warn` in the content script, doesn't have any affect on the method in on the parent frame. But I don't know how other versions of Chrome, or even other chrome(-extension) compatible browsers will handle this.

> Could you explain why you want to silence the warning in the first place? In what scenarios would you consider it a false positive?

I don't consider the accessibility warning a `false positive`, but reporting it as an extension-error is. The `warn` is logged in two places.

1. The console in the current active page.
2. In the extension page, making the extension itself look buggy

My biggest concern is 2.

![testing-library-warn](https://user-images.githubusercontent.com/1196524/96098635-a50dd400-0ed2-11eb-96c1-f246957b23c4.gif)

**Comment by kentcdodds** [comment]
I think given the arguments given, adding global configuration for this is acceptable.

**Comment by savcni01** [comment]
I plan to work on this issue today.

**Comment by eps1lon** [comment]
Closing since there are no examples for false positives. This is purely a chrome extension issue and I'd rather not endorse the usage outside of this very specific use case.

Extensions should either mock out the console accordingly or create a fork that suites there use case.
