### ISSUE TITLE
ByLabelText does not work properly with output element

### ISSUE THREAD

**Issue by pawbor** [testing-library/dom-testing-library#787]
- `@testing-library/dom` version: 7.24.5
- Testing Framework and version: jest@26.5.2
  
- DOM Environment: jsdom@16.4.0
  

### Relevant code or config:

```js
describe('labeled output', () => {
  it('passes', () => {
    const root = render('<label>foo <output></output></label>');

    expect(getByLabelText(root, 'foo')).toBeInstanceOf(HTMLOutputElement);
  });

  it('fails', () => {
    const root = render('<label>foo <output>bar</output></label>');

    expect(getByLabelText(root, 'foo')).toBeInstanceOf(HTMLOutputElement);
  });

  it('passes too', () => {
    const root = render('<label>foo <output>bar</output></label>');

    expect(getByLabelText(root, 'foo bar')).toBeInstanceOf(HTMLOutputElement);
  });
});

function render(html: string) {
  const root = document.createElement('div');

  root.innerHTML = html;

  return root;
}
```

### What you did:

I want to find `output` element by its label

### What happened:

When `output` has text content it is not ignored during the scan.

### Reproduction:

- 

### Problem description:

It's impossible to find output by its label. 

### Suggested solution:

I think similar solution to [this](https://github.com/testing-library/dom-testing-library/blob/53829b8651bcea86410de73eeb81751b0f2ccae6/src/queries/label-text.js#L29) would be ok.

**Comment by eps1lon** [comment]
Relevant spec text:

> Some elements, not all of them form-associated, are categorized as labelable elements. These are elements that can be associated with a label element.
>
> button, input (if the type attribute is not in the Hidden state, )meter, output, progress, select, textarea, form-associated custom elements

-- https://html.spec.whatwg.org/multipage/forms.html#category-label
