### ISSUE TITLE
title.replaceAll is not a function

### ISSUE THREAD

**Issue by mikealizade** [testing-library/dom-testing-library#797]
- @testing-library/react@9.5.0
- Jest
- Chrome 86

### Relevant code or config:

```
const urlTitle: string = title.replaceAll(' ', '-');
```

### What you did:

Testing a product list page

### What happened:

TypeError: title.replaceAll is not a function

### Problem description:

replaceAll function not being recognised, but replace function is fine

**Comment by eps1lon** [comment]
That is almost certainly your environment. [`replaceAll`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) is a fairly new method and only available in latest browsers but no node version. So if you run your tests with `jest` you can't use `replaceAll`

**Comment by 3nuc** [comment]
You can just use https://github.com/es-shims/String.prototype.replaceAll

in package.json => {jest: { setupFilesAfterEnv: ["./src/utils/jestSetup.ts"]}}

jestSetup.ts
![image](https://user-images.githubusercontent.com/5359825/118659930-05108400-b7ee-11eb-86c9-eb506baea566.png)

**Comment by joelcross** [comment]
This works for me, thanks @3nuc! I like your changes in jestSetup.ts- it makes a lot of sense to have the shim method run only in the tests.

**Comment by Rafatcb** [comment]
Another option is to update Node.js version to v15 or higher

**Comment by ManhNV103** [comment]
The quickest fix is to use replace with regex.

`const urlTitle: string = title.replace(/ /g, '-');`
