### ISSUE TITLE
 Unable to find the "window" object for the given node. 

### ISSUE THREAD

**Issue by jasonburnell98** [testing-library/dom-testing-library#812]
I am mapping through json data file and have a tooltip to show the time when hovered over a chip in the component NoteLog

       <PaperTooltip data-testid={"hoverCreationTimeStamp"} content={formatDateTime(log.creationTimeStamp)} placement={"right-start"} >
                                        <Chip
                                            style={{ height: "100%" }}
                                            size="small"
                                            // avatar={log.firstname === "Jason" ? <EditDeleteNote /> : ""}
                                            // icon={() => editDeleteButton()}
                                            // onDelete={() => { console.log("delete") }}
                                            // deleteIcon={log.firstname === "Jason" ? <div>hello</div> : ""}

                                            label={<>
                                                <Typography data-testid={"content"} className={classes.noteWrap} variant={"overline"} align={"left"} component={"span"} display={"block"} gutterBottom >
                                                    <Typography data-testid={"categories"} className={classes.textAlign} gutterBottom align={"left"} variant={"subtitle2"}> {log.category}     {log.firstname === "first" && log.lastname === "last" ?
                                                        <div className={classes.wrapper}> <EditDeleteNote noteValue={log.data} categoryValue={log.category} OnChange={() => log.data} /></div>
                                                        : ""}
                                                    </Typography>
                                                    {log.data === null ? "" : log.data}

                                                </Typography>

                                            </>
                                            }
                                        />
                                    </PaperTooltip>

Trying to test that the tooltip is showing up properly:
  const setUpNoteLog = () => {
        return render(<NoteLog />)
    };
   test("Tooltip is showing exact time when hovered over with mouse", async () => {
        const { queryAllByTestId } = setUpNoteLog();
        const timeHovered = queryAllByTestId("hoverCreationTimeStamp");
        fireEvent.mouseMove(timeHovered);

        expect(await timeHovered).toBeInTheDocument();
    })
 Got this error: 
 Unable to find the "window" object for the given node.

**Comment by nickmccurdy** [comment]
This seems like more of an environment issue, as Testing Library doesn't implement or mock browser APIs externally. Can you please [make a sandbox](https://kcd.im/rtl-help) with the issue?

**Comment by MatanBobi** [comment]
I think that this one relies on `queryAllByTestId` returning an array and `fireEvent` expecting one node.
We did add a better [error message](https://github.com/testing-library/dom-testing-library/blob/master/src/helpers.js#L104) 
 for that case two months ago so I'm closing this one.
@jasonburnell98 If there's still anything we can do, please feel free to comment and I'll re-open it.
