### ISSUE TITLE
Input with invalid type does not have textbox role

### ISSUE THREAD

**Issue by florian-milky** [testing-library/dom-testing-library#814]
### Problem description:

According to spec:

input type=text or with a missing or invalid type, with no list attribute should have role=textbox
https://www.w3.org/TR/html-aria/

see repro https://codesandbox.io/s/react-testing-library-demo-forked-6mh5f

**Comment by MatanBobi** [comment]
Hi @florian-milky, thanks for opening this issue :)
If I understand the issue correctly, testing-library is only the testing framework and not the rendering engine, for issues with the rendering engine (probably jsdom) you should file an issue in [jsdom](https://github.com/jsdom/jsdom).
I see that they had an [issue](https://github.com/jsdom/jsdom/pull/2712) about something related to this already, I'm keeping this open cause I may have missed something so feel free to comment.
Thanks!

**Comment by eps1lon** [comment]
This is likely an issue with how we leverage aria-query or probably how aria-query maps elements. They probably declare that `input` is mapped based on the `type` **attribute** when it should be the `type` **property**:

```js
const input = document.createElement('input');
input.setAttribute('type', '123');

console.log(input.getAttribute('type'), input.type); // 123, text
```

In that example `input[type="text"]` would not match but the input's type is actually `text`.

**Comment by marcosvega91** [comment]
I have created a small example on jsfiddle https://jsfiddle.net/zw5401b8/1/

If the input has a not defined type or an invalid type the selector `input[type="text"]` will not work. Are we sure that it's our problem?

**Comment by florian-milky** [comment]
I used a screenreader to test out, and it recognized the `input type="123"` as a text field. I am not sure what to take from this but it was really crazy to use a screenreader 😆

**Comment by eps1lon** [comment]
> input[type="text"] will not work. Are we sure that it's our problem?

"will not work" needs some clarification. If you want to select textboxes then the selector is incorrect. If you want to select `<input />` with the `type` **attribute** set to `text` then it works. 

Two possible solutions to get textboxes:
1. get by `type` **property**
1. query with `input:not([type="number"]):not([type="password"])...etc`
 	 Though that might still not be robust enough (are attribute values case-sensitive? what about whitespace? )

**Comment by marcosvega91** [comment]
Yes, I think is better the first case. We can add here, instead of you the selector for this case

**Comment by florian-milky** [comment]
> This is likely an issue with how we leverage aria-query or how aria-query maps elements. They probably declare that `input` is mapped based on the `type` **attribute** when it should be the `type` **property**:
> 
> ```js
> const input = document.createElement('input');
> input.setAttribute('type', '123');
> 
> console.log(input.getAttribute('type'), input.type); // 123, text
> ```
> 
> In that example `input[type="text"]` would not match but the input's type is actually `text`.

Super interesting! I played a bit with that actually but I didn't find the `input.type`, good to know!

Thanks for the PR, it might save some headache to future developers :)

**Comment by CarlosHdez** [comment]
Hi, I'm seeing this behavior, although I'm not using `dom-testing-library` I only have `@testing-library/react` v11.2.2 and `@testing-library/jest-dom` v5.11.6, do I need to add this one to dependencies or does this fix needs to be implemented in one of those packages.
Thanks

**Comment by MatanBobi** [comment]
Hi @CarlosHdez!
`@testing-library/react` depends on `@testing-library/dom`, that's why you don't have it installed.
You can update `@testing-library/react` to the latest version and you'll get this fix.

Sorry it took us time to answer your question :)

**Comment by CarlosHdez** [comment]
I see, I didn't see this fixed in the notes from those repos so I was not sure an update would fix it, but if it does that would fix my problems. Thanks
