### ISSUE TITLE
getByDescriptionText

### ISSUE THREAD

**Issue by enagy27** [testing-library/dom-testing-library#815]
### Describe the feature you'd like:
I would love to have a `getByDescriptionText` and related queries for elements associated by `aria-describedby`.

### Teachability, Documentation, Adoption, Migration Strategy:
Code:
```
<label htmlFor="email">Email</label>
<input id="email" name="email" type="email" required="" aria-describedby="email-error" />
<p role="alert" id="email-error">Email is required</p>
```

Test:
```
expect(getByDescriptionText('Email is required')).toBeInTheDocument();
```

**Comment by kentcdodds** [comment]
Hi @enagy27!

Interesting thought. Can you explain a situation where querying by description text would be favorable? If it's about confidence that your description is correct, you could query by the label and then use [`toHaveDescription`](https://github.com/testing-library/jest-dom#tohavedescription).

**Comment by enagy27** [comment]
@kentcdodds oh! I don't know how I missed that, thank you!

I guess the other part to this could be separating out an individual description when we have multiple, though that could be an improvement to `toHaveDescription` instead. In my case I have helper text and error text, often at the same time. So for example:
```jsx
const { getByLabelText } = render(
  <TextField
    name="fullName"
    label="Full name"
    helperText="Your full, legal name"
    invalid
    validationText="Full name is required"
  />
);

const input = getByLabelText('Full name');
expect(input).toHaveDescription('Your full, legal name');
```

This would fail because there are multiple descriptions. Searching directly for one snippet of the description could resolve the ambiguity, but maybe the alternative request is to match individual descriptions 🤔

**Comment by enagy27** [comment]
Oh, thanks! I don't know how I missed that 😅 I think that covers my case.

I think the only benefit might be if searching this way could allow us to search for an individual description among multiple associated ids, but it's not the best way for me to test that. I could always try a regex instead.
