### ISSUE TITLE
Not being able to search by role textbox, when searching by name.

### ISSUE THREAD

**Issue by jean182** [testing-library/dom-testing-library#825]
- `@testing-library/dom` version: ^5.11.4
- Testing Framework and version: Jest 24.9.0
  
- DOM Environment: jest-environment-jsdom-fourteen 1.0.1
  

### Relevant code or config:

```js
test("React Testing Library works!", () => {
  const { getByRole } = render(<Hello />);
  expect(getByRole("textbox", { name: "releaseDate" })).toBeInTheDocument();
});
```

### What you did:

Trying to find an input with a textbox role and name attribute.

### What happened:

I'm getting this even though the match found has a name attribute.
<img width="573" alt="Screen Shot 2020-11-17 at 9 30 00 AM" src="https://user-images.githubusercontent.com/7577652/99410774-78c1ea80-28b8-11eb-8ab5-2f64f53bf60c.png">

### Reproduction:

Here's a minimal example, I know I can make it work with using only getByRole(''textbox") but I want to know how to deal with this when I'm using more than 1 input.
https://codesandbox.io/s/react-testing-library-demo-forked-79seh?file=/src/hello.js

### Problem description:

I don't know why name is empty even though the test is printing the input with the name attribute.

**Comment by eps1lon** [comment]
Sorry for the confusion. The `name` option filters by accessible name not by `name` attribute. For more details check out https://testing-library.com/docs/dom-testing-library/api-queries#byrole.
