### ISSUE TITLE
Can't fire a submit event using Nightwatch.js + Testing Library

### ISSUE THREAD

**Issue by lsoares** [testing-library/dom-testing-library#828]
"@testing-library/dom": "^7.26.7",
    "@testing-library/nightwatch": "^2.0.0",
    "@testing-library/user-event": "^12.2.2",
    "chromedriver": "^87.0.0",
    "nightwatch": "^1.5.1"

Node 12.19.0

Relevant code or config

```js
const { getQueriesFrom } = require('@testing-library/nightwatch')
const { fireEvent } = require('@testing-library/dom')

module.exports = {

  async 'Demo test ecosia.org'(browser) {
    await browser.url('https://www.ecosia.org/')

    const { getByPlaceholderText } = getQueriesFrom(browser)

    const searchBox = await getByPlaceholderText(/search the web to plant trees.../i)

    await browser.setValue(searchBox, 'nightwatch')
    await fireEvent.submit(searchBox);

    await browser.end()
  }
}

```

What you did:
`npm t -- tests/ecosiaSearchWithTL.js
`
What happened:

```
[Ecosia Search With TL] Test Suite
==================================
ℹ Connected to localhost on port 9515 (1061ms).
  Using: chrome (87.0.4280.66) on Mac OS X platform.

Running:  Demo test ecosia.org


FAILED: 1 errors (913ms)
   Error: Unable to find the "window" object for the given node. Please file an issue with the code that's causing you to see this error: https://github.com/testing-library/dom-testing-library/issues/new
       at Object.Demo test ecosia.org (/Users/lsr7759/projects/e2e/tests/ecosiaSearchWithTL.js:14:21)
       at processTicksAndRejections (internal/process/task_queues.js:97:5)
_________________________________________________

TEST FAILURE: 1 error during execution; 0 tests failed, 0 passed (2.642s)
```

Repo:
https://github.com/lsoares/e2e-nightwatchjs-testinglibrary

Above, I tried firing an event to submit the form. It failed... but [I also tried using `getByRole` but it also failed for other reason](https://stackoverflow.com/questions/64884748/getbyrole-in-nightwatch-testing-library-throws-error-in-basic-example). I think `getByRole` would be better though.

**Comment by kentcdodds** [comment]
@lsoares, I'm not sure what this could be but I'm guessing this is a `@testing-library/nightwatch` bug. I don't know anything about nightwatch, but my first guess would be that it's not properly injecting the script into the browser environment which is why `window` is unavailable 🤔

**Comment by lsoares** [comment]
@kentcdodds makes sense. I'm going to open an issue there. I tried a different approach but also, this seems to be another bug in Nightwatch right?
https ://stackoverflow.com/questions/64884748/getbyrole-in-nightwatch-testing-library-throws-error-in-basic-example

**Comment by kentcdodds** [comment]
Yeah, I'm afraid my experience with nightwatch is basically 0 so I can't really say much about it, but I doubt this issue is DOM Testing Library related. So I'm going to close this here.

Good luck!

**Comment by nickmccurdy** [comment]
@lsoares If you'd like I can move this to `@testing-library/nightwatch`'s issues.

**Comment by lsoares** [comment]
@nickmccurdy yes please
