### ISSUE TITLE
Support document.body initialized after importing screen

### ISSUE THREAD

**Issue by codeclown** [testing-library/dom-testing-library#831]
### Describe the feature you'd like:

Currently the exported `screen` binds itself to `document.body` at export-time:

https://github.com/testing-library/dom-testing-library/blob/f627ade1d8169db6113181a3893c847c10fa3ee2/src/screen.js#L41-L51

Which means that if document.body wasn't yet initialized, screen methods are not available later:

```js
import { screen } from '@testing-library/react'; // <- document.body bound to now
import jsdomGlobal from 'jsdom-global';

describe('something', () => {
  beforeEach(() => {
    jsdomGlobal(); // <- initializing document.body after screen was imported
  });

  it('works', () => {
    console.log(document.body); // => HTMLBodyElement {}
    screen.getByText('example'); // => throws "For queries bound to document.body [...]"
  });
});
```

### Suggested implementation:

Perhaps export a new function which looks up document.body live during each query-method, e.g.

```js
export const screen = () => ...;
// usage in tests:
screen().getByText('example');
```

### Describe alternatives you've considered:

A workaround is to setup a "screen" manually:

```js
import { within } from '@testing-library/dom';
let screen;
beforeEach(() => {
  jsdomGlobal();
  screen = within(document.body);
});
```

Or to include document.body in every get\* call:

```js
import { getByText } from '@testing-library/dom';
it('works', () => {
  getByText(document.body, 'example');
});
```

**Comment by kentcdodds** [comment]
Hey @codeclown,

99% of users of DOM Testing Library have a global document in place before they import anything. Making this kind of change would complicate things for the 99% case in favor of the 1% case. I'm sometimes ok with doing that if the workaround for the 1% is a big problem, but the workaround you've suggested seems fine to me. Put that in your own test utils module and you're golden. https://testing-library.com/docs/react-testing-library/setup

Thanks anyway, and good luck!

**Comment by DanKaplanSES** [comment]
I'm confused about the ramifications of "the exported screen binds itself to document.body at export-time." Does that mean `jsdom.reconfigure(...)` won't work correctly in tests? I have some tests where I want to perform some actions, change the "browser" address, and then run some expectations. 

By the way, is "the exported screen binds itself to document.body at export-time" documented anywhere? I may be doing something wrong, but isn't that important information for anybody not using an existing wrapper?
