### ISSUE TITLE
Adding playground link when a test fails

### ISSUE THREAD

**Issue by nofar9792** [testing-library/dom-testing-library#837]
### Describe the feature you'd like:

The playground link is really useful.
Each time `find`/`get` function fails, it prints a really long HTML.
Maybe you can add the playground link by default, each time 
1. `find`/`get` function fails
2. One of the `expect` fails. like `expect(element).toBeChecked();`

### Suggested implementation:

1. Adding the link to `getElementError`.
2. I would like to hear what do you think

**Comment by kentcdodds** [comment]
I think that's a pretty good idea personally. Maybe it could be disabled globally?

**Comment by AlonMiz** [comment]
That sounds like a great idea.

**Comment by delca85** [comment]
It sounds good to me too, it could be very useful but I agree with @kentcdodds that should be disabled globally.

**Comment by kentcdodds** [comment]
To be clear, I think it should be enabled by default. Just something you can disable globally.

**Comment by kentcdodds** [comment]
Also, to be clear further, anyone can claim this. Feel free to volunteer to implement this :)

**Comment by AmirTugi** [comment]
Ooo sounds neat.
I'd definitely wan't this in my pipeline.

Aren't the `expect`s standalone, and don't relate to any testing lib?
How can we put the the link in that case without binding `jest-dom` to `testing-library`?

**Comment by lidoravitan** [comment]
@kentcdodds i'd like to help with it

**Comment by kentcdodds** [comment]
Go for it 💯
