### ISSUE TITLE
Argument of type 'Element' is not assignable to parameter of type 'HTMLElement'.

### ISSUE THREAD

**Issue by Semigradsky** [testing-library/dom-testing-library#838]
- `@testing-library/react` version: 11.2.2

### Relevant code or config:

```tsx
	const { container } = render( // container is `Element` here
		<MyComponent/>,
	)

	expect(getByText(container, someText)).toBeInTheDocument() // Error: Argument of type 'Element' is not assignable to parameter of type 'HTMLElement'.
	expect(getByTestId(container, 'test-id')).toBeInTheDocument() // Error: Argument of type 'Element' is not assignable to parameter of type 'HTMLElement'.
```

### Problem description:

After testing-library/react-testing-library#833 I get type errors because `container` no more `HTMLElement`.

`container as HTMLElement` doesn't seem like a good solution.

**Comment by nickmccurdy** [comment]
`getByText` and `getByTestId` are being imported from DOM Testing Library, which hasn't been updated to match React Testing Library yet (you can [subscribe to the pull request for updates](https://github.com/testing-library/dom-testing-library/pull/834)). However it's recommended to only import from React Testing Library, which would fix this issue for you now, so I will close this.

There is also an unrelated issue with the runtime (not TypeScript) type checking in Jest DOM. I'll open another issue for that.
