### ISSUE TITLE
timeStamp in event created by `createEvent` is not used

### ISSUE THREAD

**Issue by atk** [testing-library/dom-testing-library#842]
- `@testing-library/react` version: 11.2.0
- Testing Framework and version: jest-26.0.15
  
- DOM Environment: jsdom-16.4.0
  

### Relevant code or config:

```js
import { createEvent } from '@testing-library/react'

test('event uses timeStamp', () => {
  const mockEvent = createEvent.click(document.body, { timeStamp: 1000000 })
  expect(mockEvent.timeStamp).toBe(1000000)
})
```

### What you did:

- used createEvent to create an event with a manipulated timeStamp

### What happened:

- the created event had a native timeStamp

### Reproduction:

See test case above

### Problem description:

Overwriting timeStamp is one of the documented use cases for createEvent, see https://testing-library.com/docs/dom-testing-library/api-events/#createeventeventname

### Suggested solution:

As a workaround, one can use Object.defineProperty(event, 'timeStamp', { value: 1000000 });

**Comment by atk** [comment]
Isn't this supposed to work as described in the [documentation](https://testing-library.com/docs/dom-testing-library/api-events/#createeventeventname)? Being able to overwrite timeStamp is one of the few reasons to use `createEvent` at all - so I think this is a fix rather than an enhancement.

However, the fix should be easy: one only needs to add `'timeStamp'` to the list of `dataTransferProperties` in https://github.com/testing-library/dom-testing-library/blob/master/src/events.js#L66

**Comment by eps1lon** [comment]
> Isn't this supposed to work as described in the [documentation](https://testing-library.com/docs/dom-testing-library/api-events/#createeventeventname)? 

It doesn't say you should be able to set these properties. Maybe we need to be clearer in the docs and replace "access" with "read".

**Comment by atk** [comment]
Which would be misleading too, as a few properties can be overwritten without using `Object.defineProperty`. Maybe it would be clearer if the docs said the access in question was based on the usual native event API and thus properties such as `timeStamp` needed to be modified by `Object.defineProperty` instead of being writable directly.

**Comment by drorheller** [comment]
Hi, I'd like to update the doc on this
