### ISSUE TITLE
After firing blur event on an input, unable to find the element by its (new) display value

### ISSUE THREAD

**Issue by andycarrell** [testing-library/dom-testing-library#845]
- `@testing-library/dom` version: 5.1..6
- `@testing-library/react` version: 11.2.2
- Testing Framework and version:
jest: v26.6 (via react-scripts v4.0.1)
- DOM Environment:
Default with jest?

### What you did:
I'm trying to test a custom input, which on blur formats the event value and sets state. The state value is used as the value for the input - standard controlled component pattern. 
I then try and query the DOM for an element by its display value, but it fails. 

### What happened:
The test can't find the input by its display value:

```
Unable to find an element with the display value: 123.00.

<body>
  <div>
    <input
      aria-label="my input"
      type="text"
      value="123.00"
    />
  </div>
</body>
```

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-forked-owbli?file=/src/__tests__/input.js

### Problem description:

An existing test setup as outlined here now breaks when I upgrade to React v17

### Suggested solution:

The query should be able to find an element with the display value of "123.00" since it's there in the DOM

**Comment by balavishnuvj** [comment]
@andycarrell input doesn't have a `change` event. I don't think the value of the input would be changed otherwise(maybe I'm wrong here). Does this work as expected in the browser?

a log on `input.value` didn't show the updated value. Maybe I am missing something.

https://codesandbox.io/s/react-testing-library-demo-forked-un9d8

**Comment by andycarrell** [comment]
Hi @balavishnuvj - it should update the value because the blur event sets the local state.

To get this test to pass I actually need to wrap the fireEvent in an `act` or `waitFor`:

```js
await waitFor(() => {
	fireEvent.blur(screen.getByLabelText("Currency input"), {
		target: { value: "123" },
	});
});
```

Will close this issue, sorry for wasting your time!
