### ISSUE TITLE
Node.innerText is undefined

### ISSUE THREAD

**Issue by Fi1osof** [testing-library/dom-testing-library#853]
- `@testing-library/dom` version: 7.28.1
- Testing Framework and version: jest@26.6.3
  
- DOM Environment: jsdom@16.4.0
  

### Relevant code or config:

```ts
    const newPid = "newParagraph";
    const newPtext = "New paragraph text";

    act(() => {
      const p = document.createElement('p');
      p.id = newPid;
      p.innerHTML = newPtext;

      expect(p).toMatchSnapshot();
      expect(p.innerText).toMatchSnapshot();
      expect(p.textContent).toMatchSnapshot();

      editableDivWithSection?.appendChild(p);

    });


    expect(contentProxyEditor).toMatchSnapshot();

    expect(newP?.innerHTML).toBe(newPtext);
    expect(newP?.textContent).toBe(newPtext);
    expect(newP?.innerText).toBe(newPtext);

```

### What you did:

I create new P tag and set inner content. Try to get p.innerText

### What happened:

Snap:
```
exports[`ContentProxy Render default view 3`] = `
<p
  id="newParagraph"
>
  New paragraph text
</p>
`;

exports[`ContentProxy Render default view 4 innerText`] = `undefined`;

exports[`ContentProxy Render default view 5 textContent`] = `"New paragraph text"`;
```

Tests result:
```
 ● ContentProxy › Render default view

    expect(received).toBe(expected) // Object.is equality

    Expected: "New paragraph text"
    Received: undefined

      121 |     expect(newP?.innerHTML).toBe(newPtext);
      122 |     expect(newP?.textContent).toBe(newPtext);
    > 123 |     expect(newP?.innerText).toBe(newPtext);

```

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-forked-twff7?file=/src/__tests__/hello.js

### Problem description:

It's not by MDN https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText

**Comment by marcosvega91** [comment]
Hi @Fi1osof thanks for reaching us :).

Unfortunately `innerText` is not implemented in `jsdom` see [here](https://github.com/jsdom/jsdom/issues/1245). 
I'll close the issue because I think that we can't do more here. If you need further assistance let me know :)

**Comment by Fi1osof** [comment]
@marcosvega91 thanks for answer!
