### ISSUE TITLE
Custom testIdAttribute ignored

### ISSUE THREAD

**Issue by amandapouget** [testing-library/dom-testing-library#874]
- `@testing-library/dom` version: 7.29.4
- Testing Framework and version: Jest
  
- DOM Environment:
  

### Relevant code or config:

```js
configure({ testIdAttribute: 'foobar' })
```

### What you did:

Happily seeing getByTestId work, then I bumped to this version of dom-testing-library, and it stopped working.

### What happened:

It's clearly ignoring the config and searching for the default `data-testid`:
`TestingLibraryElementError: Unable to find an element by: [data-testid="bar"...`

### Reproduction:

Use `configure({ testIdAttribute })` in any environment and see that it's broken now.

### Problem description:

Hundreds and hundreds of tests break.

### Suggested solution:

It's unfortunately hard to figure out where this broke because we get our dom-testing-library via @testing-library/react, which carets it, meaning it jumps from 7.27.1 -> 7.29.4. Somewhere in the commits in dom-testing-library between those two version numbers is the regression.

**Comment by amandapouget** [comment]
It seems that if you bump @testing-library/react to 11.2.2+, _you must also bump @testing-library/dom to the latest available version at the same time_. This is because @testing-library/react carets @testing-library/dom.

Resolves the issue.

Please update the documentation for the release notes for @testing-library/react 11.2.2 to indicate this dependency. Thank you!

**Comment by eps1lon** [comment]
Thanks for the report.

I definitely understand your frustration here. Let me quickly explain the problem.

`@testing-library/react` depends on `@testing-library/dom`. If you `configure` `@testing-library/react` you also configure **the version `@testing-library/react` uses** of `@testing-library/dom`. However, if you explicitly declare `@testing-library/dom` in your package.json it is not guaranteed that the version of `@testing-library/dom` you import is the same as `@testing-library/react` uses. 

In the current state you would have to guarantee that. We could make `@testing-library/dom` a peer dependecy of `@testing-library/react` but that would mean more setup steps required for users of `@testing-library/react`.

Could you share a reproducible example where this problem occurred and explain a bit more about how you use `@testing-library/react` and `@testing-library/dom`? Because "It seems that if you bump @testing-library/react to 11.2.2+, you must also bump @testing-library/dom to the latest available version at the same time." seems unintended.

We may just want to re-export everything from `@testing-library/dom` so that you don't have to install that separately.

**Comment by MatanBobi** [comment]
> Thanks for the report.
> 
> I definitely understand your frustration here. Let me quickly explain the problem.
> 
> `@testing-library/react` depends on `@testing-library/dom`. If you `configure` `@testing-library/react` you also configure **the version `@testing-library/react` uses** of `@testing-library/dom`. However, if you explicitly declare `@testing-library/dom` in your package.json it is not guaranteed that the version of `@testing-library/dom` you import is the same as `@testing-library/react` uses.
> 
> In the current state you would have to guarantee that. We could make `@testing-library/dom` a peer dependecy of `@testing-library/react` but that would mean more setup steps required for users of `@testing-library/react`.
> 
> Could you share a reproducible example where this problem occurred and explain a bit more about how you use `@testing-library/react` and `@testing-library/dom`? Because "It seems that if you bump @testing-library/react to 11.2.2+, you must also bump @testing-library/dom to the latest available version at the same time." seems unintended.
> 
> We may just want to re-export everything from `@testing-library/dom` so that you don't have to install that separately.

I think we already do re-export everything from `@testing-library/dom` [here](https://github.com/testing-library/react-testing-library/blob/master/src/pure.js#L119) and actually there's no real need to install `@testing-library/dom` as far as I remember and as far as the docs say [here](https://testing-library.com/docs/react-testing-library/intro/).

**Comment by eps1lon** [comment]
> as far as the docs say here.

Where does it say that you don't need to install `@testing-library/dom`? It's kind of implied that by `@testing-library/react` just working. But I can't find where it says that the importing from both libraries might be problematic concerning singletons (like `configure`).

**Comment by MatanBobi** [comment]
> > as far as the docs say here.
> 
> Where does it say that you don't need to install `@testing-library/dom`? It's kind of implied that by `@testing-library/react` just working. But I can't find where it says that the importing from both libraries might be problematic concerning singletons (like `configure`).

You're right about that one, I think that we don't mention that it might be problematic. Maybe we can implicitly state that there's no need to install `@testing-library/dom` since everything is already exported from `@testing-library/react`,
Wdyt?

**Comment by eps1lon** [comment]
> Maybe we can implicitly state that there's no need to install @testing-library/dom since everything is already exported from @testing-library/react,
Wdyt?

You mean "explicitly"? If not then I don't think that "implicit documentation" works.

It would still be nice to confirm if this is indeed the problem.

**Comment by MatanBobi** [comment]
> 
> You mean "explicitly"? If not then I don't think that "implicit documentation" works.

Yep, you're right, my bad :)

**Comment by amandapouget** [comment]
I suspect it got added in our case due to the eslint warning when importing configure:
```
import { configure } from '@testing-library/dom';
...
 1:1  error  '@testing-library/dom' should be listed in the project's dependencies. Run 'npm i -S @testing-library/dom' to add it
```

**Comment by amandapouget** [comment]
It could help to have a warning not to install dom directly if installing @testing-library/react?

**Comment by amandapouget** [comment]
At least in my repo, I can confirm this was the issue.

**Comment by eps1lon** [comment]
> I suspect it got added in our case due to the eslint warning when importing configure:

Why did you choose to import it from `@testing-library/dom` and not `@testing-library/react`?

**Comment by amandapouget** [comment]
similarly, these red herrings from eslint because of the usage in jest setup file:

  1:1  error  '@testing-library/react' should be listed in the project's dependencies, not devDependencies     import/no-extraneous-dependencies
  2:1  error  '@testing-library/jest-dom' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies

not really this repo's problem but it could help to doc that this is false

**Comment by eps1lon** [comment]
> 1:1 error '@testing-library/react' should be listed in the project's dependencies, not devDependencies import/no-extraneous-dependencies
2:1 error '@testing-library/jest-dom' should be listed in the project's dependencies, not devDependencies import/no-extraneous-dependencies

None of these mention `@testing-library/dom` though. Maybe your editor accidentally created the import of `@testing-library/dom`?

It sounds like false-positives of `import/no-extraneous-dependencies` not like an issue with our library. If you import something in a test (config) file then it seems appropriate to me to list it as a `devDependency`.

**Comment by alexkrolick** [comment]
That's a lint warning from the AirBnB lint config - they should really document when to disable it, e.g., for test files and local development scripts.

**Comment by JESii** [comment]
> I think we already do re-export everything from @testing-library/dom here and actually there's no real need to install @testing-library/dom as far as I remember and as far as the docs say here.

I'm seeing this same issue `@testing-library/react' should be listed in the project's dependencies, not devDependencies.`. I'm also using `airBnb`, I do not import `@testing-libdrary/dom` but I do import `@testing-library/jest-dom`

**Comment by MatanBobi** [comment]
> > I think we already do re-export everything from @testing-library/dom here and actually there's no real need to install @testing-library/dom as far as I remember and as far as the docs say here.
> 
> I'm seeing this same issue `@testing-library/react' should be listed in the project's dependencies, not devDependencies.`. I'm also using `airBnb`, I do not import `@testing-libdrary/dom` but I do import `@testing-library/jest-dom`

Hi @JESii, based on airbnb's config, if you're importing one of the libraries not from [one of these globs,](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L72) you'll get an error:
```
      'test/**', // tape, common npm pattern
        'tests/**', // also common npm pattern
        'spec/**', // mocha, rspec-like pattern
        '**/__tests__/**', // jest pattern
        '**/__mocks__/**', // jest pattern
        'test.{js,jsx}', // repos with a single test file
        'test-*.{js,jsx}', // repos with multiple top-level test files
        '**/*{.,_}{test,spec}.{js,jsx}', // tests where the extension or filename suffix denotes that it is a test
        '**/jest.config.js', // jest config
        '**/jest.setup.js', // jest setup
        '**/vue.config.js', // vue-cli config
        '**/webpack.config.js', // webpack config
        '**/webpack.config.*.js', // webpack config
        '**/rollup.config.js', // rollup config
        '**/rollup.config.*.js', // rollup config
        '**/gulpfile.js', // gulp config
        '**/gulpfile.*.js', // gulp config
        '**/Gruntfile{,.js}', // grunt config
        '**/protractor.conf.js', // protractor config
        '**/protractor.conf.*.js', // protractor config
        '**/karma.conf.js', // karma config
        '**/.eslintrc.js' // eslint config
```
My guess is that you're importing `@testing-library/jest-dom` in a setup file which doesn't match the format airbnb expect..

**Comment by eps1lon** [comment]
This issue looks like there's nothing actionable for us. If you do want to also explicitly use `@testing-library/dom` then it's somewhat implied that you control its version. After all, it might be intended that you use a different version of `/dom` compared to the version `/react` is using.

**Comment by czabaj** [comment]
Happened to me today again. For further readers, if you are using Yarn, simply check that you have only one version of `@testing-library/dom` with 

```
yarn why @testing-library/dom
```

If it discovers more than one version, try to upgrade its dependants and when it's not possible, try [Yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)

```json
"resolutions": {
    "@testing-library/dom": "preferred version"
},
```

**Comment by unbugx** [comment]
> If it discovers more than one version, _upgrade all dependants_ and when it's not possible, try [Yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)

Unfortunately, it didn't help me. So I downgraded to @testing-library/dom@8.0.0 since this version is used by @testing-library/react
