### ISSUE TITLE
input is treated as non-labellable

### ISSUE THREAD

**Issue by IanVS** [testing-library/dom-testing-library#877]
- `@testing-library/dom` version: 7.29.4
- Testing Framework and version: mocha 5.2.0
  
- DOM Environment: jsdom 11.0.0
  

### Relevant code or config:

```js
const content = render(
    <PaymentInfoForm
        initialPaymentInfo={US_PAYMENT_INFO}
        isMSP={false}
        recurlyPublicApiKey="blah blah blah"
        xsrfToken="totally secure token"
        recurly={mockRecurly}
        showTaxSection
    />
);

assert.equal(
    content.getByLabelText('First name').value,
    "Frank"
);
```

The relavant section of rendered output is:

```
<label
  class="m--form-field-legend --is-required"
  for="first_name"
>
  First name
</label>
<div class="m--form-field ">
  <ul class="error-list" />
  <div class="text ">
    <input
      class="l--field--height-default l--field--width-default"
      data-recurly="first_name"
      id="first_name"
      name="first_name"
      required=""
      type="text"
      value="Duo"
    />
  </div>
</div>
```

### What happened:

I got an error: 

```
TestingLibraryElementError: Found a label with the text of: First name, however the element associated with this label (<input />) is non-labellable [https://html.spec.whatwg.org/multipage/forms.html#category-label]. If you really need to label a <input />, you can use aria-label or aria-labelledby instead.
```

I can't tell why the input is not labellable.  It doesn't have a `type` of `hidden`, which seems to be the only reason it could be.

### Problem description:

It is preventing me from upgrading from a very old version of react-testing-library.

**Comment by MatanBobi** [comment]
Hi @IanVS!
Thanks for opening this one :)
Could you please attach a full reference of the DOM or maybe reproduce it in a [codesandbox](http://kcd.im/rtl-help)?

**Comment by eps1lon** [comment]
I suspect that the input is not reachable from the container of the label considering 

https://github.com/testing-library/dom-testing-library/blob/5831f608bb0225233f1d8c5aa555328ca0c72b0b/src/queries/label-text.js#L120

Given the component name `PaymentInfoForm` the input is probably in an iframe. I'm not sure if labels can label inputs from another iframe. Though generally `getTagNameOfElementAssociatedWithLabelViaFor` should use the `ownerDocument` of the label not the container.

**Comment by IanVS** [comment]
This is super strange.  It's not an iframe, and I've simplified it down and created a minimal repro.  I am not able to trigger the failure in codesandbox, but I can if I clone the github repo and `yarn test` in my terminal.

The codesandbox is https://codesandbox.io/s/focused-dust-9cybr
and the repo is at https://github.com/IanVS/testing-library-877

This is what I get from a `yarn test` (similar with npm as well):

```
▶ yarn test
yarn run v1.22.10
$ mocha ./src/index.test.js --require=./test-setup.js --require=./babel-register.js --ui=tdd


  1) Renders a label

  0 passing (36ms)
  1 failing

  1) Renders a label:
     TestingLibraryElementError: Found a label with the text of: First name, however the element associated with this label (<input />) is non-labellable [https://html.spec.whatwg.org/multipage/forms.html#category-label]. If you really need to label a <input />, you can use aria-label or aria-labelledby instead.

<body>
  <div>
    <div>
      <label
        for="first_name"
      >
        First name
      </label>
      <input
        id="first_name"
        name="first_name"
        type="text"
        value=""
      />
    </div>
  </div>
</body>
      at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:37:19)
      at getAllByLabelText (node_modules/@testing-library/dom/dist/queries/label-text.js:111:40)
      at /Users/ivanschooten/src/test/testing-library-877/node_modules/@testing-library/dom/dist/query-helpers.js:62:17
      at getByLabelText (node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
      at Context.<anonymous> (src/index.test.js:21:11)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by IanVS** [comment]
It looks like codesandbox always uses jest, so that might explain the difference.  Not sure why jest and mocha would behave differently in this way, though.

**Comment by IanVS** [comment]
OK, knowing that codesandbox wasn't executing my mocha + jsdom was a good clue.  I was able to narrow this down to jsdom versions less than 11.11.0.  Upgrading to that version solves this error.  https://github.com/jsdom/jsdom/blob/master/Changelog.md#11110

Hopefully this issue report will be useful for anyone else who hits this error.

**Comment by MatanBobi** [comment]
Thanks for the thorough explanation @IanVS!
