### ISSUE TITLE
WebdriverIO testing library

### ISSUE THREAD

**Issue by olivierwilkinson** [testing-library/dom-testing-library#878]
### Describe the feature you'd like:

I absolutely love the API provided by DOM Testing Library, we use React Testing Library at work and it has improved our tests so much. For our E2E testing we use [WebdriverIO](https://webdriver.io/). I was looking for ways to use the DOM Testing Library API in our E2E tests and found [Nightwatch Testing Library](https://github.com/testing-library/nightwatch-testing-library), [Puppeteer Testing Library](https://github.com/testing-library/pptr-testing-library) and [TestCafe Testing Library](https://github.com/testing-library/testcafe-testing-library).

It would be great to see a version of DOM Testing Library that works with [WebdriverIO](https://webdriver.io/).

### Suggested implementation:

Because I was interested I decided to implement something myself 😄. I have an initial version based heavily off of Nightwatch Testing Library. I tried to keep the API and tests as similar as possible. Here is the repo, I've added some more information in the readme: https://github.com/olivierwilkinson/webdriverio-testing-library.

### Describe alternatives you've considered:

My original thought was to use Puppeteer Testing Library with WebdriverIOs underlying puppeteer instance but there are some limitations:
- Puppeteer is not always available

Puppeteer is used when the tests are run locally and there is no browser driver detected at `localhost:4444`. This means the Puppeteer instance isn't available in some setups (including mine).

- Unable to use WebdriverIO specific APIs

APIs like `Element.waitForDisplayed` are no longer available since the queries return Puppeteer ElementHandles.

### Teachability, Documentation, Adoption, Migration Strategy:

If this is something [Testing Library](https://github.com/testing-library) would like to maintain I would happily transfer ownership of the repo. I made sure to keep the same packages, setup and workflows from Nightwatch Testing Library so hopefully that wouldn't be a hassle. I'm also very happy to maintain and publish the package if this isn't something Testing Library wants to pursue, in which case I would appreciate some direction in terms of attribution as I don't want to step on anybody's toes.

Thanks in advance for any help/feedback you can give me here!

**Comment by nickmccurdy** [comment]
I'm not personally familiar with WebdriverIO, but this does sound like something that would be useful to have in the organization. Would you like to request a transfer to the organization? Then we can give you permissions for it. I'm not sure about how publishing would work though, as we have semantic release bots manage that.

**Comment by nickmccurdy** [comment]
> I tried to transfer ownership to testing-library but it says I need to have permission to create public repos. 

Oops, I forgot about that restriction.

> Would you like me to transfer ownership to you so you can transfer it on to testing-library?

Sure thanks, I'll see if I can take care of it.

**Comment by olivierwilkinson** [comment]
Ok great, I've requested to transfer ownership to you 👍 

Thanks for taking care of this 😄

**Comment by nickmccurdy** [comment]
Whoops sorry, I didn't respond to the invitation in time and it expired. Could you please try again?

**Comment by olivierwilkinson** [comment]
No worries haha, I'll request it again now.

**Comment by nickmccurdy** [comment]
Thanks, I've completed the transfer into @testing-library and given you admin permissions.

If you'd like to [join the Discord](https://discord.gg/testing-library) we can ask the other maintainers about how to handle releases, as I'm not sure how to handle that myself. I can try to help with anything else though.

**Comment by olivierwilkinson** [comment]
Brilliant, Thanks so much for organising all of this!

I'll look into both of those tonight. I'll be sure to get in contact if I'm struggling, thank you for the offer 😄

**Comment by MatanBobi** [comment]
@nickmccurdy Do you think we should also open a new Discord channel for WebdriverIO?

**Comment by nickmccurdy** [comment]
> @nickmccurdy Do you think we should also open a new Discord channel for WebdriverIO?

Good idea, I forgot about this. There's now a `webdriverio` channel. Here's the public invite link: https://discord.gg/AGyFvEKRqQ

@olivierwilkinson Most of our libraries have an emoji for branding purposes, do you want to pick one?

**Comment by olivierwilkinson** [comment]
> @olivierwilkinson Most of our libraries have an emoji for branding purposes, do you want to pick one?

Oh definitely! How about a spider 🕷️? it works with the 🕸️ part of WebdriverIO.

**Comment by nickmccurdy** [comment]
Good idea. I've added it to the Discord and readme.

**Comment by MatanBobi** [comment]
Since WebdriverIO is now a part of the testing-library organisation, I'm closing this one :)
For future visitors, the repo is [here](https://github.com/testing-library/webdriverio-testing-library).
Thanks!
