### ISSUE TITLE
Add global hook to handle elements result of all query types

### ISSUE THREAD

**Issue by ysfaran** [testing-library/dom-testing-library#882]
### Describe the feature you'd like:

Currently it's not possible to hook into query executions (at least it's not simple). You can write [Custom Queries](https://testing-library.com/docs/dom-testing-library/api-custom-queries/) but it's really cumbersome to adapt **all** query types for one and the same concern.

Imagine you want to add an option to verify that an element is fully visible. What I mean with fully visible is,  that the element must not have `display: none`, `opacity: 0` or `visibility: hidden` and also none of its parents. At the moment you have no (simple) way to integrate such a check in every query type.

### Suggested implementation:

> DISCLAIMER: This is just a rough idea. I appreciate any suggestions and improvement.

First of all the end user needs to specify a handler:

```js
function customHandleElements (elements, { container, name, text, options }){
    if(options.fullyVisible){
        return elements.filter(isFullyVisible)
    } else {
      return elements
    }
}
```

This function receives following arguments:

- `elements`: all queried elements (in other words: the result of a `queryAllBy*` call)
- second argument is an object with few properties:
  - `container`: container element which was passed to the original query
  - `name`: name of the query (e.g. `"queryByText"` or `"findAllByRole"`)
  - `text`: `TextMatch` which was passed to the to original query
  - `options`: options passed to the original query. It's important to note here that the end user could pass **any custom option**
  - (maybe even more)

This `customHandleElements` function can then be passed to the [Global Configuration](https://testing-library.com/docs/dom-testing-library/api-configuration):

```js
import { configure } from '@testing-library/dom'
import { customHandleElements } from './customHandleElements'

configure({
 handleElements: customHandleElements
})
```

Then the `handleElements` from the configuration would be called in every `queryAllBy*` function.

An example for [queryAllByAltText](https://github.com/testing-library/dom-testing-library/blob/master/src/queries/alt-text.js):

```js
function queryAllByAltText(
  container,
  alt,
  {exact = true, collapseWhitespace, trim, normalizer} = {},
) {
  checkContainerType(container)
  const matcher = exact ? matches : fuzzyMatches
  const matchNormalizer = makeNormalizer({collapseWhitespace, trim, normalizer})
  const elements = Array.from(container.querySelectorAll('img,input,area')).filter(node =>
    matcher(node.getAttribute('alt'), node, alt, matchNormalizer),
  )
  
  return config.handleElements(elements, /* ... */) // <- that's the main change
}
```

Finally queries could be used like so: 

```js
getByText(document, "text", { fullyVisible: true })
findAllByRole(document, "button", { fullyVisible: true })
// should work for any query
```

### Describe alternatives you've considered:

If the original `queryAll*` functions would be exported e.g.:

https://github.com/testing-library/dom-testing-library/blob/5bc93643f312d9ca4210b97681686c9aa8a902d7/src/queries/text.js#L12

then the end user could wrap it in another function (which adds the extra functionality, e.g. as `fullyVisible` above) and call `buildQueries` with this new function.  
IMHO this is not ideal since you would need do it again for every query type. You would also need to export `getMultipleError` and `getMissingError` for each query.

### Teachability, Documentation, Adoption, Migration Strategy:

As I searched in [Custom Queries](https://testing-library.com/docs/dom-testing-library/api-custom-queries/) docs when i was trying to find a solution for this issue, I would simply add another section on this page.  
This should not be a breaking change.

I'd be keen to make a PR once my feature request has been approved :)

**Comment by tigerabrodi** [comment]
Thanks for the feature request :blue_heart: 

Regards to the queries you mentioned, with the option `fullyVisible`:

```js
getByText(document, "text", { fullyVisible: true })
findAllByRole(document, "button", { fullyVisible: true })
```
A similar discussion happened here (scroll): https://github.com/testing-library/user-event/issues/475#issuecomment-723591541

I would cover it with Cypress, an example would be: https://github.com/cypress-io/cypress/issues/877#issuecomment-490504922

That would also give us more confidence, due to testing on a real browser compared to jsdom.

**Comment by ysfaran** [comment]
I'm actually using puppeteer and I also wrote some code that is checking full visibility 🙂 

The issue I see especially happens with `findBy*` queries (but it could also happen in another way with other queries):

```js
// this obviously could resolve even if the element is not fully visible
const elementHandle = await findByText("mytext")
const isFullyVisible = someUtils.isFullyVisible(elementHandle)
```

So the problem here is that I would need to wrap `const isFullyVisible = someUtils.isFullyVisible(elementHandle)` in some kind of loop to really wait until it's fully visible. In the meanwhile the `elementHandle` could've been disposed for some reason.

Another idea would be to wrap the whole statement in some kind of loop and use `queryBy*`:

```js
await waitForExpect(() => {
  const elementHandle = queryByText("mytext")
  const isFullyVisible = someUtils.isFullyVisible(elementHandle)
  expect(isFullyVisible).toBe(true)
})
```

But that's what I mean with: it's not simple. If you would like to add multiple global options it gets quite cumbersome to abstract this behaviour and you loose the prettiness and readability of Testing Library. How would you extract such a logic and still maintain the beauty of Testing Library syntax? 😕 

Please don't take the `fullyVisible` example too serious, it's a general issue IMO. This feature makes Testing Library more extensible without breaking anything especially for libraries which are built on Testing Library.

**Comment by ysfaran** [comment]
I actually found out [playwright](https://playwright.dev/) exists and moved away from puppeteer. playwright comes with much better testing utilites and built-in auto-wait for elements, so my actual problem with `fullyVisible` is not relevant for me anymore.

IMHO this feature is still a good idea as I already stated. I'm open for other opinions of course 🙂

**Comment by eps1lon** [comment]
This feature can be implemented with composition i.e. wrapping testing-library queries with custom functions. Not every possible composition needs to be implemented in this library.

For a more specific reason we have to consider the primary environment `@testing-library/dom` is running in: `jsdom`. In `jsdom` you cannot compute layout like you would do in a browser and other visibility related styles are also not fully implemented (`color`, `opacity`, `display` etc). So even if we would decide on a definition of `fullyVisible`, it likely causes more confusion in `jsdom`.

Furthermore, `fullyVisibile` is an ambigious term. Do you consider opacity, dimensions, font, color etc? I think this is better solved in your codebase depending on what you find frequently fails.
