### ISSUE TITLE
test: Leaking test

### ISSUE THREAD

**Issue by ph-fritsche** [testing-library/dom-testing-library#884]
- `@testing-library/dom` version: master = v7.29.4

### Relevant code or config:

This test leaks `setTimeout` so that tests added below are not run by jest.
https://github.com/testing-library/dom-testing-library/blob/5bc93643f312d9ca4210b97681686c9aa8a902d7/src/__tests__/helpers.js#L78

### What you did:

Added tests for a pull request.

### What happened:

Jest fails to `setTimeout` for subsequent tests.
Adding a `describe` block with `test`, the tests are ignored without error messages.
Adding a `describe` block with `test.only` reveals the problem.

### Suggested solution:

Enclose the tests in a `describe` block and define `beforeAll`/`afterEach` to properly clean up after the test.

**Comment by eps1lon** [comment]
Good catch. A PR would be appreciated!
