### ISSUE TITLE
Can't run testing when use social login

### ISSUE THREAD

**Issue by phuongit0301** [testing-library/dom-testing-library#891]
In my project has use third party - social login (facebook, google login). When I run test then it show errors like images attach and my code in [Codesandbox](https://codesandbox.io/s/clever-haibt-37ijt?file=/src/App.js). Can you have more ideas or suggest for me?

<img width="663" alt="Screen Shot 2021-02-14 at 09 14 38" src="https://user-images.githubusercontent.com/3425152/107882360-55402780-6f1b-11eb-9f25-32039d465df0.png">
<img width="1022" alt="Screen Shot 2021-02-14 at 09 21 50" src="https://user-images.githubusercontent.com/3425152/107882362-5a04db80-6f1b-11eb-90e8-6510b68257bd.png">

**Comment by eps1lon** [comment]
For questions please use [our discord](http://testing-library.com/discord).
