### ISSUE TITLE
`clearImmediate is not defined` error when using new v7.29.5 via cypress

### ISSUE THREAD

**Issue by kschiffer** [testing-library/dom-testing-library#899]
- `@testing-library/dom` version: 7.29.5
- Testing Framework and version: cypress 4.11.0
- DOM Environment:
 Cypress Chrome 88

### Relevant code or config:

Running any cypress test that uses `@testing-library/cypress`.

### What you did:

Running cypress tests which worked before the update.

### What happened:

```
 1) An uncaught error was detected outside of a test:
     ReferenceError: The following error originated from your test code, not from Cypress.

  > clearImmediate is not defined
```

### Reproduction:

Running any cypress test that uses `@testing-library/cypress`.

### Problem description:

The error originates from here: https://github.com/testing-library/dom-testing-library/commit/ac9a6b78968e39547d1383e51f74752259fbe2f2#diff-49ba0c85360693b8e89ae0e0428284a55db749f08f2b9993d26910def646e02fR13

It appears like `dom-testing-library` assumes that `clearImmediate` and `setImmediate` are globally available, but it appears to be available in [Internet Explorer 10 only](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate).

### Suggested solution:

I don't have time to look into why `setImmediate` is used in the first place, but I suppose that `setImmediate` needs to be removed or at least polyfilled before `dom-testing-library` uses it in the global scope.

**Comment by eps1lon** [comment]
Thanks for the report.

Could you try if this still happens with `@testing-library/dom@7.29.6 `?

If the issue persists then we would need a reproduction to debug the issue. A link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by JBWatenbergScality** [comment]
Hello,

I had a similar issue and I confirm that by upgrading `@testing-library/dom` to `7.29.6` it solves it.

Thanks for the fix !

**Comment by eps1lon** [comment]
Waiting for @kschiffer to confirm or if there's no response within 7 days.

**Comment by kschiffer** [comment]
I can confirm that the issue is resolved. Thanks for the swift action and for this awesome library \<3.
