### ISSUE TITLE
"Please file an issue with the code that's causing you to see this error"

### ISSUE THREAD

**Issue by jdevries3133** [testing-library/dom-testing-library#911]
# Edit

**Please see my last comment – this is a case of beginner's confusion but maybe a bit of a confusing error message as well.**

- `@testing-library/dom` version: 7.30.0
- Testing Framework and version: @testing-library/react ^11.2.5
  
- DOM Environment: jest / jestdom
  

Relevant code or config

https://github.com/jdevries3133/song_maker_gallery/blob/12fcc5be423a8cdac1a439e9e35d8e6ab1fe9bc9/django_smg/frontend/src/components/teacher/teacher.test.js#L44

What you did: Working on some tests; I am still very new to testing-library and unit testing with React overall.

What happened:

I got this error message, so am opening an issue as requested:

```
Unable to find the "window" object for the given node. Please file an issue with the code that's causing you to see this error: https://github.com/testing-library/dom-testing-library/issues/new
```

Reproduction repository:
https://github.com/testing-library/dom-testing-library-template

Problem description: I got an error asking to open an issue.

Suggested solution: Who knows, but I hope this can help you trace down a bug if there is one. Let me know if you'd like any additional information.

**Comment by jdevries3133** [comment]
Full traceback:

<img width="1440" alt="Screen Shot 2021-03-18 at 10 47 18 PM" src="https://user-images.githubusercontent.com/58614260/111725160-ef59ff00-883c-11eb-904a-85092188a76d.png">

**Comment by MatanBobi** [comment]
Hi @jdevries3133, thanks for opening this :)
What would you think should be the error in that case?
The issue was that you passed in the `screen` object which is basically an object we create that contains all the queries attached to the `document.body`. That in fact really isn't a DOM node so it can't find the window attached to it.

**Comment by jdevries3133** [comment]
Yes, the first part of the error is good and accurate, I just don't think it should solicit a GitHub issue since it's a case of user error. It made me think that I had caused an unexpected exception and uncovered a problem in the library when that obviously wasn't the case.

**Comment by MatanBobi** [comment]
We can make a better error message here, maybe checking if the element is in fact an HTML element and only then ask the user to file an issue.

**Comment by savcni01** [comment]
I plan to work on this issue today.
