### ISSUE TITLE
Feature Request: waitForStableRender

### ISSUE THREAD

**Issue by RossKinsella** [testing-library/dom-testing-library#928]
### Describe the feature you'd like:

I would like a function waitForStableRender(maxWaitMs?: number): Promise<boolean>
It would be used in similar situations as waitFor, except instead of specify what you're waiting for, it will just stall execution until the react tree has been stable for some arbitrary period of time.

The reason I want this is I am feeling pain when trying to test complex components which have a number of internal setup steps. 
For example, I have a component: SingleMetricDateMatrix which I am working on at the moment which does the following:
1) Grabs some configuration data via a hook
2) Makes a call to a backend to get some reporting data via a hook
3) When the data from (2) comes back, another hook will prepare a grid definition to reflect the pattern of the data
4) Build an AG grid with the items from above

At the moment, to make the testing library wait long enough for these side effects to complete, I am doing the following:
```
    await waitFor(() => screen.queryByText(mockedGadget.name));
    await waitFor(() =>
      expect(screen.queryByText('No Rows to Show')).toBeNull(),
    );
    await waitFor(() =>
      expect(screen.queryByRole('gridcell', { name: 'Apple' })).toBeVisible(),
    );
```

This is quite painful. I'd like to just tell the testing library "Wait until the renders stop happening"

### Describe alternatives you've considered:

A way to do something like this today is the following:
await act(() => new Promise(r => setTimeout(r, 3000)));

However, I feel this has a lot of room for introducing flakiness to the test suite

### Teachability, Documentation, Adoption, Migration Strategy:

I think this could just be one more option available here:
https://testing-library.com/docs/dom-testing-library/api-async/#waitfor

**Comment by timdeschryver** [comment]
I think that you should use the `findBy` query for this.
`waitFor` should be used to wait on an action that doesn't infect the DOM, e.g. wait until a spy has been called.

**Comment by RossKinsella** [comment]
Thanks Tim, I plugged that into the test in question and it a lot cleaner!

I still feel it is worth considering a "waitForStableRender" command

**Comment by kettanaito** [comment]
While a utility like `waitForStableRender` looks practical, I think it leaks implementation details ("render") into tests. You should always prefer awaiting UI elements whose appearance or disappearance corresponds to the state of "stable render" defined by your UI. That way you're putting yourself in the user's shoes, writing tests like

```ts
await waitFor(() => {
  // The "stable render" is finished when the user greeting is printed out.
  // That's also how the user would know that the UI is ready.
  expect(screen.findByText('Hello, John!')).toBeVisible()
})
```

Moreover, the state of "stable render" is rather abstract and, in my opinion, shouldn't be evaluated by this library. React may perform an arbitrary number of internal re-renders that are perfectly fine. Asserting such rendered state may be tight on performance.
