### ISSUE TITLE
getByRole('form') should work without "name" attribute

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/dom-testing-library#937]
- `@testing-library/dom` version: all
- Testing Framework and version: Any
- DOM Environment: Any

### Relevant code or config:

```js
// this passes, and that's great:
test('form with name', () => {
  const form = document.createElement('form')
  form.name = 'anything'
  const container = document.createElement('div')
  container.append(form)
  within(container).getByRole('form')
})

// this fails, but I think it should pass:
test('form without name', () => {
  const form = document.createElement('form')
  const container = document.createElement('div')
  container.append(form)
  within(container).getByRole('form')
})
```

### What you did:

Originally I thought that a form didn't actually have the accessible role "form" unless they had a name, but I just did a quick check in the devtools and that appears to not be the case:

![image](https://user-images.githubusercontent.com/1500684/116477445-dbd98500-a839-11eb-9366-e6c87390417a.png)

I did a bit of research and it appears there aren't any strong reasons to use a `name` attribute for a form, so it seems an odd limitation for us to have.

### What happened:

Test fails.

### Reproduction:

Put the above snippet in any jest environment you have working with testing library.

Alternatively, you'll find the same behavior in the browser as well: https://jsbin.com/ceyifo/edit?html,output

```html
<!DOCTYPE html>
<html>
<head>
  <script src="https://unpkg.com/@testing-library/dom@7.30.4/dist/@testing-library/dom.umd.js"></script>
</head>
<body>
  <div>Check the console</div>
  <script>
    function withName() {
      const form = document.createElement('form')
      form.name = 'anything'
      const container = document.createElement('div')
      container.append(form)
      TestingLibraryDom.within(container).getByRole('form')
    }
    
    function withoutName() {
      const form = document.createElement('form')
      const container = document.createElement('div')
      container.append(form)
      TestingLibraryDom.within(container).getByRole('form')
    }
    
    try {
      withName()
      console.log('withName passes')
    } catch (error) {
      console.error('withName fails', error)
    }
    try {
      withoutName()
      console.log('withoutName passes')
    } catch (error) {
      console.error('withoutName fails', error)
    }
  </script>
</body>
</html>
```

### Problem description:

It seems odd to me that a form requires a `name` attribute to be retrievable by a role query when it appears that the browser considers it to have a role of `form`.

### Suggested solution:

Update `getByRole` to match forms without a `name`.

**Comment by mt9eet** [comment]
@kentcdodds I think this is expected, or at least that's what the [spec](https://www.w3.org/TR/html-aria/#docconformance) says.

<img width="802" alt="Screen Shot 2021-05-02 at 05 37 49" src="https://user-images.githubusercontent.com/82734065/116796678-956d7a00-ab08-11eb-992b-320f04e9a69d.png">

**Comment by kentcdodds** [comment]
Ah! That's interesting. So this sounds more like a bug in Chrome's accessibility devtools than a DTL bug 😅

Thanks for finding that @mt9eet! 👏

**Comment by MatanBobi** [comment]
@ahsatha thanks for reaching out.
This issue you're experiencing isn't really related to the one described in this issue.
The reason you're seeing this is because the `name` attribute on a `form` doesn't represent the **accessible name**.
You can read in the [accessible name computation spec](https://www.w3.org/TR/html-aam-1.0/#accessible-name-and-description-computation). If I'm not mistaken, you need an `aria-label` an `aria-labelledyby` or a `title`.
![image](https://user-images.githubusercontent.com/12711091/137258376-c93b43b5-9090-400d-89d3-d8c19cfd8d46.png)

**Comment by challet** [comment]
> ![image](https://user-images.githubusercontent.com/12711091/137258376-c93b43b5-9090-400d-89d3-d8c19cfd8d46.png)

Setting a `title` still makes the form hidden from `getByRole("form")`

**Comment by MatanBobi** [comment]
Thanks @challet. This looks like an issue with `aria-query`: https://github.com/A11yance/aria-query/blob/main/src/etc/roles/literal/formRole.js

Maybe @jlp-craigmorten will know?

**Comment by jlp-craigmorten** [comment]
Exactly as @MatanBobi suggests, the role of `form` currently constraints set within `aria-query` which only cater to:

1. `aria-label`
2. `aria-labelledby`
3. `name`

it seems. So `title` is not being considered.

See also https://github.com/testing-library/dom-testing-library/issues/1293 which might be a better place to track this rather this older closed issue? There is an open draft MR https://github.com/A11yance/aria-query/pull/547 to try address the fact that the implicit form role conditions appear to have changed whereby it is not now necessary to name a form to get a `form` role.
