### ISSUE TITLE
nested text contents of element with role=alert are not found on the screen

### ISSUE THREAD

**Issue by cabillin** [testing-library/dom-testing-library#941]
- `@testing-library/dom` version: 7.30.4
- Testing Framework and version:
  - "@testing-library/jest-dom": 5.12.0
  - "@testing-library/react": 11.2.6
  - "jest": 26.6.3
  - "jest-dom": 4.0.0

- DOM Environment:
  either 16.3.0 or 16.5.3 (not 100% sure bc we just switched from npm to yarn & our yarn.lock has multiple versions)

### Relevant code or config:

See repo: https://github.com/cabillin/dom-testing-library-alert-contents-issue/tree/alert-contents-inaccessible

### What you did:

Render [FluentUI TextField ](https://developer.microsoft.com/en-us/fluentui/#/controls/web/textfield) with error message & then try to query for contents of error message.

### What happened:

test output:
![image](https://user-images.githubusercontent.com/71525014/117093069-bd312d80-ad14-11eb-8470-9b386ca22b21.png)

Actual ui:
the span with id="TextFieldDescription#" is only rendered when the contents will be non-zero
![image](https://user-images.githubusercontent.com/71525014/117093172-14cf9900-ad15-11eb-892d-8d593c96da8e.png)

### Reproduction:
https://github.com/cabillin/dom-testing-library-alert-contents-issue/tree/alert-contents-inaccessible

### Problem description:

The nested text contents of the alert are not found on the screen even though they are visible.

### Suggested solution:

None

**Comment by cabillin** [comment]
Ok, I'll try that & get back to you

**Comment by eps1lon** [comment]
Closing since this was likely solved by following https://github.com/testing-library/dom-testing-library/issues/941#issuecomment-835679789
