### ISSUE TITLE
Incomplete typing for `MatcherOptions`

### ISSUE THREAD

**Issue by biniyam17** [testing-library/dom-testing-library#958]
Sorry to not use the template but I just had a simple question. 

Why does `MatcherOptions` have incomplete typing (see [here](https://github.com/testing-library/dom-testing-library/blob/main/types/matches.d.ts#L19)) when the usage on the official docs (see [here](https://testing-library.com/docs/queries/byrole/)) has more properties using `MatcherOptions`.

This is what the `getByRole` page shows
`getByRole(
  container: HTMLElement,
  role: TextMatch,
  options?: {
    exact?: boolean = true,
    hidden?: boolean = false,
    name?: TextMatch,
    normalizer?: NormalizerFn,
    selected?: boolean,
    checked?: boolean,
    pressed?: boolean,
    expanded?: boolean,
    queryFallbacks?: boolean,
    level?: number,
  }): HTMLElement`

but MatcherOptions only offers the following properties
`
export interface MatcherOptions {  
exact?: boolean 
trim?: boolean 
collapseWhitespace?: boolean  
normalizer?: NormalizerFn  
suggest?: boolean
}`

What does this mean?

If I want to use the following syntax `
   const { getByRole } = render(wrapper);
   const button = getByRole('button', { pressed: false });
`
typescript complains that pressed is not a property of MatcherOptions. It's not just pressed however, there a bunch of properties shown in the docs that are not specified in the interface.

This is either a bug or I am missing something. (If it is a bug, I can rewrite the issue in the proper format.) Any direction would be appreciated!

**Comment by eps1lon** [comment]
Thanks for the report.

It seems like you're using an older version of the library. With the latest version everything seems to be working as you'd expected:

```tsx
import { render } from '@testing-library/react';
import * as React from 'react';

const { getByRole } = render(<button />);

getByRole('button', { pressed: false });
```

[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzlApgOwCYqnAvnAMyghDgHIABGFAZxmDQHMBaAG2ACMoBDKATwD0qbgGMYZAFChIsOACo43GnABKKUfCIlywsZIkiIaOojiMUMAEJ8VEVijxwAvMnRYoACgA8HAK4wYIzgBAD4ASgBuCQlzKxs7FA8yPwCjMgAaUzBUGhoUDAAuOBgoXwdcMIkgA)
