### ISSUE TITLE
Throw better error message by findByRole query

### ISSUE THREAD

**Issue by vinaymahamuni** [testing-library/dom-testing-library#970]
### Describe the feature you'd like:
Currently if findByRole query doesn't find the element for given role and name, it throws error with message `TestingLibraryElementError: Unable to find role="button"`

Test to verify above behavior
```
it("Doesn't tell where it failed", async () => {
  render(<button>Click me</button>)
  
  await screen.findByRole('button', { name: 'submit' })
  await screen.findByRole('button', { name: 'Click me' })
})
  ```

In above test, I don't get feedback for which name the findByRole query failed.

For same scenario, if  getByRole query is used, it gives the name as well 
`TestingLibraryElementError: Unable to find an accessible element with the role "button" and name "submit"`

This helps in debugging. Specially when it fails on CI.

### Suggested implementation:

I looked the code. This behavior happen for all the queries which internally use `runWithExpensiveErrorDiagnosticsDisabled` function to run callback. In `src/queries/role.js` there is `getMissingError` function. In that there is one condition applied which tries to avoid expensive error diagnostics. This condition applies to `findByRole` function as well. I agree with decision. But I think that adding only namehint to the error string won't hit the performance.

### Describe alternatives you've considered:

Currently, I try to figure out where error might have occur using line number printed in stacktrace. But that is very difficult as I am using typescript + snowpack+ web test runner which runs test on browser and I don't get easy access to generated js files

### Teachability, Documentation, Adoption, Migration Strategy:

we can easily extract out function returning namehint and reuse it in first if condition
```
const getNameHint = (name) => {
  let nameHint = ''
  if (name === undefined) {
    nameHint = ''
  } else if (typeof name === 'string') {
    nameHint = ` and name "${name}"`
  } else {
    nameHint = ` and name \`${name}\``
  }
  return nameHint
}

const getMissingError = (
  container,
  role,
  {hidden = getConfig().defaultHidden, name} = {},
) => {
  if (getConfig()._disableExpensiveErrorDiagnostics) {
    return `Unable to find role="${role}${getNameHint(name)}"`
  }
  ...
  ...
  ...
  ...
  ...
  ...
  ...
}

  ```

**Comment by bobleujr** [comment]
I am experiencing the same issue. It happens to me specifically when I run headless in a container/pipeline
```1. If 'mat-icon' is an Angular component, then verify that it is part of this module.
Chrome Headless 93.0.4577.0 (Linux x86_64) UserDetailsComponent should display correct header FAILED
	SyntaxError: Failed to execute 'querySelectorAll' on 'Element': '*[role~="heading"],[object Set]' is not a valid selector.
	error properties: Object({ code: 12, INDEX_SIZE_ERR: 1, DOMSTRING_SIZE_ERR: 2, HIERARCHY_REQUEST_ERR: 3, WRONG_DOCUMENT_ERR: 4, INVALID_CHARACTER_ERR: 5, NO_DATA_ALLOWED_ERR: 6, NO_MODIFICATION_ALLOWED_ERR: 7, NOT_FOUND_ERR: 8, NOT_SUPPORTED_ERR: 9, INUSE_ATTRIBUTE_ERR: 10, INVALID_STATE_ERR: 11, SYNTAX_ERR: 12, INVALID_MODIFICATION_ERR: 13, NAMESPACE_ERR: 14, INVALID_ACCESS_ERR: 15, VALIDATION_ERR: 16, TYPE_MISMATCH_ERR: 17, SECURITY_ERR: 18, NETWORK_ERR: 19, ABORT_ERR: 20, URL_MISMATCH_ERR: 21, QUOTA_EXCEEDED_ERR: 22, TIMEOUT_ERR: 23, INVALID_NODE_TYPE_ERR: 24, DATA_CLONE_ERR: 25 })
	Error: Failed to execute 'querySelectorAll' on 'Element': '*[role~="heading"],[object Set]' is not a valid selector.
	    at queryAllByRole (node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1911:1)
	    at node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1355:1
	    at node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1330:1
	    at node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1383:1
	    at src/app/users/user-details/user-details.component.spec.ts:50:27
	    at <Jasmine>
	    at fulfilled (node_modules/tslib/tslib.es6.js:73:42)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-evergreen.js:372:1)
	    at ProxyZoneSpec.push.QpwO.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:301:1)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-evergreen.js:371:1)```

**Comment by eps1lon** [comment]
@MatanBobi The why is not questioned by the issue. For its rationale, check the git-blame: https://github.com/testing-library/dom-testing-library/pull/590

As to the issue about the missing name hint: I'm all for it. Thanks for catching this 👍🏻

**Comment by eps1lon** [comment]
> Regarding this issue, I'm up for doing it but I'm not sure how we can without running the expensive part of understanding the correct error message. Any ideas?

The issuer just asked for adding the expected name. That seems fine to me and doesn't require any expensive diagnostics as far as I can tell.

> sorry if it seemed like I was questioning it.

No need to appologize.
