### ISSUE TITLE
Missing type: wrapAllByQueryWithSuggestion

### ISSUE THREAD

**Issue by leepowelldev** [testing-library/dom-testing-library#972]
It seems that `wrapAllByQueryWithSuggestion` is missing from the query helpers Typescript types.

**Comment by MatanBobi** [comment]
@leepowelldev `wrapAllByQueryWithSuggestion` was migrated to TypeScript, is this still an issue?

**Comment by leepowelldev** [comment]
In 2 years I hope so 😂
