### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by janeerrai** [testing-library/dom-testing-library#989]
- `@testing-library/dom` version:
- Testing Framework and version:
  
- DOM Environment:
  

Relevant code or config

```js

```

What you did:

What happened:

Reproduction repository:
https://github.com/testing-library/dom-testing-library-template

Problem description:

Suggested solution:

**Comment by MatanBobi** [comment]
Hi @janeerrai,
This issue has no details inside.
I'm closing this one, if you do have an issue, feel free to edit the issue and comment here so I'll re-open it.
If you have a question, you can also try our [discord channel](https://discord.com/invite/testing-library) :)
