### ISSUE TITLE
getByRole 'button' with { name } fails @12.0.0

### ISSUE THREAD

**Issue by brookjordan** [testing-library/dom-testing-library#996]
After updating `@testing-library/react` from `11.2.6` to `12.0.0`, attempting to get a button by role and name doesn’t work. I initially thought this was due to the nested span, but when building the reproduction it appears the same issue arises when the text is directly in the button, or even in the `aria-label`

- `@testing-library/dom` 8.1.0:
- Testing Framework and version:
  `jest` 26.6.3
- DOM Environment:
  `jsdom` 16.6.0

### Relevant code or config:

```html
<button
  class="simple-button__button"
  id="14ec4cff-01d0-4067-9eeb-8a297dfd051a"
  type="submit"
>
  <span
    class="simple-button__button-text"
  >
    Cancel
  </span>
</button>
```

### What you did:

I attempted to get a button by role and name:
```js
const btn = screen.getByRole('button', { name: 'Cancel' });
```

### What happened:

```shell
  ● Dialog component › can press cancel button

    TestingLibraryElementError: Unable to find an accessible element with the role "button" and name "Cancel"

    Here are the accessible roles:

      button:

      Name "":
      <button
        class="simple-button__button"
        id="14ec4cff-01d0-4067-9eeb-8a297dfd051a"
        type="button"
      />

    Ignored nodes: comments, <script />, <style />
    <body>
      <div>
        <button
          class="simple-button__button"
          id="14ec4cff-01d0-4067-9eeb-8a297dfd051a"
          type="button"
        >
          <span
            class="simple-button__button-text"
          >
            Cancel
          </span>
        </button>
      </div>
    </body>
```

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-forked-3kbn2?file=/src/__tests__/button.js

### Problem description:

The recommended way to get an element is by role and name, but this is no longer possible.

(I also noticed that `toBeVisible` doesn’t exist on some `expect` assertions when building the reproduction. Note the comments on codesandbox)

**Comment by eps1lon** [comment]
Thanks for the report.

This looks like a codesandbox issue since all of the tests are passing once I replace `toBeVisible` with `toBeTruthy`. The issue looks similar to https://github.com/codesandbox/codesandbox-client/issues/5887

For `toBeVisible` you want to [install `@testing-library/jest-dom`](https://github.com/testing-library/jest-dom#usage)

**Comment by brookjordan** [comment]
In that case, is there any way for me to build a reproduction that you would accept? This issue is the same on my local machine and in GitHub CI.

**Comment by brookjordan** [comment]
I see you said that replacing `toBeVisible` with `toBeTruthy` makes the tests pass, that doesn’t seem to be the case on this side on codesandbox nor locally.

Did you possibly copy the entirety of the lower tests? The selectors are different to show that it’s only an issue with `getByRole`, not with `getByText` nor `getByLabelText`.

**Comment by eps1lon** [comment]
I downloaded the whole codesandbox and ran it locally. Since there's already a similar issue open on codesandbox, I'm fairly certain this is the same case here. 

If you have something that reproduces locally, please include it here.

**Comment by brookjordan** [comment]
Oh wow, thanks for bearing with me, turns out that there was an empty label tag referencing the button… TIL. I had no idea that this was valid HTML:

This will have a name of `''` (empty string):
```html
<label htmlFor="cancel"></label>
<button id="cancel">Cancel</button>
```

This will have a name of `'Cancel'`:
```html
<label htmlFor="cancel">Cancel</label>
<button id="cancel"></button>
```

I guess that this was “fixed” in the new version. Is this actually more correct? I would have expected that `getByRole('button', { name: 'Cancel' })` would still work in the first case.
