### ISSUE TITLE
Feature request: `waitFor` to throw error with initial check

### ISSUE THREAD

**Issue by zaicevas** [testing-library/dom-testing-library#998]
### Describe the feature you'd like:

`waitForElementToBeRemoved` does an initial check for the element and throws an error if the element is initially NOT present. Why couldn't `waitFor` behave in the same way and throw an error if the passed callback does NOT throw an error at the first check?

Example:
```
await waitFor(() => expect(true).toBe(true)) // throws an error
```

**Comment by alexkrolick** [comment]
`waitFor` is meant to handle possible asynchronicity, not enforce it.

`waitForElementToBeRemoved` throws an error because if the element reference wasn't in the DOM initially, you have a false positive with respect to the assertion - it wasn't removed, it just wasn't present at all.

**Comment by kettanaito** [comment]
I agree with @alexkrolick, throwing when the initial `waitFor` check resolves is not intended. I don't think this is an issue.
